### ISSUE TITLE
There's no frontend validation of 'Search query' field in LogUI

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1002]
##### Actual result:
User can input anything into _Search query_ field, then hit _Search_, however Loki (backend) only accepts labels (`{a="b"}`) as a query. This difference results in an error when user enters some invalid text there. Also, the brand new _Auto refresh_ feature executes form submit when its state becomes `play` which obviously produces similar error.
![image.png](https://images.zenhubusercontent.com/5ba8d87d4e030d642cf5cd1c/d909edda-9dcb-4dca-a914-3d57ad868281)

##### Expected result:
Form is not submit until _Search query_ has a valid (and not empty) value. Inform user if (and why) the value is invalid.

**Comment by sjanota** [comment]
Have to be taken into account during kyma-project/kyma#4711

**Comment by kwiatekus** [comment]
Already fixed in new Logging UI
