### ISSUE TITLE
Improve README.md for the Documentation Component

### ISSUE THREAD

**Issue by kazydek** [kyma-project/console#1029]
**Description**

Improve `README.md` for the [Documentation Component](https://github.com/kyma-project/console/pull/1017/files?file-filters%5B%5D=.md#diff-68765e49697ec464b80a812cffc714cc).

> **TIP:** Use [this](https://github.com/kyma-project/community/blob/master/guidelines/internal-guidelines/repository-template/template/README.md) template.

**Reasons**

There is just one sentence info on the component - needs improvement.

**Comment by derberg** [comment]
What actually has to be done, where in the repo? and is it really needed if this is internal component used in console only
