### ISSUE TITLE
Clicking "Save" in lambda details view multiple times creates multiple service bindings

### ISSUE THREAD

**Issue by sjanota** [kyma-project/console#1031]
**Description**
On the lambda details view, there is a possibility to add service binding. Once the binding is created you have to click "Save" to create in the backend. When the lambda is saved you can click the "Save" button again and one more binding will be created. You can repeat it how many times you like and that many bindings will be created. The result won't be visible until the page is refreshed. 

**Expected result**

Only one binding for service instance is created.

**Actual result**

Multiple garbage bindings exist

**Steps to reproduce**

Create a binding from lambda details view and hammer the "Save" button 

**Troubleshooting**

**Comment by kwiatekus** [comment]
The stack for serverless function will be reworked
