### ISSUE TITLE
Removing multiple service bindings in lambda view has no effect

### ISSUE THREAD

**Issue by sjanota** [kyma-project/console#1032]
**Description**
The user is allowed to remove multiple service bindings at once in the lambda details view. To confirm the operation he clicks the "Save" button. Everything looks fine until the page is refreshed. Only one service binding gets removed, others stay as they were.

**Expected result**

All chosen service bindings get removed

**Actual result**

Only one binding is removed and the user does not see the actual state

**Steps to reproduce**
1. Have a lambda with at least two service bindings
2. Go to the lambda details view of this lambda
3. Click the trash icon next to at least two bindings
4. Click "Save"

**Troubleshooting**

**Comment by kwiatekus** [comment]
The stack for serverless function will be reworked
