### ISSUE TITLE
Focus first input inside modals

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1034]
**Description**

When user opens a modal that has a form inside (there are few ones in the Console), the first input should be focused after the modal is shown to let the user type inside immediately.
Contact me @parostatkiem for an out-of-the-box solution (independent from Fundamental version).

**Related issues**
https://github.com/kyma-project/kyma/issues/4249

**Comment by kwiatekus** [comment]
Although this is still relevant, we will fix it case by case, not under such huge task.
