### ISSUE TITLE
Console: API View Improvements

### ISSUE THREAD

**Issue by tricky42** [kyma-project/console#1059]
The current API View in the console has a few shortcomings I marked in the attached screenshot. 

![apiview](https://user-images.githubusercontent.com/402282/61038111-b7928700-a3cc-11e9-8c0f-d62f70d8ba01.png)

1) Column Hostname: my understanding here is that we don't want to show the hostname here, I think it is the full URL to access the api (including everything needed, e.g. protocol, hostname, port). I think the column header should be URL or something better expressing what it is. 

2) Values shown in Column Hostname: while the value provided for the lambda works and the link opens the endpoint the values provided for the mocks dont work, as they are incomplete. My expectation is that I can use them in the same way as the value provided for the lambda. E.g. clicking the first icon should open the Varkes UI.

**Comment by sjanota** [comment]
The first obvious problem is that the API controller accepts hostname in two formats:
* <machine>.<domain>
* <machine>

While the second is not strictly a hostname it is convenient to use. UI needs to take it into account.

**Comment by sjanota** [comment]
We'll change the table so always FQDN is shown. Links and copying also will use FQDN.

@tricky42 According to [RFC describing URLs](https://tools.ietf.org/html/rfc3986#section-3.2) this part of URL is called "host". Also, [Wikipedia](https://en.wikipedia.org/wiki/Hostname#Internet_hostnames) says that hostnames for Internet addresses are FQDN. Is it ok to leave the header as is?

**Comment by tricky42** [comment]
@sjanota The column should always contain a valid URL according to the RFC. The host itself is potentially not enough, as it does not include parts like scheme, port, path or query. 

As a simple rule, the value in this column should always work when I copy and paste it into the address part of the browser. I think it is important, that we always use consistent values in the column and they always should follow this rule. 

If we do this, then the column header should be URL.

**Comment by kwiatekus** [comment]
Lets change the column name to `URL` and let's display full url:
 - Lets add missing schema (https://).
 - Currently, the definition of API does not contain url (with path, query, port etc..), but just the hostname
@piotrmsc Could you please include also full url in the API defintion?
