### ISSUE TITLE
Improve settings view 

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1073]
**Description**

Settings are visible in two places (top header menu + left navigation). Lets show it it only from top header menu.
Additionally, the view is confusing. It contains of:
- some org name and id which is not used, 
- button to download kubeconfig
- UI preferences

Lets:
- Get rid of the confusing org metadata ( not used)
- move download kubeconfig button to its own top level navigation entry, to make it more prominent
 - Make the remainings on that page only about UI preferences - visibility preferences

**Reasons**

We want to reduce left navigation size and define clear purpose for the view

**Attachments**
<img width="861" alt="Screen Shot 2020-05-19 at 10 54 30" src="https://user-images.githubusercontent.com/6783567/82306301-2c582980-99bf-11ea-8e54-3e789faa5736.png">

**Comment by kwiatekus** [comment]
When touching the code here, please move it to core-ui
