### ISSUE TITLE
Add-Ons Config view is not loading

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/console#1077]
**Description**
I click on Add-Ons Config view in the navigation. 

**Expected result**

Add-Ons Config view is displayed

**Actual result**

Page loading animation is displayed forever.
<img width="845" alt="Screen Shot 2019-07-17 at 09 20 45" src="https://user-images.githubusercontent.com/191769/61355221-30ce2600-a874-11e9-8e87-adab4c5e9501.png">

**Steps to reproduce**

- Install kyma CLI in the latest version (1.3.0)
- Install kyma on minikube:
    ```
    kyma provision minikube
    kyma install
    ```
- Log in to console and navigate to Add-Ons View

**Comment by sjanota** [comment]
The problem is that CLI in version 1.3.0 does not add domain `add-ons.kyma.local` to /etc/hosts, thus console cannot reach microfrontend. Here's the issue in CLI: kyma-project/cli#182

**Comment by kwiatekus** [comment]
Robot causa fixed
