### ISSUE TITLE
Add "ClusterMicrofrontends" CRD

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#108]
**Description**

Definition of **ClusterMicrofrontends** is similar to 'regular' **Microfrontends** CRD, with the difference  that they are not namespaced - they live in the cluster scope.

A ClusterMicrofrontend should have a property describing where the corresponding node should be added in the navigation (in the environment, in the global settings, .. other?)
A ClusterMicrofrontend is not namespaced, but can still be configured to show up in the navigation under environment. If it is the case, it would affect all environments (e.g. lambdas), not any specific one.

**Reasons**

To enable UI modularisation on the cluster level.

**Comment by kwiatekus** [comment]
https://github.com/kyma-project/console/pull/50
 https://github.com/kyma-project/kyma/pull/237

**Comment by kwiatekus** [comment]
Define additional attribute to the CRD defining where the cluster microfrontends should be shows (in the environment, in the global settings, .. other?). They should be shown in the environment's nav tree, unless defined so.

**Comment by kwiatekus** [comment]
Contact @hardl  before implementation (as it might have an impact on the ongoing restructure of the nav structure initiative)

**Comment by pekura** [comment]
Update:

Current state of the implementation is here: https://github.com/pekura/console/tree/multi-view-microfrontends. 

Things that are still to be done:
- MicroFrontend and ClusterMicroFrontend CRDs need to be updated with validation according to the upgraded design.
- Backwards compatibility must be decided on and implemented as needed.
- What placement options we need must be decided (currently two are implemented).
- Navigation node order and "hideNavigation" options must be implemented if needed.

**Comment by maxmarkus** [comment]
1. delete the existing crds: 
```
kubectl delete -f  ./kyma/resources/core/charts/console/templates/microfrontend.crd.yaml
kubectl delete -f  ./kyma/resources/core/charts/console/templates/clustermicrofrontend.crd.yaml
```
2. create new crds:
```
kubectl create -f  ./kyma/resources/core/charts/console/templates/microfrontend.crd.yaml
kubectl create -f  ./kyma/resources/core/charts/console/templates/clustermicrofrontend.crd.yaml
```
    
3. create the three test microfrontends
```
kubectl create -f sftest_lambdas.yml
kubectl create -f sftest_lambdas2.yml
kubectl create -f sftest_lambdas3.yml
```

[sftest_lambdas.yml.txt](https://github.com/kyma-project/console/files/2401648/sftest_lambdas.yml.txt)
[sftest_lambdas2.yml.txt](https://github.com/kyma-project/console/files/2401649/sftest_lambdas2.yml.txt)
[sftest_lambdas3.yml.txt](https://github.com/kyma-project/console/files/2401650/sftest_lambdas3.yml.txt)
