### ISSUE TITLE
Improve graphql error handling

### ISSUE THREAD

**Issue by akucharska** [kyma-project/console#1086]
**Description**

We're not showing graphql errors at all (Compass).
Graphql error:
Cannot query field "createApplicakhbvkhbtion" on type "Mutation". Did you mean "createApplication", "updateApplication", or "deleteApplication"?
What we're showing:
Error occored during creation Network error: Response not successful: Received status code 422
We should probably work on a better graphql error handling :)

**Comment by kwiatekus** [comment]
We will revisit CBS implementation and improve it iteratively
