### ISSUE TITLE
Integrate Luigi Client in service-catalog and instances

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/console#109]
**Description**

- direct link to details of a specific service class work
- direct link to details of a specific service instance work
- show link `add instance` in instance view and on click user should be redirected to the catalog
- the instance provisioning indicator/message contains a link to the details of new created instance

**Reasons**

- improve navigation between external views
- exposure paths of external views in `core` of Kyma console

**Comment by michal-hudy** [comment]
Review: @akucharska, @michal-hudy
