### ISSUE TITLE
lambda logs view opening behind lambda configuration view

### ISSUE THREAD

**Issue by k15r** [kyma-project/console#1104]
**Description**

on the current nightly cluster the logs view in the lambda interface is unusable as it opens behind the lambda configuration view. 

**Expected result**

usable logs view

**Actual result**

![Screen Shot 2019-07-25 at 16 44 19](https://user-images.githubusercontent.com/292906/61883906-8bfabb00-aefb-11e9-85a0-ced073cbc487.png)

**Steps to reproduce**

Create a lambda
open its configuration view
click logs

**Troubleshooting**

**Comment by kwiatekus** [comment]
Duplicates https://github.com/kyma-project/console/issues/1099
