### ISSUE TITLE
Consistent usage of status attribute in CRD

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#114]
**Description**

This is feedback from partner.

API exposing is done according to Kyma UI, but it took 30 seconds for the API to be accessable. This is long enough to fail when testing the API-endpoint and you think there is an error. Whenever something is not available right away, there needs to be a status for that resource.

**Problem**: 

> **The UI has no clue about the status of an API and require internals to reflect the reality.**

**Idea**: 
API resource uses proper "status" attribute based on underlying resources to indicate a realistic status. That should be done for all CRDs we have (if meaningful). Even the CRD resource has a status, it seems to be best practice. It should be using the new concept of sub-resources directly, it has the benefit of security - only the controller can change the status, not a user.
Assure that any general guideline for CRD should be reflected in our CRD guideline 

**Analysis**:
Resources without status:
- api
- environmentmapping
- eventactivation
- IDPPreset
- releases
- remoteenvironments (present but not used, will be awesome to see if connection works)
- microfrontends

Resources having status
- installation
- servicebindingusage
- subscription (not sure if meaningful)

**Reasons**

The UI has no clue about the status of an API and require internals to reflect the reality.

**Comment by pbochynski** [comment]
The API Custom resource already has a status. In the status you can check if resources for authentication policy (if applied) and virtual service are created.

**Comment by parostatkiem** [comment]
I took a closer look at the first resource (APIs) and it seems to not have any status field...
![image.png](https://images.zenhubusercontent.com/5ba8d87d4e030d642cf5cd1c/90656a7c-5de8-4de1-bcf7-4a2aefdb473e)

**Comment by kwiatekus** [comment]
Its hard to bite this subject as a whole.
This issue really got stale - a lot of resources mentioned changed..
We will follow up on API Status here : https://github.com/kyma-project/console/issues/996
