### ISSUE TITLE
Log search: Search button (magnifying glass) should be emphasized

### ISSUE THREAD

**Issue by PierreFritsch** [kyma-project/console#1140]
In Kyma 1.2.2

When I open the *Logs* 
and I select *Log Labels*: *app*
and I select an app in *Log Values*,
then the search button (magnifying glass) is activated.

However its current rendering is not sufficient to clarify that this button could/should be clicked next. The button is "lost" next to a *Query Examples* label and above a *Selected Labels* text.

I'd suggest to **make the search button stand out more**, for instance by emphasizing it (i.e. make it a white magnifying glass on a blue background)

![Screenshot 2019-08-05 at 15 47 37](https://user-images.githubusercontent.com/10234267/62470030-c84ed680-b799-11e9-87c7-666497f2c452.png)

Semantically, this button is different from the other search buttons in the kyma console, as it is not about finding an entry already displayed on the screen, but about triggering a search operation in the logs and displaying the corresponding results. How about even adding the verb "Search" next to the icon?

**Comment by kwiatekus** [comment]
With Kyma 1.6 the Log UI was completely reworked. The search button was removed in favor of auto-refresh feature
