### ISSUE TITLE
User is redirected to Runtimes after changing tenant

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1147]
**Description**

**Expected result**
User is not redirected to Runtimes after changing tenant. Compass stays at the same view.

**Actual result**
User is redirected to Runtimes after changing tenant

**Steps to reproduce**
1. Go to any other view than Runtimes
2. Change tenant using Luigi's context switcher

**Troubleshooting**
I have done absolutely nothing at all to solve this problem.

**Comment by kwiatekus** [comment]
Already fixed within https://github.com/kyma-project/console/issues/1391
