### ISSUE TITLE
CSS issues on Application Details after fundamental upgrade

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1150]
**Description**

1. "Namespace Bindings" title is misplaced.
2. Application name is shortened to several characters only

![Screen Shot 2019-08-08 at 11.51.57.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/0552d055-f822-49ce-a6ba-50e7f5fde511)

**Comment by parostatkiem** [comment]
2. https://github.com/SAP/fundamental-ngx/issues/1122

**Comment by parostatkiem** [comment]
The same problem as #1 found here:
![image.png](https://images.zenhubusercontent.com/5ba8d87d4e030d642cf5cd1c/2169dda5-64a7-4471-be08-30b1f36b814b)
