### ISSUE TITLE
Lambdas list not refreshing after using context switcher

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/console#1169]
**Description**

When you enter lambdas-list and the list is **not empty**, and you use context switcher to navigate to another namespaces that has **no lamba functions** defined you will see that view is not refreshed. 

**Expected result**

The list of lambda functions refreshes and the user is given information that no lambdas are defined.

**Actual result**

The list stays the same after navigation event, and you can see some lambas on the list, even though that is not true.

**Comment by kwiatekus** [comment]
The old lambda view is gone
