### ISSUE TITLE
Fix unique "key" prop error in fundamental

### ISSUE THREAD

**Issue by akucharska** [kyma-project/console#1182]
**Description**
Fundamental should pass key into components

**Expected result**

No error

**Actual result**

Warning: Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
see issue : https://github.com/SAP/fundamental-react/issues/512

**Comment by Wawrzyn321** [comment]
For an insightful observation, please reach me @Wawrzyn321

**Comment by parostatkiem** [comment]
Resolved by https://github.com/SAP/fundamental-react/pull/739

**Comment by parostatkiem** [comment]
And we have to remember to add `uniqueKey` and `key` props wherever we use Menu.Item component after the above changes got released.
