### ISSUE TITLE
Add a possibility to pass documentation specification directly, not by url

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1190]
**Description**

Add a possibility to pass the documentation specification directly, not by passing the url with the documentation in it.

**Reasons**

Generic documentation component works only when you pass the `url` attribute. In my case I want to pass the specification directly, not from the url.

**Attachments**

**Comment by magicmatatjahu** [comment]
Possibility will be added by https://github.com/kyma-project/console/pull/1164

**Comment by dariadomagala** [comment]
Done in https://github.com/kyma-project/console/pull/1164
