### ISSUE TITLE
Luigi integration in `content` view

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/console#120]
**Description**

- integration `Luigi Client` with `content` view,
- direct link to specific documentation topic and fragment.

**Reasons**
- more readable url in browser address window for users,
- the ability to open documentation with specific fragment of content of specific topic directly from the link,
- smaller configuration from side of external application: The logic is performed on the `Luigi` side.

**Comment by derberg** [comment]
@magicmatatjahu hey, 0.6 comes with Console fully luigified. Please check what we would have to do to enable docs linking and update this ticket with details

**Comment by derberg** [comment]
still valid

**Comment by derberg** [comment]
not needed atm
