### ISSUE TITLE
Introduce dynamic icons in Compass GenericList's action element

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1203]
**Description**
GenericList's actions element should not always be a popover. In case it contains some well-known actions, such as **delete** and **edit** (which is a majority), it should be displayed as icons (trash, pencil etc.; not in a popover). 

The popover should only be displayed in case:
- there are some other actions than well-known ones with icons
- there are more than **3** (to be discussed) well-known actions with icons.

![image.png](https://images.zenhubusercontent.com/5ba8d87d4e030d642cf5cd1c/0b8c9011-93ac-4ab3-ace8-c9512013f52a)

#### Stretch goal:
- Allow adding custom icons to actions
- display icons also in the popover in case not all of them can be displayed outside.

**Reasons**
It's cool 😎

**Attachments**

**Comment by kwiatekus** [comment]
Duplicates https://github.com/kyma-project/console/issues/1385
