### ISSUE TITLE
Modal is not closing after creating credential

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1207]
**Description**

In instances details view, if you open 'Create Credentials' modal, and click enter multiple times, multiple credentials are added and modal is not closed. 

**Expected result**

After creating a credential, modal should close.

**Actual result**

If you add a credential using enter instead of 'Create' button, modal is not closed. At first because of that I though that credential was not created, so I pushed enter few more times, and created many credentials I didn't need. 

**Steps to reproduce**

* create an instance that will have 'Credentials' tab (for example testing bundle with full plan)
* go to its details
* go to 'Credentials' tab
* click '+ Create Credentials' button
* focus on input
* click enter few times - multiple credentials added, modal still open 
* click 'Create' button - one credential added, modal is closed

**Troubleshooting**

**Comment by kwiatekus** [comment]
This issue doesn't occur anymore after refactoring on instances view.
