### ISSUE TITLE
Support fragment navigation in console views with tabs

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/console#121]
**Description**

- Support fragment navigation in `service-catalog` and `instances`, e.g.:
  - after entering the link `.../instances/details/redis-instance#bindings` or `.../instances/details/redis-instance#binding-usages` the specified tab is automatically opened,
  - after entering the link `.../instances/details/redis-instance#(documentations|events|etc)` the specified tab is automatically opened,
  -  ~after entering the link `.../instances/details/redis-instance#delete`, `.../instances/details/redis-instance#create-binding`, `.../service-catalog/details/redis#create`, `.../instances/details/redis-instance#plan-parameters` the specified modal with specific functionality/information is automatically opened.~

Please take into account the following views with tabs
 - Lambda ui 
 - permissions (cluster roles, roles, bindings)
 - resources (resource quotas, limit ranges)

**Reasons**

- improve navigation in `service-catalog` and `instances`.

**Comment by derberg** [comment]
@magicmatatjahu please double check state of console and luigi after 0.6 and if we can go forward with this ticket or not

**Comment by derberg** [comment]
still valid

**Comment by kwiatekus** [comment]
We will handle current tab using luigi parameters.
We will not provide parameter support for linking to a specific operations : for example instance creation or deletion.
