### ISSUE TITLE
Unify the way of embedding JSONeditor, add mode switcher

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1211]
1. Currently we use JSON editor in two separate places and two separate ways. One is `Ace` wrapped in a React component/library, the other is not wrapped. 
This should be unified. Examine benefits and consequences of each solution, then decide to use one. From my personal perspective, "naked" Ace seems reasonable.

2. Our editor supports few ways of displaying JSON - code and tree mode. Let user decide in which way he wants to see his JSON.

**Comment by kwiatekus** [comment]
As we decided to go with monaco editor for new lambda view, maybe it would be better to unify all existing JSON editors with monaco editor.

**Comment by kwiatekus** [comment]
closing in favor of https://github.com/kyma-project/console/issues/1897
