### ISSUE TITLE
Show bound service classes for application on namespace details

### ISSUE THREAD

**Issue by sjanota** [kyma-project/console#1229]
**Description**

Show number of service classes  available in the namespace `X` that originate from a given application binding.  Also, show number of all available service classes `Y`   (x out of y - `x/y`)

Allow to inspect a full list of used service classes once user clicks on the application name.

**Reasons**

Namespace details view should provide holistic view about the namespace - also giving the information about what services classes come from which remote application binding

**Attachments**
<img width="941" alt="Screen Shot 2019-11-13 at 13 46 32" src="https://user-images.githubusercontent.com/6783567/68768615-2ace3300-0623-11ea-8297-6c5004f097f0.png">

<img width="921" alt="Screen Shot 2019-11-13 at 14 37 19" src="https://user-images.githubusercontent.com/6783567/68768600-2275f800-0623-11ea-8922-1081c31841d3.png">

**Comment by kwiatekus** [comment]
The application binding to specific namespace is being discussed.
It might be that this concept will be significantly redesigned
