### ISSUE TITLE
Edit namespace memory configuration

### ISSUE THREAD

**Issue by sjanota** [kyma-project/console#1235]
**Description**

User can edit limit ranges and resource quotas for existing namespace

**AC**

- Modal is dismissed on <ESC>
- New labels are validated and added on <tab> button
- label field is auto-focussed when modal is opened 

**Attachments**

https://app.zeplin.io/project/5ab0db46508f1e7a678a01c1/screen/5d148b753ea6b873570ca62f

Stay consistent with the current implementation in `create namespace` modal
![Screen Shot 2019-09-09 at 15.56.25.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/220f7613-be08-4126-aec7-214889548368)

**Comment by kwiatekus** [comment]
Duplicated by #1234
