### ISSUE TITLE
Console basic test fails if testnamespace already exists 

### ISSUE THREAD

**Issue by sjanota** [kyma-project/console#1239]
**Description**
Console basic test fails if namespace `testnamespace` already exists. The namespace may be created by a different test in the meanwhile, so we need to be more resilient here. The namespace name should be random to avoid races between tests.

Make sure generic namespace is used both in **UI** and **cbs**. 

**Attachments**

**Comment by akucharska** [comment]
Besides testing Namespaces and pods there is also static namespace used in secrets
```
=== RUN   TestSecret
 --- FAIL: TestSecret (4.12s)
     secret_test.go:69: Creating namespace...
     secret_test.go:71: 
         	Error Trace:	secret_test.go:71
         	Error:      	Received unexpected error:
         	            	namespaces "console-backend-service-secret" already exists
```
