### ISSUE TITLE
Configure DEX as identity provider for Compass UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1268]
**Description**

Compass API will be protected by bearer token soon.
We need to configure the onboard DEX as ID Provider via luigi config.

There will be dedicated dex client for compass (with local dev url : ` http://compass-dev.kyma.local:8080`)

**AC**
 - IPD configuration is injectable via configmap 
 - Bearer token is sent from luigi core to MFs as context and sent as `Authorization` header with every gql request
 

**Reasons**

Allow users to consume protected compass-gateway API from compass UI

**Comment by kubadz** [comment]
Please use the following Compass URL, as it is the one secured with JWT. Currently, both secured and unsecured (the default one) will coexist, but it will change soon. 
```https://compass-gateway-auth-jwt.kyma.local```
