### ISSUE TITLE
Compass : Combobox in modal css issues

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1274]
**Description**

The combobox/popover component is not rendered properly when put inside modal.

We need to upgrade Fundamental in Compass. 

Examples : 
 - create application modal (scenario selector)
<img width="746" alt="Screen Shot 2019-09-23 at 10 01 17" src="https://user-images.githubusercontent.com/6783567/65409961-6568db80-dde9-11e9-8baf-c2329a081e34.png">

 - create API (credentials type chooser)

<img width="539" alt="Screen Shot 2019-09-23 at 10 04 22" src="https://user-images.githubusercontent.com/6783567/65410041-9fd27880-dde9-11e9-981c-ee44a19241e8.png">

**Expected result**

The options of the combobox should render on top of modal.

**Troubleshooting**

We know already that this problem was fixed already in 0.7.0 version of the `fundamental-react` library. This version however introduces different bug around combos inside modals -  propagation of onClick event (https://github.com/SAP/fundamental-react/issues/649). Please walk it around or contribute to the fundamental-react, so that we could upgrade to the latest version.

**Comment by parostatkiem** [comment]
This one needs to be merged:
https://github.com/SAP/fundamental-react/pull/789

**Comment by tricky42** [comment]
Has the fix for this issue being delayed?
