### ISSUE TITLE
Allow selecting precise time constraints for logs

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1299]
**Description**

As a user I want to read logs from a specific time-box. I want to specify start and end timestamp to filter out logs in Log UI

**Reasons**

Currently we have rather limited options to filter logs basing on time constraints. 

<img width="173" alt="Screen Shot 2019-12-12 at 16 07 49" src="https://user-images.githubusercontent.com/6783567/70723701-a04c2280-1cf9-11ea-961c-3b047fbb2f68.png">

For a person who is monitoring the system a very specific time slots are very useful.

**Comment by pbochynski** [comment]
I disagree with the stale bot and I would like to see that feature.

**Comment by VishnAndr** [comment]
voting up this request pls

**Comment by kwiatekus** [comment]
INvalid already.
We decided to replace log UI with deep links to grafan which is the right tool for the job:
https://github.com/kyma-project/kyma/issues/9196
