### ISSUE TITLE
Select function's event triggers

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1313]
**Description**

As a user I want to configure an event trigger for my lambda function.
User should be able select multiple events from the ones available in the namespace (defined via api specs) or even type in arbitrary strings as events (as there might be service instances available in the namespace that produce events, but do not have async api specs explicitly defined  )

**AC**

 - User can select event(s)  from all events available in the namespace (w/o storing the data)
 - User can find available events using text search match (search-as-you-type). 
 - User should see a sample payload of the selected event(s)
 - User can type in arbitrary string as a event(s) 

** Hints**

Do not show events as labels in the code section. Use a dedicated section in the right panel.
Add new triggers using `+` action in the section header.
Avoid changing modal size during search and filtering.
Allow expanding details (sample payload) of a single event.

**Comment by magicmatatjahu** [comment]
**Change of scope**

AC:
- User can select event(s) from all events available in the namespace (w/o storing the data)
- User can find available events using text search match (search-as-you-type).

Stretch:
- User should see a sample payload of the selected event(s)
- User can type in arbitrary string as a event(s)
