### ISSUE TITLE
Advanced Function Managament

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1315]
**Description**

Provide  advanced function management options. 
Provide IDE-like development experience.

User should be able to manage:
 -  service bindings (re-use the components from service instances view)
 -  dependencies
 -  env variables
 - event triggers

... in such a way that the components for those goals should be available at hand, but do not introduce too much noise on the function details view. The main focus of the user should be the function's code

**Attachments**

**Comment by michal-hudy** [comment]
It has been split into smaller issues in Kyma repository that also covers backend.
