### ISSUE TITLE
Service Instance Details view not refetching Instance data

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/console#1321]
**Description**

When you move from the list of all instances to its details the Service Instances details are fetched from the GraphQL-based backend service. If you move out of the view and go back to it later, the data will be fetched from the Apollo cache, even though Apollo configuration has `fetchPolicy: 'no-cache'` enabled.

**Expected result**

Data is being re-fetched every time users visit the view.

**Actual result**

Data is loaded from Apollo's cache.

**Comment by jose-cortina** [comment]
Although this issue is considered critical, there is a workaround (reload the page).
It does not block the 1.8 release and is planned for 1.9.
