### ISSUE TITLE
A tool to automatically bump console images on a cluster 

### ISSUE THREAD

**Issue by sjanota** [kyma-project/console#1333]
**Description**

We could have a tool running on a cluster that will automatically update console images in a cluster. It could listen to PR merged events from github webhook and update images build on presubmits to the version from the merged commit. It could be either a lambda or a separate deployment. It needs to have access to the cluster so lambda may not be suitable.

**Reasons**

Having a cluster with all recent changes will help us to develop faster as we won't need to create a new cluster every time something changes on master.

**Attachments**

**Comment by kwiatekus** [comment]
done
