### ISSUE TITLE
Replace catalog e2e UI tests with Enzyme tests

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1340]
**Description**

1. Refactor Catalog UI to make it testable and easier to connect with websockets.
2. Add enzyme integration tests that verify the same scenarios as ui-acceptance do.
3. Leave only smoke test in ui-accpetance

**Reasons**

Currently it is impossible to properly test Catalog UI.

**Attachments**

**Comment by kwiatekus** [comment]
Please take this into consideration:
https://github.com/kyma-project/console/issues/1245
