### ISSUE TITLE
console readme need update , you cant access to link , its redirect github 404

### ISSUE THREAD

**Issue by delokman** [kyma-project/console#1348]
OSBA Contract
Contract with OSBA is available in the Catalog view document.

where are documents related ui?

**Comment by derberg** [comment]
Hey @delokman 
Could you please provide a bit more context. I'm not sure how we can help you atm.

The Contract we have for the OSB API and the Console UI is described here https://kyma-project.io/docs/components/service-catalog/#console-ui-views-ui-contracts
Is this what you were looking for? Is this link missing somewhere? you suggest we should add it somewhere?

**Comment by derberg** [comment]
No answers provided, hard to do any fixes without more details
