### ISSUE TITLE
UI for creating remote environments

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#135]
Should work like creating IDP presets with the following fields (as described in https://github.com/kyma-project/community/blob/master/sig-and-wg/sig-core/proposals/remote-environment-creation.md):

* name
* description
* labels 
   - Key1:Value1
   - Key2:Value2
   - ...

For labels, see the labels editor used in lambdas view.

**Comment by kwiatekus** [comment]
Changes in RemoteEnv CRD and ui-api-layer planned (breaking changes)
We need to sync with framefrog team
