### ISSUE TITLE
Specify function memory limits and instances count instead of 't-shirt' sizes

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1356]
**Description**

Replace simple functions size presets (`S`,`M`,`L`, etc) with more precise and understandable limits.

**AC**

 - User can specify number of function instances for new and existing functions.
 - User can specify memory limits for new and existing functions.

**Reasons**

Function sizes (`S`,`M`,`L`, etc) are not accurate and might be confusing for the user. An option to specify number of instances and memory limits appears more straight-forward

**Comment by michal-hudy** [comment]
Already implemented
