### ISSUE TITLE
Prototype for API Rule creation flow

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1359]
**Description**

Visualise how user could create API Rule in Kyma.
Take into account the [API Rule CRD](https://kyma-project.io/docs/components/api-gateway-v2/#custom-resource-api-rule)

![Screen Shot 2019-10-30 at 15 21 17](https://user-images.githubusercontent.com/6783567/67866245-f178cc00-fb28-11e9-996a-c5fc2c73367d.png)

**Comment by kwiatekus** [comment]
As a start lets model 3 types of startegies : 

 1. **Pass-all** (pass all through, no authz required) 
  - no configuration required
 2. **JWT** (jwt token required to pass through) 
  - [sample config](https://github.com/kyma-incubator/api-gateway/blob/master/config/samples/valid.yaml#L93):
    - *trusted_issuers*: list of strings
    - *required_scope*: list of strings
 3. **OAuth2** (access token required to pass through) 
  - [sample config](https://github.com/kyma-incubator/api-gateway/blob/master/config/samples/valid.yaml#L113):
    - *required_scope*: list of strings

**Comment by kwiatekus** [comment]
No UI support for mutators in first iteration. lets start with the basic functionality.

**Comment by parostatkiem** [comment]
TODO: Remove setting the navigation node, then merge.
