### ISSUE TITLE
Rework all Makefiles and Dockerfiles

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1362]
Since the main Console components are no longer dependent on _components/*_ we can remove many steps from our Makefiles and Dockerfiles. I mean mostly the building process of those dependencies. I also believe some copying work can be done smarter.

Whoever does this, will get a sticker! ![20191031_093439.jpg](https://images.zenhubusercontent.com/5ba8d87d4e030d642cf5cd1c/92f03144-d693-4e94-9ea6-6e5b152af0bb)

**Comment by kwiatekus** [comment]
Done with changes : https://github.com/kyma-project/console/issues/1744
