### ISSUE TITLE
Changes in Event Activation might impact lamda ui.

### ISSUE THREAD

**Issue by venturasr** [kyma-project/console#137]
Following the improvement in the Remote Environment, we have found out that there is a query to `EventActivation`, which is likely to be changed.

This issue aims to get answers to the questions below.

- Are there plans to change EventActivation CRD?
- How the query should be adjusted?
- Is there are any related github issue?

```getEventActivations(environment: string, token: string): Observable<EventActivationResponse> {
    const query = `query EventActivations($environment: String!) {
      eventActivations(environment: $environment) {
        name
        displayName
        source {
            environment
            type
            namespace
          }
          events {
            eventType
            version
            description
          }
        }
}`;
    const variables = { environment };
    return this.graphQLClientService.request(
      AppConfig.graphqlApiUrl,
      query,
      variables, token);
  }

**Comment by PK85** [comment]
Related issue on gopher side, see answers:
- https://github.com/kyma-project/kyma/issues/723

**Comment by PK85** [comment]
Closing issue as answers are provided via #723
