### ISSUE TITLE
Get rid of react-components dependency in new 'shared' catalog

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/console#1373]
**Description**

The new `GenericList` component (`shared/components/GenericList/GenericList.js`) has a dependency to an 'outer' library, that is `@kyma-project/react-components` - two components are used (`TableWithActionsToolbar` &  `TableWithActionsList`). It causes increased bundle size, and should be re-written to suit our needs.

**Reasons**

1. Reduced bundle size, from 1.5 MB to ~200 KB. 
2. No more dependency to 'outer' library.

**Comment by kwiatekus** [comment]
Fixed with https://github.com/kyma-project/console/pull/1847
