### ISSUE TITLE
Styles incorrectly/not applied when running Console in development mode

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/console#1379]
**Description**

If user navigates to another view when notification is opened, notification breaks.

**Expected result**

Notification looks _normal_ and persists between views.

**Actual result**

Notification looks silly.
![image](https://user-images.githubusercontent.com/10504661/68482038-f3354480-0238-11ea-8445-712fdccea4bf.png)

**Steps to reproduce**

1) Go to Lambda details and update it - a "normal"-looking notification should be displayed.
2) Before notification hides, go back to Lambdas list (using either Luigi navigation or breadcrumbs).
3) Notification breaks as shown in screenshot.

**EDIT**: Looks like it happens **only** when running in development mode - deployed versions are not affected.
Compass' modals (Create Application/Scenario) are also affected.

**Comment by parostatkiem** [comment]
Seems to have already been solved. Notifications are closed once user quits the view that has triggered them.
Checked in both Console and Compass.
