### ISSUE TITLE
Display essential runtime properties

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1405]
**Description**

There are some specific meta information applied on runtimes that define it's essential properties, for example : 
 - console URL
 - event service URL
- ....

Those properties have very specific label prefix : `runtime_....`, which makes them easy to find and promote into a dedicated section on the runtime details view.

**AC**

 - those properties are regular meta data (labels),  so they should also be visible in the tab for metadata (#1404 )
 - those properties have string values - schema less - please make it easy to copy the content
 - any label with key matching the `runtime_...` prefix and string value should appear in the dedicated `{Runtime_Name} Essentials` panel

**Reasons**

Display essential properties of the runtime in a way the user wont miss them.

**Attachments**

![20191118_162559](https://user-images.githubusercontent.com/6783567/69066010-e7a80180-0a20-11ea-9025-ce3e996c6d67.jpg)

**Comment by tricky42** [comment]
Just a question, does it really make sense to store such information in labels? My understanding is that we have an "entity" for our runtimes, why dont we store such important information not as an property of this entity. Using labels for such essential information feels like a misuse of labels.
