### ISSUE TITLE
Instances of Addon Classes defined via namespaced AddonsConfiguration end up in "Services" tab in UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1432]
**Description**

An addon instance (if addon was configured via namespaced configuration) appears in wrong tab in service instances list view.

**Expected result**

Instances of addon classes should end up on the list under 'Addons' tab on service instances list

**Actual result**

Instances of addon classes end up on the list under 'Addons' tab on service instances list

<img width="1641" alt="Screen Shot 2019-11-27 at 14 00 19" src="https://user-images.githubusercontent.com/6783567/69725449-7fdb7000-111e-11ea-8343-5d1cd8bd3775.png">
<img width="1660" alt="Screen Shot 2019-11-27 at 14 00 31" src="https://user-images.githubusercontent.com/6783567/69725457-8669e780-111e-11ea-9700-ec0cbc1f26f1.png">

**Steps to reproduce**

1. Log in to console
2. configure an addon configuration in a namespace (i.e [varkes mocks](https://storage.googleapis.com/faros-prod-base-xf-bundles/index.yaml).
3. Go to service catalog for this namespace and find the addon class (under Addons tab).
4. Create an instance of the class - observe, that an instance ends up under `Services` tab.

**Comment by akucharska** [comment]
Already fixed
