### ISSUE TITLE
Creating an app/runtime reloads the whole view

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1457]
**Description**

Creating an application or runtime reloads the whole list view in the Compass UI. 

**Expected result**

Creating an application or runtime should add this entry to the list but shouldn't reload the whole view.

**Actual result**

Creating an application or runtime reloads not only list but also header etc.

**Steps to reproduce**

* Go to application/runtimes list
* Create a new entry
* Whole list view reloads

**Troubleshooting**

**Comment by kwiatekus** [comment]
Not a priority at the moment
