### ISSUE TITLE
New loading message

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1458]
**Description**

Current 'loading..' message is well... ugly. 
Also, sometimes it is shown multiple times on a page. For example, on scenario details page, 'loading..' is shown separately for header and two lists.
![Screen Shot 2019-12-05 at 13.24.56.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/db3bf53f-45c3-429f-a068-85e9dbbad4b9)

**Reasons**

Make compass pretty :) 

**Attachments**

**Comment by kwiatekus** [comment]
Ideas from sprint planning:
 - main component should use loading indication from Luigi ( in this example -  header ). Child components are not rendered ( in any state) in case parent is not ready to host them
 - child components should render only when parent component is loaded and is ready to host them
 - child components will have individual loading states

**Comment by kwiatekus** [comment]
Not a priority
