### ISSUE TITLE
No message why validation failed

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1459]
**Description**

There is no message why validation failed while typing URLs in 'create new API' modal.
![Screen Shot 2019-12-04 at 11.50.24.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/2509e471-769c-4437-a67d-8028b5c072d5)
![Screen Shot 2019-12-05 at 13.39.18.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/09987041-2d55-49cb-a2a6-62a0e9986163)

**Expected result**

The user should know what is expected to be in an input field. 

**Actual result**

The user is not allowed to submit the form but doesn't really know why.

**Steps to reproduce**

* Create an application
* Go to its details
* Open the 'add new API' modal
* Upload a file with an open API type
* Fill all fields but all URLs write without 'http://' or 'https://' at the beginning. 

**Troubleshooting**

**Comment by kwiatekus** [comment]
Will be fixed within:
https://github.com/kyma-project/console/issues/1403
