### ISSUE TITLE
Vulnerable dependency in console repo -`serialize-javascript`

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1465]
**Description**

Github detected a security vulnerability in console:

https://github.com/kyma-project/console/network/alert/lambda/package-lock.json/serialize-javascript/open

Please upgrade vulnerable dependency

**Comment by Wawrzyn321** [comment]
We need to wait for finishing an [issue in this Angular package](https://github.com/angular/angular-cli/issues/16414), as it still uses vulnerable version.

**Comment by sergio-oss** [comment]
@kwiatekus still applicable ?
