### ISSUE TITLE
Additional not needed failing calls in the Catalog view

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#150]
**Description**

We should have one POST request to graphql per view. Please check why this bug is happening in whole Catalog View. What I described below also happens in details view when I click `Add to your Environment` button, another 2 POST calls are triggered 

**Expected result**

One POST request to UI API layer, this is one of the reasons we use GraphQL ;)

**Actual result**

When I go to details of the specific class, there are 3 POST request sent to ui-api-layer, the one for class details and two about service instance `{"operationName":"serviceInstance","variables":{"environment":"production"},"query":"query serviceInstance($name: String!, $environment: String!) {\n  serviceInstance(name: $name, environment: $environment) {\n    name\n    __typename\n  }\n}\n"}` and they both respond with `null` of course

**Steps to reproduce**

Install kyma and local and go to https://console.kyma.local/home/environments/production/service-catalog/details/a2257daa-0e26-4c61-a68d-8a7453c1b767

**Troubleshooting**

I opened console in chrome and troubleshooted catalog view with Network tab of Dev Tools

**Comment by pkosiec** [comment]
Review: @akucharska @pkosiec
