### ISSUE TITLE
Fix missing HSTS Header

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/console#1508]
**Description**

Checkmarx audit has shown that a HSTS header is missing in `logging/src/services/httpService.js`.

![image](https://user-images.githubusercontent.com/10504661/71726663-1bf04980-2e38-11ea-96bb-f5baa40353ef.png)

A message from Checkmarx: `The web-application does not define an HSTS header, leaving it vulnerable to attack.`

This issue is of _medium_ severity.

**Comment by akucharska** [comment]
This is false positive. Checkmarx thinks we are making a http response without headers. We are not. This code is receiving response from another service
