### ISSUE TITLE
Invalid color of checkbox background in lambda HTTP trigger

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/console#1510]
**Actual result 1**
![image](https://user-images.githubusercontent.com/10504661/71898243-173dd500-3159-11ea-93e1-8cc626aaeb15.png)

**Actual result 2**
![image](https://user-images.githubusercontent.com/10504661/71898265-2ae93b80-3159-11ea-9c98-d004e241d70e.png)

Note that both screenshots were taken while using the same cluster (1.9 RC2).

**Comment by kwiatekus** [comment]
This wont get fixed. The view will be deprecated and new lambda UI will replace it
