### ISSUE TITLE
Use subscriptions for Instances view

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/console#156]
AC:
- [ ] Configure Apollo Client on UI
- [ ] enable websockets on listing instances so without page refresh
  - we see new instances are added to the list
  - particular instance disappears from the list in case it is deleted
  - status is updated from PROVISIONING to READY or any other status, and the status.message too

**Comment by michal-hudy** [comment]
It is not possible to connect to UI API, because Apollo Client 2 don't support HTTP headers for WebSocket connection - https://github.com/apollographql/apollo-client/issues/3967

Also we need to consider global WebSockets for `Service Binding` and `Service Binding Usage`.

**Comment by derberg** [comment]
@michal-hudy check if we can downgrade to Apollo 1 or check if we can do some other solution here, some custom stuff on istio or something

**Comment by pkosiec** [comment]
Review: @michal-hudy @magicmatatjahu
