### ISSUE TITLE
Clicking actions dropdown in the namespaces list crashes the view

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1568]
**Description**

Clicking actions dropdown in the namespaces list crashes the view.
![Screen Shot 2020-02-18 at 14 56 56](https://user-images.githubusercontent.com/40663133/74742575-1f605880-525f-11ea-97fb-cd283faf56c4.png)
![Screen Shot 2020-02-18 at 14 58 54](https://user-images.githubusercontent.com/40663133/74742626-34d58280-525f-11ea-854b-b4c3a335d329.png)

**Expected result**

User should be able to delete the namespace from the list view, the application shouldn't crash.

**Actual result**

Application crashes, user cannot delete namespace from the list view.

**Steps to reproduce**

* Go to namespaces list
* Click actions dropdown

**Troubleshooting**

The error probably comes from fundamental.

**Comment by Wawrzyn321** [comment]
This issue exists on core-ui @ f240c978, it will be resolved with next core-ui version bump (ex. b1759d58).
