### ISSUE TITLE
Show lambda build and execution logs in UI

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/console#1582]
**Description**

Display Lambda logs in UI. Logs from building an image should also be visible in UI. 

![image](https://user-images.githubusercontent.com/26445970/77990557-ee754800-7321-11ea-8d1b-05a6c3da8c63.png)

**Reasons**

**Attachments**

**Comment by pPrecel** [comment]
Great the function's name ;)

**Comment by michal-hudy** [comment]
Use `UUID` instead of name

**Comment by michal-hudy** [comment]
@aerfio Is it possible to remember the Logs panel state when you switch tabs (Code <-> Config)? It is a little bit annoying when it opens/closes between switches.

**Comment by michal-hudy** [comment]
And I think it should be by default closed

**Comment by michal-hudy** [comment]
Closed by mistake ;)

**Comment by magicmatatjahu** [comment]
@michal-hudy Memorizing of open/close state is fix already in this https://github.com/kyma-project/console/pull/1706 Also panel will be close by default after merging mentioned PR.
