### ISSUE TITLE
Runtimes view sends query twice. Wrong error handling

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1608]
**Description**

1. Runtimes view sends query twice.
2. When a response contains both: errors and data, the view ignores the data and writes errors on the screen

**Expected result**

1. The view should send single request to fetch runtimes
2. If response data is there, render it. If error is there, render it additionally in a dedicated error component

**Steps to reproduce**

Log in to compass ui and navigate to runtimes

<img width="1424" alt="Screen Shot 2020-03-11 at 11 14 45" src="https://user-images.githubusercontent.com/6783567/76425544-10764d00-63aa-11ea-8b99-fc915daab724.png">

**Comment by PK85** [comment]
@kwiatekus not only runtimes query are twice, I also see other places like Scenario Name details view. Every call is doubled. Please check other places as well. Cheers
