### ISSUE TITLE
Cannot distinguish APIs from multi API packages in service catalog UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1617]
**Description**

Is a package contains multiple APIs, I cannot distinguish them based on the tab names. 
All of the tabs corresponding to  APIs have  `Console #` name.

So user needs to click through them to find the API spec he is looking for.

**Expected result**

The tab names reflect API names 

**Actual result**

All of the tabs corresponding to  APIs have  `Console #` name.

**Proposed solution**
The discussion between different teams produced an outcome of a possible solution:
- add an optional `displayName` field to the _Source_ type of the Rafter domain (assetgroup_common.go:35)
- populate the field with data from Compass Director when converting app to service
- use the field as a tab title for an API

<img width="1917" alt="Screen Shot 2020-03-13 at 13 20 08" src="https://user-images.githubusercontent.com/6783567/76620454-7b03c600-652d-11ea-84e6-605d5902c084.png">

**Comment by michal-hudy** [comment]
Will this value be propagated to the corresponding Assets, or it will be only in AssetGroup? I would recommend passing this value also to the Asset, because you can search Assets created by AssetGroup by label.

Please also fill a proper issue in the Rafter repository.

**Comment by parostatkiem** [comment]
@michal-hudy https://github.com/kyma-project/rafter/issues/71
and I think we can add this field also to the _Asset_ type.

**Comment by kwiatekus** [comment]
Fixed
