### ISSUE TITLE
Event API Documentation rendering bug

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/console#1618]
**Actual result**

![image](https://user-images.githubusercontent.com/10504661/76632748-fb352600-6543-11ea-896c-7acb42f15df3.png)

Spec: [sap-commerce-cloud.txt](https://github.com/kyma-project/console/files/4330160/sap-commerce-cloud.txt)

**Comment by magicmatatjahu** [comment]
AC:
- contribute to compass with conversion from 1.X.X of AsyncAPI spec to 2.X.X by https://github.com/asyncapi/converter-go

**Comment by michal-hudy** [comment]
The specification must be converted to AsyncAPI v2 before it is displayed.

In Kyma the conversion is made by webhook connected to Rafter (it is using https://github.com/asyncapi/converter-go).
