### ISSUE TITLE
Fix failing core-ui unit tests 

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1668]
**Description**

`ConnectApplicationModal` and `CreateApplicationFromTemplateModal` are randomly failing with timeout.

**Expected result**

Tests should be stable.

**Actual result**

Tests are randomly failing.

**Steps to reproduce**

Run tests multiple times on CI.

**Troubleshooting**

**Comment by kwiatekus** [comment]
Fixed  with https://github.com/kyma-project/console/pull/1673/files
