### ISSUE TITLE
Schema validation in label editor is broken (CSP)

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/console#1671]
**Steps to reproduce**

Navigate to any Metadata Definition details and edit label schema.

**Expected result**

![image](https://user-images.githubusercontent.com/10504661/78236305-13acb680-74da-11ea-976a-2862218c0da5.png)

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".
```
Note that `JSON.parse` validation still works.

**Actual result**

Label schema is validated against schema.

**Comment by kwiatekus** [comment]
Fixed with https://github.com/kyma-project/console/pull/1682
