### ISSUE TITLE
Compass UI views are getting unsynchronized after modifying entity

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/console#1672]
**Description**
After modifying the Application's scenarios (adding or removing one) in the "Applications" view, the "Scenarios" view is not synchronized until the page is refreshed manually. For example "Scenarios" view shows that a scenario has no Application's assigned even though it does have one.

**Expected result**
Different views should be synchronized after modifying entities.

**Actual result**
Views are unsynchronized.

**Steps to reproduce**
1. Create an Application with DEFAULT scenario assigned.
2. Change the view to "Scenarios".
3. See that the "DEFAULT" scenario doesn't have just created Application listed as assigned.

**Comment by kwiatekus** [comment]
Hi @tgorgol.

When an operator uses the compass cockpit and jumps from apps to scenarios to runtimes, the views are reloaded fresh every time he switches view. So he will seethe changes.

Of course, those views are not refreshed (live) by web-sockets. However I don't think we have such requirement at the moment.

**Comment by kwiatekus** [comment]
Views are reloaded when user switches the page. Already fixed
