### ISSUE TITLE
Application scenarios - feature flag for default scenario

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/console#1674]
**Description**

Compass UI will require some adjustments to support disabling automatic `DEFAULT` scenario assignment for newly created Applications. This new functionality will be hidden behind a feature flag, and UI should support both the old implementation and new one. Also, the restriction on unassigning last scenario from Application will be lifted in both cases.

**Reasons**

When Management Plance Services are running without default Runtime the `DEFAULT` scenario doesn't make sense and shouldn't be forced.

**AC**

* Add new boolean feature flag read from Helm chart values, e.g. `automaticDefaultScenario`, `true` by default.
* Do not insert `DEFAULT` scenario to chosen scenarios in Application creation modal when the flag value is `false` .
* Allow removing last scenario from Application both in Application details view and Scenarios view (regardless of the flag value).
* Applications view is using different components for scenario management than Runtimes view, that can't handle removing last scenario (because it was forbidden before), so those components would have to be either adjusted or replaced by components used by Runtimes view.

**Comment by kwiatekus** [comment]
the differentiation in the behaviour in the UI could be based on the global override:
https://github.com/kyma-incubator/compass/blob/master/chart/compass/values.yaml#L258
