### ISSUE TITLE
Microfrontend overrides

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/console#1709]
**Reasons**

Allow developers to create declarative configuration for conditional overriding MF in Console.

**Description**

We could create a simple CRD with override data (which MF is to be replaced with other MF & replacement condition) and handle it during building the navigation tree. This override CR could be declared in 3rd party installed modules, so that custom logic does not interfere with current microfrontend CR.

**Comment by pbochynski** [comment]
@Wawrzyn321 @kwiatekus Is it still planned?

**Comment by Wawrzyn321** [comment]
It was more like an idea. I think we could close it now, but keep it in mind in case it comes useful. I'll wait for @kwiatekus opinion on that.
