### ISSUE TITLE
Unify Fundamental dependencies versions across console UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1728]
**Description**

Define single `fundamental styles` and `fundamental-react` version across console UIs.
Avoid redefining fundamental dependencies in subfolders of console repo

**Reasons**

Currently, CSS classes in console come from multiple sources of  Fundamental-styles, fundamental-react etc.. There were cases that those multiple sources imply contradicting rules that clash randomly.
From time to time we observe random css classes conflicts in react components, I.e:
 - blue background in search boxes and checkboxes
 - white fonts on white background in API specs
 - badge textx with the same color as its background

**Attachments**

![Screen Shot 2020-04-22 at 13 17 54](https://user-images.githubusercontent.com/6783567/79975734-bcc44c80-849b-11ea-9a5b-92332ce5b22e.png)
<img width="1108" alt="Screen Shot 2020-03-17 at 20 40 46" src="https://user-images.githubusercontent.com/6783567/79975871-ee3d1800-849b-11ea-9315-a3edc690a66d.png">

**Comment by pbochynski** [comment]
@kwiatekus Is it still valid?

**Comment by kwiatekus** [comment]
Fixed with https://github.com/kyma-project/console/pull/1793
