### ISSUE TITLE
The auth method dropdown in API Rules view sometimes shows the wrong value

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1739]
**Description**

The auth method dropdown sometimes shows the wrong value.

<img width="1404" alt="Screen Shot 2020-04-24 at 09 07 38" src="https://user-images.githubusercontent.com/40663133/80184582-2878f780-860b-11ea-931b-31c995b96f59.png">

**Expected result**

The dropdown should always show the method that is actually created.

**Actual result**

The dropdown sometimes shows a different value than what is actually created later on.

**Steps to reproduce**

* Go to 'Create API Rule' view
* Create 2 Access strategies 
  * First one for example with 'OAuth' method
  * Second one with 'noop' method
* Delete the first Access Strategy (with OAuth)
* The Access Strategy that is left should have the 'noop' method, but 'OAuth' is shown
* If you save the API Rule, it will have the 'noop' method, so it has been saved properly, just the dropdown shows wrong value
 

**Troubleshooting**

**Comment by pbochynski** [comment]
@dariadomagala Is  it still valid? I see merged PR.
