### ISSUE TITLE
Write smoke integration TestCafe tests for Function view

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/console#1747]
**Description**

As in title. Write smoke integration TestCafe UI for `Function` view.

**Comment by michal-hudy** [comment]
Epic: https://github.com/kyma-project/kyma/issues/8256

**Comment by magicmatatjahu** [comment]
PR: https://github.com/kyma-project/console/pull/1714

**Comment by aerfio** [comment]
Closing this one as #1714 is already merged.
