### ISSUE TITLE
Editing description and labels of remote environments

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#175]
UI concept needed

**Comment by jesusreal** [comment]
Waiting for UI API Layer part to be finished.

**Comment by antiheld** [comment]
@jesusreal pleas find the attached visuals below

![Administration - Remote Environment Details - Edit.png](https://images.zenhubusercontent.com/5ba20240bb59de04f7d4b3ba/b75ba267-412e-44cb-9c4b-27f36ac07afc)![Administration - Remote Environment Details.png](https://images.zenhubusercontent.com/5ba20240bb59de04f7d4b3ba/2da1e73b-7589-4332-b285-9bffe715fde0)

**Comment by jesusreal** [comment]
Applied visuals only partially to keep consistency with existing similar views through Console, like IDP Presets, Lambdas and create Remote Environments itself.
