### ISSUE TITLE
Preselect default JWT issuer in access strategy in API exposure UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1756]
**Description**

Selector for predefined IDP presets is confusing. It allows to select an issuer based on IDP Preset, but those presets are extremely rarely used. For most users its just unnecessary clicks.

In addition,  it is not clear to me that using the selector I can append additional jwt issuer entries. 
I would prefer a simple add button which would add new row in the form allowing to define additional issuer.

**Reasons**

Do not force the user to select a JWT issuer from a list.
In most cases users use default (included).

**Attachments**

![Screen Shot 2020-04-29 at 13 14 07](https://user-images.githubusercontent.com/6783567/80591332-d4607f80-8a1d-11ea-974a-2e5b8f89abc3.png)

**Comment by kwiatekus** [comment]
This might be a usecase for a button with dropdown.

**Comment by parostatkiem** [comment]
A button with the "empty" variant used by default and a dropdown (in the button) to choose another variant, like this:
![image](https://user-images.githubusercontent.com/22825433/81293191-3304a980-906d-11ea-88d8-46c7081a2b63.png)

**Comment by kwiatekus** [comment]
Please take this bug into consideration as well:
https://github.com/kyma-project/kyma/issues/8701

**Comment by kwiatekus** [comment]
Fixed with https://github.com/kyma-project/kyma/pull/8773

**Comment by akucharska** [comment]
Done in https://github.com/kyma-project/console/pull/1837
