### ISSUE TITLE
Make UI tests stable

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#179]
**Description**
Investigate the issue with running UI tests - find the reason of failing tests
- [x] make sure tests go through on local and cluster (or at least find the reason)
- [x] check the resources limit, maybe it is enough to run test in another environment then kyma-system
- [x] check if we need to enhance test logic to make it runnable on stability checks, like we did with ui-api-layer - skip them when domain log-in is enabled, like in ui-api-layer

**Expected result**

If UI test fails, it fails because some functionality was broken and UI doesn't work anymore 

**Actual result**

UI tests fail randomly for different unspecified reasons

**Steps to reproduce**

Run tests on any cluster several times

**Comment by pkosiec** [comment]
Review: @pkosiec @akucharska
