### ISSUE TITLE
Kyma Log UI log search field doesn't allow all LogQL queries 

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/console#1824]
**Description**
Console log ui search field validation doesn't allow all LogQL queries to enter, queries like ```{stream=~"stderr|stdout"}```

**Expected result**
Log ui in the console should allow all LogQL queries and able to send loki log server

**Actual result**

In the log ui "advance settings"  currently entering queries like ``` {stream=~"stderr|stdout"}``` not possible due to form validation.

**Steps to reproduce**

- Go to  kyma console log ui

- Click "Advance Settings" and enter query ```{stream=~"stderr|stdout"}```

**Comment by kwiatekus** [comment]
Fixed with https://github.com/kyma-project/console/pull/1825
