### ISSUE TITLE
Simplify exposure of Functions

### ISSUE THREAD

**Issue by hudymi** [kyma-project/console#1827]
**Description**

Currently, if someone would like to expose a Function he/she needs to go to API Rules view. User needs to know that this is a recommended way of exposing. To make it more user friendly, we should create a simple way of exposing, like button `Expose` that will redirect to API Rules view with filled fields. Maybe we should also display all API Rules that expose a Function in the configuration view?

**Reasons**

Improve UX.

**Comment by kwiatekus** [comment]
Lets validate a concept of embedding API Rule creation in the modal (Luigi `.openAsModal`) from the function details. (from configuration tab)

Let's put a list of API rules with a button `Expose` that triggers the modal.
![Screen Shot 2020-06-15 at 14 45 19](https://user-images.githubusercontent.com/6783567/84659079-22224000-af17-11ea-87de-68b59743632d.png)

**Comment by kwiatekus** [comment]
Investigate drawer component. 
Api rule creation might be a good use case.
https://ant.design/components/drawer/
https://github.com/SAP/luigi/issues/1425

**Comment by kazydek** [comment]
+ improve the [**Expose a Function with an APIRule**](https://kyma-project.io/docs/components/serverless/#tutorials-expose-a-function-with-an-api-rule) tutorial (change the steps in the **Console UI** tab to reflect the improved UX)

**Comment by kwiatekus** [comment]
Done 🎉
