### ISSUE TITLE
LogUI bottom panel doesn't hide after leaving Functions view

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/console#1842]
**Description**

It's very hard to reproduce, so I cannot show bug in screenshot. As in title. If you go to Functions view, go to details of some Function, open LogUI from bottom panel, and then just leave from details view, sometimes this LogUI still exist in browser.

**Expected result**

After leaving Functions view, LogUI etc (all related DOM elements of Functions view) should close.

**Actual result**

Sometimes LogUI still exist in browser view.

**Comment by kwiatekus** [comment]
Fixed with https://github.com/kyma-project/console/pull/1884/files
