### ISSUE TITLE
Local development is almost impossible due to high cpu usage

### ISSUE THREAD

**Issue by aerfio** [kyma-project/console#1846]
**Description**

Local development is highly hindered by the fact that cpu usage somewhere at 99%. It makes it almost impossible to edit something and have an instant answer in your browser.

My notebook specs: 
![image](https://user-images.githubusercontent.com/17271979/84643569-50dfec80-aefe-11ea-9806-9332359a486f.png)

Htop: 
![image](https://user-images.githubusercontent.com/17271979/84643732-88e72f80-aefe-11ea-8308-f47bc31e361a.png)

vtop: 
![image](https://user-images.githubusercontent.com/17271979/84643788-9a303c00-aefe-11ea-99aa-c39bf3d06a10.png)

**Reasons**

**Temporary solution**
Removing some views from `lerna.json` makes development bearable, but this "hack" is not documented anywhere, and as far as I remember local development used to be possible, so we should not fall back on it

**Comment by valentinvieriu** [comment]
Please try https://github.com/kyma-project/busola
We've refactored our project and moving towards a more lightweight approach
