### ISSUE TITLE
Failing smoke tests

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/console#1853]
**Description**
See comments.

**Comment by Wawrzyn321** [comment]
08.06
Catalog view is rendered

   1) The specified selector does not match any element in the DOM tree.

**Comment by Wawrzyn321** [comment]
10.06
 Docs view is rendered
  
     1) The specified selector does not match any element in the DOM tree.
  
         > | Selector('iframe')
10.06 post-master-kyma-gke-integration
Deployments view is rendered

   1) AssertionError: expected false to be truthy

      Browser: Firefox 68.0 / Linux 0.0

         53 |  //THEN
         54 |  await findActiveFrame(t);
10.06 post-master-kyma-gke-upgrade
Switching the iframe failed. Retries left: 2
Switching the iframe failed. Retries left: 1
Switching the iframe failed. Retries left: 0
 ✖ Catalog view is rendered

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('iframe')
         |   .filterVisible()

      Browser: Firefox 68.0 / Linux 0.0
10.06 TO JEST ŚWIEŻE https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1270669897982021632
10.06 z PRa
Switching the iframe failed. Retries left: 2
  Switching the iframe failed. Retries left: 1
  Switching the iframe failed. Retries left: 0
   ✖ Catalog view is rendered
  
     1) The specified selector does not match any element in the DOM tree.
  
         > | Selector('iframe')
           |   .filterVisible()
  
        Browser: Firefox 68.0 / Linux 0.0
10.06
Switching the iframe failed. Retries left: 2
Switching the iframe failed. Retries left: 1
Switching the iframe failed. Retries left: 0
 ✖ Docs view is rendered

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('iframe')
         |   .filterVisible()

      Browser: Firefox 68.0 / Linux 0.0
1

**Comment by Wawrzyn321** [comment]
12.06
  Switching the iframe failed. Retries left: 2
  Switching the iframe failed. Retries left: 1
  Switching the iframe failed. Retries left: 0
   ✖ Catalog view is rendered
  
     1) The specified selector does not match any element in the DOM tree.
  
         > | Selector('iframe')
           |   .filterVisible()
  
        Browser: Firefox 68.0 / Linux 0.0
12.06   Switching the iframe failed. Retries left: 2
  Switching the iframe failed. Retries left: 1
  Switching the iframe failed. Retries left: 0
   ✖ Docs view is rendered
  
     1) The specified selector does not match any element in the DOM tree.
  
         > | Selector('iframe')
           |   .filterVisible()
  
        Browser: Firefox 68.0 / Linux 0.0
12.06    ✖ Docs view is rendered
  
     1) AssertionError: expected false to be truthy
  
        Browser: Firefox 68.0 / Linux 0.0
  
           243 |  //WHEN
           244 |  await t.click(docsLink);
           245 |
           246 |  //THEN - user should see "Kyma" category
           247 |  await findActiveFrame(t);
         > 248 |  await t.expect(kymaCategoryHeader.exists).ok();
           249 |});
12.06 Switching the iframe failed. Retries left: 0
   ✖ Catalog view is rendered
  
     1) The specified selector does not match any element in the DOM tree.
  
         > | Selector('iframe')
           |   .filterVisible()
firefox
12.06 Switching the iframe failed. Retries left: 2
  Switching the iframe failed. Retries left: 1
  Switching the iframe failed. Retries left: 0
   ✖ Functions view is rendered
  
     1) Content of the iframe in which the test is currently operating did
        not load.
  
        Browser: Chrome 81.0.4044.138 / Linux 0.0
12.06 Switching the iframe failed. Retries left: 0
   ✖ Catalog view is rendered
  
     1) The specified selector does not match any element in the DOM tree.
  
         > | Selector('iframe')
           |   .filterVisible()
  
        Browser: Firefox 68.0 / Linux 0.0
12.06 Switching the iframe failed. Retries left: 2
Switching the iframe failed. Retries left: 1
Switching the iframe failed. Retries left: 0
 ✖ Catalog view is rendered

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('iframe')
         |   .filterVisible()

      Browser: Firefox 68.0 / Linux 0.0
12.06  Switching the iframe failed. Retries left: 0
   ✖ Applications view is rendered
  
     1) Content of the iframe in which the test is currently operating did
        not load.
  
        Browser: Firefox 68.0 / Linux 0.0

**Comment by Wawrzyn321** [comment]
17.06 Instances view is rendered
  Switching the iframe failed. Retries left: 2
  Switching the iframe failed. Retries left: 1
  Switching the iframe failed. Retries left: 0
   ✖ Docs view is rendered
  
     1) The specified selector does not match any element in the DOM tree.
  
         > | Selector('iframe')
           |   .filterVisible()
  
        Browser: Firefox 68.0 / Linux 0.0
17.06 Switching the iframe failed. Retries left: 2
  Switching the iframe failed. Retries left: 1
  Switching the iframe failed. Retries left: 0
   ✖ Docs view is rendered
  
     1) The specified selector does not match any element in the DOM tree.
  
         > | Selector('iframe')
           |   .filterVisible()
  
        Browser: Firefox 68.0 / Linux 0.0

**Comment by dariadomagala** [comment]
20.07 Functions view is rendered - Content of the iframe in which the test is currently operating did not load.

Switching the iframe failed. Retries left: 2
Switching the iframe failed. Retries left: 1
Switching the iframe failed. Retries left: 0
 ✖ Functions view is rendered

   1) Content of the iframe in which the test is currently operating did
      not load.

**Comment by Wawrzyn321** [comment]
[21.07](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9065/pre-master-kyma-gke-upgrade/1285488391231639552)
Docs view is rendered
  
     1) AssertionError: expected false to be truthy
  
        Browser: Chrome 83.0.4103.97 / Linux 0.0
  
           243 |  //WHEN
           244 |  await t.click(docsLink);
           245 |
           246 |  //THEN - user should see "Kyma" category
           247 |  await findActiveFrame(t);
         > 248 |  await t.expect(kymaCategoryHeader.exists).ok();
           249 |});
           250 |
  
           at <anonymous> (/usr/src/app/tests/tests.js:248:45)

**Comment by dekiel** [comment]
Recent failures from ci-force.
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1285506761519796224
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1285473416094158848
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1285466117321527296
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1285110270384934912

**Comment by adamwalach** [comment]
These issue is pretty common:
https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-integration/1287738243512537089/build-log.txt
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1288038853583572993
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1288038853587767297
```
1) AssertionError: expected false to be truthy
        Browser: Chrome 83.0.4103.97 / Linux 0.0
           243 |  //WHEN
           244 |  await t.click(docsLink);
           245 |
           246 |  //THEN - user should see "Kyma" category
           247 |  await findActiveFrame(t);
         > 248 |  await t.expect(kymaCategoryHeader.exists).ok();
           249 |});
           250 |
           at <anonymous> (/usr/src/app/tests/tests.js:248:45)
```
It occurs on pre and post-master jobs:
![Screenshot 2020-07-28 at 13 26 22](https://user-images.githubusercontent.com/8530211/88659868-0c876500-d0d6-11ea-8437-326bffb91873.png)

It makes PRs more time consuming. Can we disable part of this test or somehow make it optional until a fix is provided?
