### ISSUE TITLE
Left navigation is not displayed properly in documentation

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/console#186]
**Description**

Left navigation in Kyma documentation is not displayed properly. Here is how it looks on image `0.1.178`:

![image](https://user-images.githubusercontent.com/26445970/46126930-3a2bca80-c22f-11e8-8b64-e7ee0a5c2e51.png)

**Expected result**

Left navigation should looks like here https://kyma-project.io/docs#

**Comment by pkosiec** [comment]
Review: @michal-hudy @magicmatatjahu
