### ISSUE TITLE
Removal of log filter item using popup menu

### ISSUE THREAD

**Issue by k15r** [kyma-project/console#1905]
**Description**

In the Log viewer you can add items to the filter using the popup list:
<img width="681" alt="Screen Shot 2020-07-29 at 10 48 38" src="https://user-images.githubusercontent.com/292906/88779511-28e4d980-d18a-11ea-821b-f6e46fde19f5.png">

But if you want to remove an item from the filter it cannot be done in the same way.
This is inconvenient if you enabled an item accidentally. To remove items you have to click on the "x" that appears next to every filter item.
<img width="1077" alt="Screen Shot 2020-07-29 at 10 51 02" src="https://user-images.githubusercontent.com/292906/88779525-2e422400-d18a-11ea-9190-68eef745f0fe.png">

**Proposal**
Allow removal of filter items using a click on the popup menu.

**Comment by kwiatekus** [comment]
Hi @k15r 
Unfortunately we will not invest in this view anymore, as we want to expose grafana UI instead:
https://github.com/kyma-project/kyma/issues/9196
