### ISSUE TITLE
Error is shown after the function is created, and triggers cannot be created

### ISSUE THREAD

**Issue by Disper** [kyma-project/console#1908]
**Description**

* Error is shown after the function is created
* Triggers cannot be created at all

**Expected result**

* Function is created and error is not shown.
* Triggers are created

**Actual result**

* Function is created and error is shown.
![image](https://user-images.githubusercontent.com/1783008/89017594-d555c580-d31a-11ea-88e0-1326147a78c1.png)

* Trigger creation fails with error message
<img width="483" alt="Screen Shot 2020-07-31 at 10 39 18" src="https://user-images.githubusercontent.com/292906/89018284-e6eb9d00-d31b-11ea-9c0f-d14faf0cc2bc.png">

**Steps to reproduce**

1. Just create new Function on 1.14-RC3 and try to have it triggered by any event

**Attachment**

**Comment by valentinvieriu** [comment]
You can also not create an api endpoint to the created function
![image](https://user-images.githubusercontent.com/478866/89018583-61b4b800-d31c-11ea-8165-2a791450844d.png)

**Comment by valentinvieriu** [comment]
I can confirm that with 1.14.-rc4 this is not happening anymore. Also creation of API endpoints seems to be ok now.

**Comment by kwiatekus** [comment]
Fixed. Doeasnt appear in 1.14
