### ISSUE TITLE
Service Brokers not visible on Console after upgrade 1.13 to 1.14

### ISSUE THREAD

**Issue by ksputo** [kyma-project/console#1910]
**Description**
During testing process of RC4, I encountered a problem with displaying Service Brokers in Namespace. Service Brokers were created on Kyma 1.13.0, ten an upgrade was performed. All resources from kubernetes cluster's perspective are there (Service Brokers, Instances, Binding etc.), but Service Brokers themselves are not visible on Console UI.

**Expected result**
Service Brokers are visible on Console UI after upgrade.

**Actual result**

<img width="1434" alt="Screenshot 2020-08-03 at 14 58 00" src="https://user-images.githubusercontent.com/26189888/89185423-7dc58d00-d59a-11ea-8c43-6aae32307bb8.png">
<img width="1434" alt="Screenshot 2020-08-03 at 14 58 14" src="https://user-images.githubusercontent.com/26189888/89185537-ae0d2b80-d59a-11ea-8c97-af5171cbe055.png">

**Steps to reproduce**
1. Create Service Broker in namespace on Kyma 1.13.0
2. Upgrade Kyma from 1.13.0 to 1.14.0-rc4
3. Go to namespace and see **Service Management > Brokers**
4. Compare results with actual cluster state:
`kubectl get servicebrokers -A`

**Troubleshooting**
- Deleting web browser cache did not work.
- Similiar test was performed in scenario with upgrading from `1.14.0-rc4` to `1.14.0-rc4`, in this case Service Broker remain visible

**Comment by parostatkiem** [comment]
We discovered that the service broker `hb-azure-defaul-31602ef8-5450-4b9a-b237-e2c8edba9970-azure-serv` has no labels at all and this is unacceptable by CBS.
![image](https://user-images.githubusercontent.com/22825433/89271189-a56d3180-d63c-11ea-8a4c-4cb3f3857733.png)
Other two brokers seem to have some labels (which is good).

**Comment by parostatkiem** [comment]
We added a label manually (for test purpose) and it seems to be working fine 👌 
![image](https://user-images.githubusercontent.com/22825433/89271505-190f3e80-d63d-11ea-8fcb-dd0ae3d77306.png)

**Comment by kwiatekus** [comment]
@ksputo should it have a follow-up issue on your side?

**Comment by kwiatekus** [comment]
@parostatkiem according to @PK85 labels are not required for the broker.
Meaning, we shouldn't interpret no labels as error state but rather display them.
Lets change that in the console-backend.

**Comment by PK85** [comment]
@ksputo In the meantime, please check why Kyam upgrade (helm2-helm3) removes labels on that ServiceBroker CR.

**Comment by ksputo** [comment]
`Azure Service Broker` never had any labels on `ServiceBroker` resource, see history [here](https://github.com/kyma-project/addons/blob/master/addons/azure-service-broker-0.0.1/chart/azure-service-broker/templates/service-broker.yaml). It should be changed in CBS then, because all resource behave properly (ServiceClasses, ServiceBroker, ServiceInstances) from k8s perspective.
