### ISSUE TITLE
Weird blue shadow on Service Catalog plan list

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1917]
**Description**
![image](https://user-images.githubusercontent.com/22825433/89417745-666bd880-d72f-11ea-812a-28606af58ed1.png)
![image](https://user-images.githubusercontent.com/22825433/89417765-6ec41380-d72f-11ea-9cb5-24dc1026144e.png)

There are some blue pixels under the doc-type counter.

There are no blue pixels
**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
Fixed with https://github.com/kyma-project/console/pull/1922
