### ISSUE TITLE
Can't download kubeconfig in Chrome

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/console#1919]
**Description**
Kubeconfig download cannot be started in Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Expected result**
Kubeconfig is downloaded.

**Actual result**
Nothing happens and such message is logged:
> Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.

**Comment by kwiatekus** [comment]
@pbochynski This issue was already fixed in 1.14. In 1.14 we moved this button out of iframe, which fixes the bug (resulting from updated chrome security policies)

https://github.com/kyma-project/kyma/issues/8683
