### ISSUE TITLE
Super wide context menu for namespace cards

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1938]
**Description**

There is a css bug related to the width of context action menu on namespaces list view ( see screenshot below.
User cannot read it and probably wont use ("DELETE" action) it as he or she may only guess what this menu item would do.
User may still delete the namespace from the UI from the namespace details view

**Expected result**

The menu width should be normal.

**Actual result**

It expands way outside the content frame
![Screenshot 2020-08-19 at 13 14 52](https://user-images.githubusercontent.com/6783567/90726842-ab147980-e2c2-11ea-85db-087b8878293e.png)

**Steps to reproduce**

Log in to console UI.
Click a three dot menu on one of the namespace cards

**Comment by VishnAndr** [comment]
This issue is not only with namespaces dropdown. I've seen it in other places in v1.14.0.
After refreshing the window or waiting some time it's back to normal.

**Comment by kwiatekus** [comment]
Fixed
