### ISSUE TITLE
Double indicators in instances tabs

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#1939]
**Description**

There are double numbers indicators in the instances view
<img width="407" alt="Screen Shot 2020-08-20 at 09 25 02" src="https://user-images.githubusercontent.com/40663133/90731884-94722080-e2ca-11ea-98d3-55814eac92ca.png">

**Expected result**

Should be only one indicator (colorful one)

**Actual result**

Double indicators

**Steps to reproduce**

**Troubleshooting**

**Comment by Wawrzyn321** [comment]
It looks like this behaviour is actually fine - in case of e.g. 5 bindings (2 with errors, 1 with warning), there should be 5 grey indicators, 1 orange and 2 red.

Logic for this is contained withing `StatusIndicator.component.js`
