### ISSUE TITLE
Logs frame disappearing in functions

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/console#1949]
**Description**
After editing and saving API rules within a function, the Logs frame disappears. To be able to look into logs, we need to refresh the window or reopen the function from the list of functions.

Kyma v 1.14.0

**Expected result**
Logs frame should stay in place.

**Actual result**
Logs frame disappears as soon as Save pressed in API Rules

**Steps to reproduce**
Go to the function, switch to the Configuration tab, open an existing API rule for editing or start creating a new API rule, perform any change and press Save.

Before pressing Save:

![2020-08-27_14h06_04](https://user-images.githubusercontent.com/4543139/91383225-f7395e00-e86e-11ea-8ba4-db142ef85ad0.png)

After Save pressed and the popup window with API rule was closed:

![2020-08-27_14h06_28](https://user-images.githubusercontent.com/4543139/91383262-0d471e80-e86f-11ea-82bc-b533ad754dd7.png)

**Troubleshooting**

**Comment by VishnAndr** [comment]
Sometimes it is opposite. The Logs frame stays visible at the bottom of the page even if I left the function screen and went to the functions list already.

**Comment by kwiatekus** [comment]
The newest Luigi version includes a fix for the remaining problem of log container remaining after leaving the function ui

**Comment by valentinvieriu** [comment]
We've moved and refactored our project to [busola](https://github.com/kyma-project/busola)
Please check the new logs implementation there.  
Starting with Kyma 2.0 we will use the [busola](https://github.com/kyma-project/busola) codebase
