### ISSUE TITLE
Improve creation and deletion of the service bindings and the usages

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#195]
**Description**

- Create Credentials button should be called Request Credentials
  - on click, if no schema for binding is provided, the service binding must be created 
  - on click, if schema for binding is provided we display modal with schema so user can fill in and create binding
![create-credentials-modal](https://user-images.githubusercontent.com/6995927/46360115-10c5d100-c66b-11e8-9dab-9674dd7aa0cf.png)
  - always after creation screen should refresh and new item on list appears
  - help icon in modal should display info box with information what does it mean to request credentials, what is actually happening here
![help](https://user-images.githubusercontent.com/6995927/46360243-52ef1280-c66b-11e8-8c81-95d3b423d4b5.png)
  - confirm info should have header `Credentials requested`
![credentials-create-confirmation](https://user-images.githubusercontent.com/6995927/46360048-e7a54080-c66a-11e8-9475-d6ef0bd8db7c.png)
- Bind Application button on click shows modal that does sbu and sb
  **1st section of modal called Bind Application, and then we have ruler**
  - help icon in modal should display info box with information what does it mean to create credentials, what is actually happening here
![help](https://user-images.githubusercontent.com/6995927/46360243-52ef1280-c66b-11e8-8c81-95d3b423d4b5.png)
  - the first textbox, realtime displays list of all resources of all available types that match the typed in text. 
  - below the textbox you have link called `Set environment prefix` and on click you get another text box where you can set the prefix. Validate length if there are some limits predefined
![sbu-prefix](https://user-images.githubusercontent.com/6995927/46360812-7f575e80-c66c-11e8-96ad-6555dcf29c06.png)
  **2nd section of modal called Create Credentials**
  - display binding parameters if such provided
  - display scroll bar in case scrolling is needed
  - instead of `Select an existing Binding` have a link `select existing credentials`
  - once above link is clicked display dropdown where user can select existing ServiceBindings. And hide schema parameters (if provided) for new binding
![sbu-existing-binding](https://user-images.githubusercontent.com/6995927/46372928-dc630c80-c68c-11e8-859f-e202a3947ea7.png)
  - we need some help text that explains credentials section like the bind apps section
![help](https://user-images.githubusercontent.com/6995927/46360243-52ef1280-c66b-11e8-8c81-95d3b423d4b5.png)
- in case mentioned above links for env prefix and existing bindings, it should be possible to cancel when someone selects them
- any UI text must be consulted with @kazydek 
- Delete Service Binding 
  - Should warn what SBUs will also be deleted/affected. Depends on completion of #1069
![sbu-remove](https://user-images.githubusercontent.com/6995927/46373251-c99d0780-c68d-11e8-97ed-3db322c57fe1.png)
- Delete Service Binding Usage should warn like previously `Warning: Removing Service Binding Usage will prevent your application from accessing the instance after its restart.`

**Reasons**

As described in linked epic.  Also current UX issue with binding is that it is overcomplicated, for example:
- you have option to provide names for sb and sbu even though they have no meaning and can be generated
- to select application you want to bind to, but need to first know that kind of app is it, function/deployment?
- reusing binding was promoted to much
- setting proxy for sbu name was not possible
- status of sbu and sb was not visible
- schema for binding not supported

**Comment by mjasinski5** [comment]
Review: @magicmatatjahu @aerfio
