### ISSUE TITLE
Labels in Functions list search

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/console#1953]
**Description**

Currently (v 1.15), we can happily assign labels to a function in Console. The labels can be used to search for the function using kubectl. 
`k get functions -A -l dev=true`

But they're not considered while performing the search in the functions list.

**Reasons**

Labels are great to organize functions. But would be really nice to have a way to be able to search them in Console.

**Comment by kwiatekus** [comment]
@valentinvieriu PLease have a look. Is it planned to have search based on labels for the generic list in busola ?

**Comment by Sawthis** [comment]
@kwiatekus yes, it is planned to add it in [Busola](https://github.com/kyma-project/busola) (new Kyma Dashboard) soon.

**Comment by Sawthis** [comment]
Done in https://github.com/kyma-project/busola/pull/291 .
