### ISSUE TITLE
Add service to application via Console

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/console#1955]
**Description**

At the moment, when we're registering an external application in Kyma, the only way to add more services to the application is via manual request as described here: https://kyma-project.io/docs/components/application-connector/#tutorials-register-a-service-register-a-serviceor here https://github.com/brendandobbs/c4c-v1-api

Would be nice to have an option to do in Console.

**Reasons**
For example, SAP C4C only adds 1 out of ~13 standard odata services when registering with Kyma automatically (by triggering registration from C4C side using an application token). No custom odata services are added either. Hence we need to follow the way described in the mentioned documentation to add them manually.

**Attachments**

**Comment by pbochynski** [comment]
Did you try to do that with compass UI? Try to install it: https://github.com/kyma-incubator/compass/blob/master/docs/compass/04-01-installation.md

**Comment by VishnAndr** [comment]
Seems like Compass should be the way to go. Thank you @pbochynski  for the discussion over the call!
