### ISSUE TITLE
console-web tests fail to click "Applications/Systems" link

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1956]
**Description**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1301144964511567873

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Wawrzyn321** [comment]
'Applications' are written in Angular. Maybe [angularStable](https://github.com/cypress-io/cypress/issues/7306#issuecomment-641965688)?

**Comment by dariadomagala** [comment]
This test is unstable. We should disable it until we get rid of angular components.
