### ISSUE TITLE
Don't disable the Expose Function button when k8s Service exists

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/console#1961]
**Description**

As in title.

In Function view, we disable the `Expose Function` button when Function is building and deploying, even if user change the Function's code/deps. We should change the behaviour -> disable only when k8s Service doesn't exist (creation step), not when Function's status is different than `Ready`.

**Comment by VishnAndr** [comment]
The issue is still there in 1.19

**Comment by VishnAndr** [comment]
Not stale. We're waiting still. The issue is still there in 1.20

**Comment by kwiatekus** [comment]
console will be discontinued in favor of busoal. Closing...
