### ISSUE TITLE
"Applications/Systems" not found in smoke tests

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#1964]
**Description**
Logs from the _nightly_ cluster:
![image](https://user-images.githubusercontent.com/22825433/92389167-e1eaec00-f118-11ea-8039-6f918b720b7a.png)

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Wawrzyn321** [comment]
The problem also occurs while querying "Deployments".

**Comment by dariadomagala** [comment]
There is a different issue with applications test
```CypressError: Timed out retrying: `cy.click()` failed because this element is detached from the DOM.```
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1305484364309598208

**Comment by dariadomagala** [comment]
Fixed in https://github.com/kyma-project/kyma/pull/9528
