### ISSUE TITLE
Left navigation panel not wide enough to fit Navigation Node Display Names

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1975]
**Description**

Adjust Navigation Panel to fit navigation node names

**Expected result**
Left Navigation should be wide enough to fit display names w/o shortening with `...` 

**Actual result**

`Service Management` navigation node is shortened with three dots ... 

**Steps to reproduce**

1. Log in to console UI.

**Attachments**

![Screen Shot 2020-09-11 at 14 58 16](https://user-images.githubusercontent.com/6783567/92928481-6c945980-f43f-11ea-8c23-8b3bddd9d6d6.png)

**Comment by Wawrzyn321** [comment]
I've noticed a CSS mismatch between the cluster where the issue occurs:
![image](https://user-images.githubusercontent.com/10504661/92931138-4cff3000-f443-11ea-8262-666a134e0c94.png)
and another cluster, where it works just fine:
![image](https://user-images.githubusercontent.com/10504661/92931252-7750ed80-f443-11ea-85ea-bace3d2b8bfa.png)
The classes overriding the `padding-right` are somehow absent from the first cluster's stylesheets. Maybe first cluster has an older Luigi version?
