### ISSUE TITLE
consolidate lists in console

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#200]
Originated from the need for a consistent way to show resource status, this issue covers a broader refactoring.

Things we want to change:
* Add "Actions" column to all resources that have item-scoped views (e.g. item details, edit functionality, ...). For lists where we have "name link", add "Details" to action dropdown
* "empty message" for labels: looks like it is a mix of "", "none", "-". Check and change to "" everywhere.

Identified views that are affected:
* /home/settings/remoteEnvs: move status, add details entry
* /home/settings/serviceBrokers: move status
* /home/environments/production/deployments: move status
* /home/environments/production/replicaSets: move status
* /home/environments/production/pods: move status
* /home/environments/production/services: move status, add details entry
* /home/environments/production/secrets: add details entry

**Comment by kwiatekus** [comment]
'Details' option comes first in the list of available actions in the dropdown

 - Details
 - Edit
 - Delete
