### ISSUE TITLE
Cannot provision ServiceClass in Catalog UI, when ClusterServiceClass with the same name exist

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/console#201]
In the routing we pass Service Class name. When it is the same for cluster-wide and local resources, it displays clusterServiceClass details:

![image.png](https://images.zenhubusercontent.com/5b98d5680e23a90b8f9c76c3/65018024-873b-40de-9192-c525ed0bc854)

We need to add `{cluster-}service-class-` prefix or `/{cluster-}service-class/` in URL.

Also, we should consider displaying type of Service Classes.

**Comment by pkosiec** [comment]
Unfortunately it's still valid

**Comment by derberg** [comment]
Doesn't seem like a valid issue, no one reported it and it is not possible to reproduce as a proper description is not provided
