### ISSUE TITLE
Generic Kubernetes Resources List View

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#2016]
**Description**

As Sebastian and Mathew, I would like to have a consistent flow and user experience when I navigate any K8s list views of any type of Kubernetes resources in Kyma. This will allow me to feel familiar browsing any resource type, and I would expect that my experience is enhanced in a contextual way ( I get more informations depending on the resource type ) 

**AC**
 - [x] I would be able to view all the list views of all Kyma/k8s resources ( the ones are existing )
 - [x] I would like to be able to deep link / bookmark my resource list page
 - [x] I would like to see advanced features in the list, depending on the resource type and field. See image for example
 
**Non Functional Requirements**
- [x] - We use the same Generic List to display all our k8s resource List View ( including our custom ones functions ) - ui differences are acceptable
- [x] This general component has the possibility for extensibility. By default has a minimal view, and parts of the list view can be enhanced with additional components
- [x] We will use k8s api for reading data. We are not going to use any of the exiting GraphQL endpoints
- [ ] Consider lazy load Expensive components, so that we offer a good first time experience ( reduce overall bundle size )
- [ ] ~Use as much as possible the available components from [fundamental-react](https://sap.github.io/fundamental-react/?path=/docs/introduction-overview--page) and when not possible use [fundamental-styles](https://sap.github.io/fundamental-styles/)~
- [ ] ~Follow the guidelines from [fiori-design-web](https://experience.sap.com/fiori-design-web/design-principles/) for any new component that needs to be develop and is not present in the above mentioned resources~
- [ ] The application might look different. We should focus on reusability of the components, the app should not look the same.

**Kyma Goals we are achieving with this **
- Slimmer / faster Kyma
- Unification of used components and technology stack across all micro-frontends
- Kyma console can be a stand alone Open Source project and can work with any K8s api server

** Reference images **
Please use those more as examples, on how to structure the default view. 
![image](https://user-images.githubusercontent.com/478866/105312742-07efc500-5bbe-11eb-88bd-6489848ea3c1.png)
![image](https://user-images.githubusercontent.com/478866/105312895-10480000-5bbe-11eb-8ed5-0c3991ab97f6.png)

**Comment by kwiatekus** [comment]
Please fix also the css bug
![2e8fb480-cf29-11ea-802e-05cabbbff293](https://user-images.githubusercontent.com/6783567/96868157-f4717880-146d-11eb-9c83-60d0f40cfdad.png)

**Comment by Sawthis** [comment]
It's part of #2080 Epic.
