### ISSUE TITLE
ReplicaSets overview with drawer component

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#2018]
**Description**

Recently we have come up with a drawer component enabling the user to preview objects as yaml content.
We should apply this concept on out replica set list view.

**AC**
 - rewrite replica sets list view  into react
 - add an action to the list entry that allows to inspect, copy, download and edit yaml content of the selected replica set
 - as for this task, preserve searching and paging on the client side 

**Reasons**

Unification of used components and technology stack across all micro-frontends

**Comment by valentinvieriu** [comment]
we will use the generic views for this
