### ISSUE TITLE
Make sure all views in console use console-backend-service

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#202]
**Description**

- Implement missing queries
- Change UI to call the graphql layer

**Reasons**

- We agreed https://github.com/kyma-project/community/blob/master/sig-and-wg/sig-core/decisions/dr-007-GraphQL_as_API_facade_for_UI.md that all Console views should use `ui-api-layer` as a backed, for reasons described in the decision.
- Don't use kubernetes-dashboard as dependency to the UI as this is going to be a blocker for https://github.com/kyma-project/kyma/issues/926 as kubernetes is an addon that should be optional

**Comment by kwiatekus** [comment]
This epic is very broad and starts to become unmanageable.
The leftovers were detached from it and will be fixed.
