### ISSUE TITLE
ConfigMap overview with drawer component

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#2021]
**Description**

Recently we have come up with a drawer component enabling the user to preview objects as yaml content.
We should apply this concept on out config map list view.

**AC**
 - rewrite config map list view  into react
 - add an action to the list entry that allows to inspect, copy, download and edit yaml content of the selected config map
 - as for this task, preserve searching and paging on the client side 

**Reasons**

Unification of used components and technology stack across all micro-frontends

**Comment by valentinvieriu** [comment]
We've moved and refactored our project to [busola](https://github.com/kyma-project/busola)
Please check the new config map implementation there.  
Starting with Kyma 2.0 we will use the [busola](https://github.com/kyma-project/busola) codebase
