### ISSUE TITLE
Make sure lambda view uses graphql layer

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#203]
**Description**

- Implement missing queries
- Change UI to call the graphql layer

**Reasons**

We agreed https://github.com/kyma-project/community/blob/master/sig-and-wg/sig-core/decisions/dr-007-GraphQL_as_API_facade_for_UI.md that all Console views should use `ui-api-layer` as a backed, for reasons described in the decision.

**Comment by kwiatekus** [comment]
The new ui supporting knative functions will be based on graphql.
