### ISSUE TITLE
Inline editor rendering issue - blank until browser window resized 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#2044]
**Description**

Inline code editor appears blank when switching between code and dependencies tabs

Chrome Version: Version 86.0.4240.111 (Official Build) (x86_64)
Kyma version: master-cf2ef204

**Expected result**

Inline editor should show the content 

**Actual result**

Inline code editor remains blank until user resized browser window
See attached screen recording

**Steps to reproduce**

1. Go to function view
2. Open a function of type `Inline`
3. Switch between code and dependencies tabs
 
**Attachments**
[Screen Recording](https://github.com/kyma-project/console/files/5474711/Screen.Recording.2020-11-02.at.12.45.18.mov.zip)

**Comment by Wawrzyn321** [comment]
Already fixed in [2045](https://github.com/kyma-project/console/pull/2045)
