### ISSUE TITLE
Generic Kubernetes Resource Detail View

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/console#2094]
**Description**

As Sebastian and Mathew, I would like to have a consistent and user experience when I navigate the detail views of all Kubernetes resources in Kyma. This will allow me to feel familiar browsing any resource type, and I would expect that my experience is enhanced in a contextual way ( I get more informations depending on the resource type ) 

**AC**
 - [x] - I would be able to view all the detail pages of all Kyma/k8s resources
 - [x] - I would like to be able to deep link / bookmark my resource Detail page
 - [x] - I would like to see the listing of the resources linked ( contained ) in my K8s Resouce, and this listing should update on a regular basis. Example: In the case of Deployment, display all the pods that are in this deployment set and update them on regular basis
 
**Non Functional Requirements**
- [x] - We use the same Component to display all our k8s resource Detail View ( including our custom ones functions )
- [x] - This general component has the possibility for extensibility. By default has a minimal view, and parts of the detail page can be enhanced with additional components
- [x] - We will use k8s api for reading data. We are not going to use any of the exiting GraphQL endpoints
- [ ] - Consider lazy load Expensive components, so that we offer a good first time experience ( reduce overall bundle size )
- [ ] ~Use as much as possible the available components from [fundamental-react](https://sap.github.io/fundamental-react/?path=/docs/introduction-overview--page) and when not possible use [fundamental-styles](https://sap.github.io/fundamental-styles/)~
- [ ] ~Follow the guidelines from [fiori-design-web](https://experience.sap.com/fiori-design-web/design-principles/) for any new component that needs to be develop and is not present in the above mentioned resources~
- [x] The application might look different. We should focus on reusability of the components, the app should not look the same.

**Kyma Goals we are achieving with this **
- Slimmer / faster Kyma
- Unification of used components and technology stack across all micro-frontends
- Kyma console can be a stand alone Open Source project and can work with any K8s api server

** Reference images **
Please use those more as examples, on how to structure the default view. 
![image](https://user-images.githubusercontent.com/478866/105309842-5781c100-5bbd-11eb-98a8-505ca0705b41.png)

**Comment by Sawthis** [comment]
It's part of #2080 Epic.
