### ISSUE TITLE
Have an OIDC login flow with PKCE and use this token for K8s access

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/console#2097]
**Description**

As Sebastian and Mathew, I would like to be able to login with a SSO provider ( OIDC ) to the Console and also to my Kubernetes cluster, so it is more user friendly for me to not have additional logins or tokens
**AC**
 - [ ]  I would be able to login in console using an OIDC certified provider
 - [ ]  I want my token to be as secured as possible, so please use security best practices when comes to SPA
 - [ ]  I would like to use the same OIDC to login in my Kubernetes Cluster
 
**Non Functional Requirements**
- [ ]  The OIDC configuration needs to be configurable at build time and run time
- [ ] We should use the Luigi plugins to handle the flow and choose the best security option available
- [ ] Remove any backend related token impersonation
- [ ] We do not care about the adapting the Graphql layer
- [ ] We would like to get the OIDC configuration via URL parameters and stored in localstorage

**Kyma Goals we are achieving with this**
- Slimmer / faster Kyma
- Kyma console can be a stand alone Open Source project and can work with any K8s api server

**Comment by Sawthis** [comment]
It's part of #2080 Epic.
