### ISSUE TITLE
New source of Kyma version

### ISSUE THREAD

**Issue by strekm** [kyma-project/console#2103]
**Description**

Moving forward with a new approach to Kyma installation (https://github.com/kyma-project/kyma/issues/10297) Kyma version will be saved in a new location. After installing Kyma via `kyma alpha deploy` Kyma version can be retrieved from CM stored in `kyma-system` NS. 

Note: in Kyma 1.20 both ways of retrieving Kyma version should be supported.

**Reasons**

Providing source of Kyma version for UI

**Attachments**

**Comment by valentinvieriu** [comment]
This will work with Kyma 2.0
