### ISSUE TITLE
Broken animation for for the radial charts

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/console#2105]
**Description**

Whenever I apply a new deployment and update pods, the radial charts go crazy and they repeat this behavior a couple times. I guess this can be somewhat distracting to developers. Therefore I wanted to ask if this is the intended behavior in the first place.

I run on SCP trial but I've seen this on other environments too.

**Expected result**

A smooth transition/animation.

**Actual result**

![image](https://user-images.githubusercontent.com/478866/106022390-12322780-60c6-11eb-8742-f0263bfa8755.png)

**Comment by IObert** [comment]
Seems like the attachment is a png, here's the gif to show the full behavior:

![a7f54b80-094b-11eb-8e23-b708fa1006ef](https://user-images.githubusercontent.com/1873245/106116556-52d78280-6152-11eb-897f-7a376917d98e.gif)

**Comment by valentinvieriu** [comment]
We've moved and refactored our project to [busola](https://github.com/kyma-project/busola)
Please check the new overview implementation there.  
Starting with Kyma 2.0 we will use the [busola](https://github.com/kyma-project/busola) codebase
