### ISSUE TITLE
Event specs are not rendered properly

### ISSUE THREAD

**Issue by desislavaa** [kyma-project/console#2107]
**Description**

Event specs are not rendered properly in the latest console from the main branch.

**Expected result**

![image](https://user-images.githubusercontent.com/9128192/106136835-81655580-6172-11eb-9c30-7be11904f658.png)

**Actual result**

![image](https://user-images.githubusercontent.com/9128192/106136332-d05ebb00-6171-11eb-88d8-0deb293ab51a.png)

**Steps to reproduce**

1. [Register an application in Compass](https://github.com/kyma-incubator/compass/blob/master/docs/compass/08-01-basic-flow-tutorial.md#register-your-application-in-the-compass-ui), but instead of creating an API definition create an Event definition with [this JSON](https://gist.githubusercontent.com/desislavaa/f88488f7eb4ddf78ef5def89daf5a92a/raw/67ca5eab425d902a3d79d9c70d19901d53f76c03/event-def.json).
2. [Execute step 1](https://github.com/kyma-incubator/compass/blob/master/docs/compass/08-01-basic-flow-tutorial.md#use-your-application-in-the-kyma-console-ui)
3. Then navigate to the catalog and open the service view.

**Troubleshooting**

It seems like this behaviour is ovservable when the returned API spec contains fields that are null. The error is observable after the update of `@kyma-project/dc-async-api-render-engine`

PS: I've greated a bug on `@kyma-project/dc-async-api-render-engine` side - https://github.com/kyma-incubator/documentation-component/issues/72

**Comment by valentinvieriu** [comment]
We've moved and refactored our project to [busola](https://github.com/kyma-project/busola)
Please check the new events implementation there.  
Starting with Kyma 2.0 we will use the [busola](https://github.com/kyma-project/busola) codebase

This feature will be different in kyma 2.0 version
