### ISSUE TITLE
Kyma Console can run outside of Kyma Cluster

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/console#2109]
**Description**

As Sebastian and Mathew, I would like to be able to make my cluster lighter, by using an external Kyma Console, that can talk to my cluster based on the provided authorization token obtained from OIDC.

**AC**
 - [ ] External Kyma Console can run outside of the Kyma Cluster 
 - [ ] I would like to be able to bookmark my Kyma Console access link
 - [ ] I should be able to download and deploy Kyma Console on my own, and even use Kyma Cluster to host it
 
**Non Functional Requirements**
- [ ] We need to capture in the url the information needed to start Kyma Console externally for the User.  This information will be stored in the browser for better User Experience
- [ ] We will have an configuration view ( in preferences view section )  interface where we can modify those init parameters and be able to recreate the Kyma Console Init Url
- [ ] Kyma Console can be used in the same time by multiple users talking with different K8s API in secured way
- [ ] A user does not need use 2 different configurations in the same browser. They can open an incognito window for that or another browser.

**Kyma Goals we are achieving with this**
- Slimmer / faster Kyma
- Kyma console can be a stand alone Open Source project and can work with any K8s api server

**Comment by Sawthis** [comment]
It's part of #2080 Epic.

**Comment by valentinvieriu** [comment]
We've moved and refactored our project to [busola](https://github.com/kyma-project/busola)
Please check the new implementation there.  
Starting with Kyma 2.0 we will use the [busola](https://github.com/kyma-project/busola) codebase
