### ISSUE TITLE
All Console Dockers eat too much CPU and Momory on Nodes with more than 16 cores

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/console#2126]
If you create a cluster that the node has more than 32 cores, you can see that the pods eat more resources than allowed
This seem to apply for all the NGINX docker images that have `worker_processes=auto`

Example
![image](https://user-images.githubusercontent.com/478866/107916591-d375eb80-6f66-11eb-94d9-13f1dbf60c40.png)

**Comment by Sawthis** [comment]
Issue is fixed for 1.19 and 1.20 milestone.
