### ISSUE TITLE
Additional information about Resource Quota

### ISSUE THREAD

**Issue by mjasinski5** [kyma-project/console#239]
**Description**

Currently, if Resource Quota has been exceeded there's a panel on the upper side of the screen telling basic information (something like "Resource Quota has been exceeded"). Lately, Gophers team extended the query to retrieve additional information. Now we can display error in details which can help user understands what has happend. Details on the screen.

![image](https://user-images.githubusercontent.com/7690363/48840082-f3210800-ed8d-11e8-9fec-bccaa8bf785a.png)

**If you need any assistance on that or more information please contact @polskikiel**

**Reasons**

User-first approach ;) its very helpful for "ui-debugging", we immediately know what happened - and also we should take advantage of the features implemented by other teams.

**Attachments**

Query when all is ok:
<img width="792" alt="screen shot 2018-10-18 at 09 58 03" src="https://user-images.githubusercontent.com/5781126/47140017-8792d900-d2bd-11e8-9145-c26f40adede3.png">

Query with exceeded quota and additional information:
<img width="978" alt="screen shot 2018-10-18 at 09 58 14" src="https://user-images.githubusercontent.com/5781126/47140018-882b6f80-d2bd-11e8-8e70-5f4254110802.png">

**Comment by kwiatekus** [comment]
After luigification we should use the same component as for the 404 use case.
Until luigification, lets change the styling of the component (make it opaque)
