### ISSUE TITLE
Consistent loading indicators for lists

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#242]
see https://sap.github.io/fundamental/components/loading-spinner.html

Generic list currently has an empty-list-placeholder just showing a text "Loading ...", should be changed to standard fundamental loading spinner.

When this is done, please inform automatix team to update to the latest version of generic list.
(or just issue a PR for them to accept)

**Comment by maxmarkus** [comment]
Can be tested by adding setTimeout to `array-data-provider.js:25`

```
    return Observable.create(observer => {
      setTimeout(() => {
        observer.next(new DataProviderResult(pagedData, filteredData.length));
        observer.complete();
      }, 2000)
    });
```
