### ISSUE TITLE
Async changes of resources requires browser refresh to see status update

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#247]
UX Improvment. Not critical
Reproduced on CCV2-provisioned kyma

Step to reproduce:

- Create a new Application from UI
- Stay on same page

After few seconds or minutes page still show the initial status (black dot)

Expected behavior: after a while dot goes to red or green

**Comment by hardl** [comment]
Please contact Wookiee team.

**Comment by dariadomagala** [comment]
Subscriptions are ready on the ui-api-layer side (Acceptance tests are missing, but Wookiee team is on it).

TODO: Use subscriptions in the console.

**Comment by hardl** [comment]
connected PR is merged, can the ticket be closed?

**Comment by dariadomagala** [comment]
@hardl As written in the comment above, backend part is ready, but we don't use that in console yet. We would need to refactor Console a bit to use Apollo Client to handle websockets.
