### ISSUE TITLE
Navigation through SPA with Luigi Client reloads the whole app

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/console#268]
**Description**

Single Page Application which uses Luigi Client reloads when navigating using Luigi Client to a path within the SPA. This causes doing unnecessary network requests, like closing and establishing Websocket connection once again. In a result we lose all benefits of SPA.

**Expected result**

The URL path changes, but without reloading the app (microfrontend)

**Actual result**

The application reloads

**Steps to reproduce**

1. Navigate to `console.kyma.local`
1. Open developer tools - Network tab
1. Navigate to `instances` section within any environment
1. Click details of any instance

**Comment by kwiatekus** [comment]
Our assumption that this should work when the external view is plugged in via micro fron-end CRD was wrong.
I have applied an example `ClusterMicrofrontend` (attached).
The navigation from list to the list element is realized via luigi client navigate API, like this:
```
gotToDetails: (id) => {
        LuigiClient.linkManager().navigate(`${id}`, null, true);
    },
```
When user clicks on the list element, the tractor detail view is loaded completely new. While 
 we assume that the same instance`externalViewComponent` would be used to render the list and the details view, a completely new instance of `externalViewComponent` is used for the details view.

**Comment by kwiatekus** [comment]
Problems with `externalViewComponent` are fixed.
After this changes are release in kyma, the console will properly handle SPA routing within microfrontends.

@pkosiec this fix doesn't apply to the custom component we use so far to host service instances view.
To benefit from this fix, you will need to define ServiceInstances view as `ClusterMicrofrontend`, like in an example attached:

[serviceinstances-cmf.yaml.txt](https://github.com/kyma-project/console/files/2557936/serviceinstances-cmf.yaml.txt)

Optionally, you can wait until console is fully luigified (https://github.com/kyma-project/console/issues/282), as proper SPA routing for microfrontends comes out of the box with Luigi.
