### ISSUE TITLE
Basic setup for luigified console

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#293]
Start an epic branch.
Include  luigi-core.
Implement configuration for luigified console.
Make sure the application can be conteneraized properly
Preserve  console configuration (assets/config/config) mechanism

**Comment by jesusreal** [comment]
Branch created: https://github.com/kyma-project/console/tree/luigification-of-console-core. This branch will be used as main branch to merge all luigification related tasks. Only once whole luigification is achieved and well tested, then we will merge this branch to master.

**Comment by jesusreal** [comment]
Working branch for this ticket: https://github.com/jesusreal/console/tree/basic-setup-for-luigified-console
