### ISSUE TITLE
Enable authentication via DEX in luigified console

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#294]
Configure `authentication` section so that  dex is used as authentication provider

**Comment by dariadomagala** [comment]
The 404 task introduced a bug:
When I try to login, I'm redirected to the ```#/accesstoken=...``` route. New mechanism reads it as an unknown route and redirects me to `#/`, and there, because I'm not logged in, I'm redirected back to the login page.

**Comment by kwiatekus** [comment]
> The 404 task introduced a bug:
> When I try to login, I'm redirected to the `#/accesstoken=...` route. New mechanism reads it as an unknown route and redirects me to `#/`, and there, because I'm not logged in, I'm redirected back to the login page.

We should make sure the the redirection from DEX loads a dedicated hash consuming path (that exists in luigi already). Change dex-config-map.yaml in kyma

**Comment by kwiatekus** [comment]
This occurs when :
 - using luigi@0.3.8
 - configuring hash routing

After login page, user is redirected to the following view: 

![Screen Shot 2018-11-26 at 12.59.00.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/8f40dfc0-c1f4-4354-8bc3-b12dd8cd1ccb)

**Comment by maxmarkus** [comment]
> This occurs when :
> 
> * using luigi@0.3.8
> * configuring hash routing
> 
> After login page, user is redirected to the following view:
> 
Thanks, I have found and fixed this bug already in my branch.

**Comment by maxmarkus** [comment]
To test the functionality, those two branches must be used together:
PR for Console: https://github.com/jesusreal/console/pull/9
PR for Luigi: https://github.com/kyma-project/luigi/pull/251
