### ISSUE TITLE
Service RE labels are wrong in the Service Catalog

### ISSUE THREAD

**Issue by mcansimsek** [kyma-project/console#317]
**Description**

When I bind two remote environments to one environment, the services with the same name has also same remote environment label. 

![image](https://user-images.githubusercontent.com/15628751/48271435-9db73380-e43c-11e8-8798-78e0483a296d.png)

**Steps to reproduce**

1- Bind two REs, which has the service with the same name, to the same environment
2- Open catalog and check the label of the services

**Comment by mjasinski5** [comment]
@mcansimsek @lszymik  Ive seen that you unregistered those 2 classes from wormhole cluster, could you please bring it back? ;) Just for testing&review purposes, it would speed up the process.

**Comment by mcansimsek** [comment]
@mjasinski5 I registered those services to "stage" environment

**Comment by mjasinski5** [comment]
@mcansimsek thanks! 👍
