### ISSUE TITLE
Tests creates a Redis service instance with wrong plan

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/console#320]
**Description**
The service-catalog test creates a Redis instance with plan Enterprise, which is not good (created PVC). The enterprise plan makes the time of test running much bigger.

**Expected result**

The test must create a redis with plan "Micro"

**Actual result**

The test creates Enterprise Redis

**Steps to reproduce**

Run ui tests and watch created pods.

**Comment by pkosiec** [comment]
Fixed in #324
