### ISSUE TITLE
Resource Status Consistency

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#334]
Goal of this epic: 

Add meaningful status indicators to CRDs (if applicable) and apply common look&feel for all status indicators in kyma console

For the visual representation the proposal would be to have a textual representing of the status that is colour coded and the status should be aligned to the total right (but left to the actions if available). On hover a tooltip appears that give you a detail description - if available

![status1.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/e4e3e944-4cff-4d94-94fc-b0b75a29c3c2)
![status2.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/0b78f326-03cf-4965-a71a-a0b1a8c48ea3)

**Comment by dariadomagala** [comment]
All issues are closed.
