### ISSUE TITLE
lambda ui sends multiple create reqs for same SBU hence HTTP 409

### ISSUE THREAD

**Issue by sayanh** [kyma-project/console#341]
**Description**

When 2 or more servicebindings are existing on a lambda, then if both are removed and created a new servicebinding in the same form, the following is observed:
- the new servicebinding is created -> good
- lambda ui sends multiple create requests(equal to the number of servicebindings which are deleted)
- HTTP 409 errors are observed in Chrome console.

- Kyma version 0.5

**Expected result**
- Only one set of create-requests should be done no matter how many servicebindings are deleted.

**Cause**
- Lines https://github.com/kyma-project/console/blob/master/lambda/src/app/lambdas/lambda-details/lambda-details.component.ts#L500-L507 are within `forEach` in [here](https://github.com/kyma-project/console/blob/master/lambda/src/app/lambdas/lambda-details/lambda-details.component.ts#L468).

**Comment by kwiatekus** [comment]
This is not a priority, as we are in process of  complete rework of lambda UI which is based on new serverless backend solution
