### ISSUE TITLE
Monitoring guidelines for web apps on base of lambda-ui

### ISSUE THREAD

**Issue by lilitgh** [kyma-project/console#343]
**Description**
UI components based on nginx have several characteristics important for monitoring in order to assure a healthy operation.
The goal of this issue is
- to define which metrics are relevant for UI components (incl. [RED](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/) metrics), see also https://github.wdf.sap.corp/SAP-CP-Extension-Factory/community/blob/master/sig-and-wg/sig-quality/investigations/nfr_components.md
- have these metrics exposed for the lambda-ui
- to define relevant alert rules on base of that metrics
- activate relevant alert rules for metrics of lambda-ui
- have relevant metrics summarized in a grafana dashboard
- have a document explaining others how to apply the same for ui components, located here: https://github.com/kyma-project/community/tree/master/guidelines

Monitoring Documentation:
- Metrics: https://github.com/kyma-project/examples/tree/master/monitoring-custom-metrics
- Dashboards: https://github.com/kyma-project/kyma/tree/master/resources/monitoring/charts/grafana#making-a-dashboard-part-of-kyma-installation
- Alerting: https://github.com/kyma-project/examples/tree/master/monitoring-alert-rules

Please talk to @bszwarc about the documentation details.

**Comment by rakesh-garimella** [comment]
Blocked as we dont have sidecar we cannot get istio metrics.

**Comment by joek** [comment]
Please add a sidecar to the lambda-ui and try to expose it via API. Nobody could tell me why it is working like it is... If this is not as easy as expected, we have to raise the flag here
