### ISSUE TITLE
Microfrontends Integration in Luigified Console 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#351]
Luigified Console should call kyma api to fetch (Cluster)Microfrontends and build navigation nodes for them.

**Comment by maxmarkus** [comment]
yamls for testing. create a _tets_ namespace and upload the resources.

[tractors_mf.yaml.txt](https://github.com/kyma-project/console/files/2647789/tractors_mf.yaml.txt)
[tractors2_cmf_environment.yaml.txt](https://github.com/kyma-project/console/files/2647790/tractors2_cmf_environment.yaml.txt)
[tractors3_cmf_cluster.yaml.txt](https://github.com/kyma-project/console/files/2647791/tractors3_cmf_cluster.yaml.txt)

**Comment by maxmarkus** [comment]
PR ready: https://github.com/jesusreal/console/pull/16

**Comment by kwiatekus** [comment]
There might be path conflicts.

1. Conflicts between MF paths and 'console' paths
We have to be able to distinguish path segments that target a MF, i.e some prefix (`/mf-bla`), or path in between (`/extensions/bla`)


2. Conflicting micro front-ends, i.e two MFs configured for the same `/path`
The system is owned by single customer, who can figure our potential clashes on his own.
