### ISSUE TITLE
Prow pipeline for kyma/console

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#353]
- Migrate CI from Jenkins into Prow job, and make prow as master CI
- Check if we need to update documentation

**Comment by y-kkamil** [comment]
these are test-infra PRs containing:

* presubmit / postsubmit jobs: https://github.com/kyma-project/test-infra/pull/249/files
* updated node-buildpack with some needed tools: https://github.com/kyma-project/test-infra/pull/262/files
* updated all console components to use that buildpack: https://github.com/kyma-project/test-infra/pull/263/files
