### ISSUE TITLE
Apply SAP Fiori Fundamentals to all views in console

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#365]
~~This epic covers preparation work to get ready to start with https://github.com/kyma-project/console/issues/369~~

The goal of this epic is to have all views in console using SAP Fiori fundamentals in order to have a consistent UI which is easy to maintain.

Links:
https://sap.github.io/fundamental/index.html
https://github.com/SAP/fundamental-react
https://github.com/SAP/fundamental-ngx

**Comment by jesusreal** [comment]
Temporary PRs:
- Console: https://github.com/kyma-project/console/pull/602
- Kyma:

**Comment by hardl** [comment]
closed since all issues closed
