### ISSUE TITLE
New basic navigation structure in console

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#366]
AC:
* Main entry page to Kyma console will be the navigation branch that is currently under "Administration" node
* "Workspace" node is moved to that branch and renamed to "Environments" (or "Namespaces", depending on current state of renaming) 
* selecting an environment will switch to the second branch, which is what we currently have under environments (minus "Workspace")
* there must be a static node at the top of the environment nodes that will navigate you back to the first branch (cluster-scope)
* Docs node must be a top header node with a help icon, between environment chooser and profile icon

![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/c8433ece-58d1-437d-a25b-2bfea893f1a7)

![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/c3f881e8-2180-427d-b170-6840e81e4153)

**Comment by kwiatekus** [comment]
Only navigation structure changes are in scope.
Ignore changes in the content views (for example list searching, filtering)

**Comment by dariadomagala** [comment]
There is no support for icons yet, so for now, we will only refactor the navigation structure. Second part of this task will be done when the support for icons will be provided.

Navigation restructure PR:
https://github.com/jesusreal/console/pull/34

**Comment by dariadomagala** [comment]
Navigation structure has been updated. 

TO DO:
Add icons to navigation nodes when luigi#60 is merged.

**Comment by kwiatekus** [comment]
UI tests were failing.
Fix for ui tests : https://github.com/jesusreal/console/pull/36
please review
