### ISSUE TITLE
Service Catalog UI displays service classes documentation with wrong styling

### ISSUE THREAD

**Issue by PK85** [kyma-project/console#372]
**Description**

Service Catalog UI displays service classes documentation with wrong styling.

**Expected result**

<img width="1213" alt="screen shot 2018-12-03 at 20 36 29" src="https://user-images.githubusercontent.com/9609118/49402143-62f9a000-f749-11e8-9691-6a8234d1f7aa.png">
link: https://github.com/kyma-project/kyma/blob/master/docs/service-brokers/helm-broker-service-classes/gcp-broker-provider/docs/plans-details.md

**Actual result**

<img width="1546" alt="screen shot 2018-12-03 at 20 36 43" src="https://user-images.githubusercontent.com/9609118/49402150-6725bd80-f749-11e8-87ff-c7916ab9038d.png">

**Steps to reproduce**

Activate GCP Broker bundle, link: https://github.com/kyma-project/kyma/blob/master/docs/service-brokers/docs/003-overview-gcp-broker.md

**Comment by pkosiec** [comment]
Review: @akucharska @magicmatatjahu
