### ISSUE TITLE
Enable new asyncapi view in catalog and instances

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#376]
**Description**

- add new event component to catalog and instance UI
- remove old one
- test if asyncapi spec is rendered properly

**Reasons**

at the moment we have very minimalistic ui for rendering asyncapi and we need to integrate the new component that we created for the open source https://github.com/asyncapi/asyncapi-react

**Attachments**

<img width="1355" alt="screen shot 2018-12-05 at 00 20 48" src="https://user-images.githubusercontent.com/6995927/49479539-a9233200-f823-11e8-9d3b-d813d7f8259b.png">

**Comment by mjasinski5** [comment]
Review: @akucharska @mjasinski5
