### ISSUE TITLE
Rename Environments to Namespaces in Console UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#381]
**Description**

Currently we are fetching namespaces with a special label (`env`) and we show them in console UI as `environments`. The goal of this task is to rename  `environment` to `namespace` in the UI, so that user doesn't see the work environment anymore. 

**To do**
- [x] rename labels in UI and rename relevant component names
- [x] adjust ui and unit tests
- [x] adopt any readme files (if relevant) in the console documentation (additional task to adopt kyma docu to be created)

**Comment by dariadomagala** [comment]
* Rename labels - done
* Change routes - done
* Adjust UI and unit tests - done

Components, function, classes etc names will be changed in a different task, probably after luigification of console.

**Comment by kwiatekus** [comment]
@dariadomagala When introducing PR for KYMA, please take into account also changes in [docs folder](https://github.com/kyma-project/kyma/tree/master/docs/console/docs)
