### ISSUE TITLE
Reuse alert mechanism from Luigi to handle resource quota limit exceeded use case

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#382]
We need consistent alerting in the console application.
Once we use Luigi in console, lets use the same mechanism which is used for handling unresolved routes (404 alerts in the App.html)

```
	{#if alert && alert.message}
	<div class="fd-alert fd-alert--error fd-alert--dismissible" role="alert" id="j2ALl423">
		<button on:click="set({alert:null})" class="fd-alert__close" aria-controls="j2ALl423" aria-label="Close"></button>
		{alert.message} {alert.link}
	</div>
	{/if}
```

**Comment by dariadomagala** [comment]
Review together with: https://github.com/jesusreal/console/pull/21

**Comment by kwiatekus** [comment]
We agreed during sprint review, that for now we will display the alert in the views themselves (as in old console)

Please tweak the positioning of the alert (left)

**Comment by kwiatekus** [comment]
For the scope of that task, that's it:
https://github.com/jesusreal/console/pull/29/commits/5460c34ad3acaeef656a0b99d2247f2329f12e68
(pushed together with luigification clean up PR)

New task for creating alert/notification component in luigi:
(tbc)
