### ISSUE TITLE
Include reset.css in console's docs page and fix docs styling

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/console#398]
**Description**

At the moment there is an incorrect path to `reset.css` in [console's docs index.html](https://github.com/kyma-project/console/blob/a64a1343740b98eefd44717aadb7d14c010cd0f2/content/public/index.html). After using `%PUBLIC_URL%` in path, docs styling breaks.

**Expected result**
Correctly styled console documentation with `reset.css` included.

**Actual result**
At the moment `reset.css` rules are not included.
After including them this is how the docs look:
![screen shot 2018-12-10 at 15 02 04](https://user-images.githubusercontent.com/45565988/49737236-9ded5d80-fc8c-11e8-8bbc-e1dcf0692bd4.png)

**Steps to reproduce**
Visit console's documentation.

**Troubleshooting**
Replaced 
```html
<link rel="stylesheet" href="/public/reset.css" />
```
with
```html
<link rel="stylesheet" href="%PUBLIC_HTML%/reset.css" />
```

**Comment by derberg** [comment]
not valid, fixed already
