### ISSUE TITLE
Fix React Components gallery page

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/console#400]
**Description**
React components library page throws an error 1-2 seconds after accessing the page.

**Expected result**
The component library should render correctly.

**Actual result**
![screen shot 2018-12-10 at 15 26 30](https://user-images.githubusercontent.com/45565988/49738611-0b4ebd80-fc90-11e8-91af-1e1d42233e6d.png)

![screen shot 2018-12-10 at 15 22 32](https://user-images.githubusercontent.com/45565988/49738348-73e96a80-fc8f-11e8-997a-7e91c497ac09.png)

**Steps to reproduce**
Launch `npm run styleguide` script in `console/components/react/` directory and visit `http://localhost:6060`.

**Comment by kwiatekus** [comment]
Cannot reproduce
