### ISSUE TITLE
Lambda UI  in luigified console using unreleased dirty state handling of luigi

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#401]
- Cannot type in the *code* editor
 - errors in the console while typing in the *function name* input field
 - cannot save

```
_kyma_project_luigi_client__WEBPACK_IMPORTED_MODULE_25__.uxManager(...).setDirtyStatus is not a function
```

**Comment by parostatkiem** [comment]
Pull request: https://github.com/jesusreal/console/pull/28
