### ISSUE TITLE
Token is not shared between tabs in Console UI Core

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/console#404]
**Description**

User token for Console UI Core is not shared between tabs or windows.

**Expected result**

Token is shared between tabs. Users don't have to provide credentials for every new tab or window.

**Actual result**

Users that create new tabs/windows have to log in again.

**Steps to reproduce**

1. Log in to Console UI Core
1. Open any link from Console UI in a new tab
1. See the login form

**Comment by y-kkamil** [comment]
this is to be fixed in #282
