### ISSUE TITLE
'Create new environment' option missing in context chooser

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#405]
![Screen Shot 2018-12-11 at 13.18.08.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/4d5f8f2e-4ce9-4ef4-863b-03efadb37720)

**Comment by parostatkiem** [comment]
Pull request: https://github.com/jesusreal/console/pull/26

**Comment by kwiatekus** [comment]
as a temporary solution:
 - navigate to overview page and open the create environment modal

this could be achieved via nodeParam, i.e

`/environment?~openModal=true`

**Comment by pekura** [comment]
Let's implement the context chooser refresh in the console only for now and discuss the refresh context chooser functionality in Luigi properly after the holiday season.
For now:
- the create new environment view sends a message to parent window after creation
- the console installs a window message listener and upon receiving the env creation event it instructs Luigi to refresh the context chooser.
