### ISSUE TITLE
Consistent use and content of actions menu

### ISSUE THREAD

**Issue by k15r** [kyma-project/console#406]
**Description**

In lists like the lambdas list or the remote environments list we display an actions menu. The content of this list is inconsistent across different areas.

In lambdas it only shows the 'delete' action
![screen shot 2018-12-11 at 13 44 50](https://user-images.githubusercontent.com/292906/49802073-30a10180-fd4c-11e8-8450-0e8189d80308.png)
whereas in 'remote environments it shows also a 'details' action.
![screen shot 2018-12-11 at 13 44 04](https://user-images.githubusercontent.com/292906/49802030-1cf59b00-fd4c-11e8-8cd8-a6eb6a16c906.png)
The shortcut of the details action is the same as the hyperlink on the name of the remote environment.
The a similar hyperlink is available on the lambdas list, but this hyperlink is not duplicated by a named action in the actions menu.

Other lists do not use the actions menu at all and directly display actions inline (e.g. service instance list). Here we should also use an actions menu.
![screen shot 2018-12-11 at 13 59 43](https://user-images.githubusercontent.com/292906/49802398-0f8ce080-fd4d-11e8-94f7-e479629b8b6d.png)

**Reasons**

The ui would be more consistent if we would always or never create such details links and always display an actions menu if the user can execute actions on a lines item.

**Comment by ly1ila** [comment]
SAP Guidelines: "When more than three actions exist per row and/or space doesn’t allow for actions, a contextual menu can be substituted in order to display all actions in one menu."

This means that all actions should be visible unless we have more than 3 elements or no space at all. The linked name leads to the detail page.

**Comment by kwiatekus** [comment]
Closing as duplicate in favor of https://github.com/kyma-project/console/issues/1385
