### ISSUE TITLE
Service Binding Modal in Lambda-ui triggers backdrop on luigi

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#421]
**Description**

This is relevant only on the luigification branch.

1. Go to lambdas, create a lambda.
2. Open the lambda again and click ''+ Create Service Bindings"
3. You will se the service binding component shown inline, but it triggers backdrop just as if it was a modal.
![screen shot 2018-12-14 at 16 36 54](https://user-images.githubusercontent.com/6783567/50012532-32263000-ffbf-11e8-9396-79b13b1643ac.png)

**Comment by dariadomagala** [comment]
This view should be displayed as a modal, so the backdrop should be there. Problem with modals styles is fixed here: https://github.com/jesusreal/console/pull/32
