### ISSUE TITLE
Better error messages in lambda ui

### ISSUE THREAD

**Issue by k15r** [kyma-project/console#434]
**Description**

Try to create a new lambda function with the same name as an already existing one. Instead of showing some clear error message it tells you:

```
Http failure response for https://apiserver.kyma.local/apis/kubeless.io/v1beta1/namespaces/stage/functions/<function name>: 409 OK
```

**Reasons**

The user should be able to understand the error.

**Comment by kwiatekus** [comment]
We are investing in new UI for function controller. So we'd rather take it into account in the view instead of fixing it in the one that will be removed
