### ISSUE TITLE
Improve styling of error alerts in modals

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#436]
**Description**

Improve styling of error alerts in modals. in console (on luigi)

**Attachments**

<img width="488" alt="screen shot 2018-12-21 at 12 11 31" src="https://user-images.githubusercontent.com/6783567/50340339-eb828980-051a-11e9-9aaa-4fd08237ec5a.png">

**Comment by kwiatekus** [comment]
Maybe we can use non-dismissible error alert component and render it inline inside the modal component?

https://sap.github.io/fundamental/components/alert.html#error

**Comment by parostatkiem** [comment]
It would be a nonsense to modify the modal in 11 different places in Console. We should do this task after Luigi is able to handle modals (and alerts) and do the change in one place instead :)

**Comment by kwiatekus** [comment]
We will invest in react based modals and use them in the application
