### ISSUE TITLE
Explore possibilities to render in UI OData specification in Service Catalog views

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#477]
**Description**

* Explore different tools for reference docs visualisation
* Explore different tools for data model visualisation
* Provide clear recommendation where to go: 
  * Some table in the comment with overview of the tools, pros/cons of using, blockers and explanation why not use something (like we had with asyncapi, that the only component available was a serverside webapp that could not be integrated at all)
  * Estimation how much time we need in case we create whole components from scratch. Separate estimation per reference visualisation and data model visualisation
* Version support: best is latest (v4) always, as long as we have an official XSD schema to build-in proper validation in future. We should explore what would have to be done to support transformation of older versions into v4

**Reasons**

For now Service Catalog views support nice rendering of Swagger and AsyncApi files. We want to enable such functionality for OData but we need first to explore what are the options and if we can reuse something or have to create some components from scratch.

Why OData? Kyma is? because quoting kyma-project.io, Kyma `allows you to extend and customize cloud-based and on-premise enterprise applications in a quick and modern way`
Many enterprise applications expose OData and they want that after connecting into Kyma their APIs are also nicely represented like the REST APIs.

**Hint/Resources**
- https://www.odata.org/documentation/
- this is how OData EDMX looks like in the UI once it is translated into OpenAPI Swagger file http://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/master/examples/TripPin.openapi3.json -> we do not want to go this direction, but you can at least see how the visualisation of data model looks like
- example of OData visualisation in https://pragmatiqa.com/xodata/
- https://odataexplorer-p1940953245trial.dispatcher.hanatrial.ondemand.com/index.html#/Alphabetical_list_of_product
- also register here https://register.sapdevcenter.com/SUPSignForms/ and then check out this sample spec https://sapes5.sapdevcenter.com/sap/opu/odata/iwbep/GWSAMPLE_BASIC/$metadata
- check also samples from SAP API Business Hub https://api.sap.com/api/API_MKT_CAMPAIGN_TEMPLATE_SRV/overview
- different open source tools https://github.com/oasis-tcs/odata-openapi/tree/master/tools

**Comment by magicmatatjahu** [comment]
After investigation of some tools to render OData spec in the web I choose:

| Tool | Description  |
|--------------|---|
| [xslt](https://github.com/murrayju/xslt) | Tool for formating v2 and v3 to v4 of OData spec. Works on the browser side. Advantages: a lot of configuration options and it works! The downside is that it creates fields that should not be (most likely, but it must be investigated).  |
| [XSLT-processor](https://github.com/fiduswriter/xslt-processor) | Another package runs in the browser for changing old version to v4 od OData. It already doesn't work with some (special) fields, but it is still being developed |
| [XSL def](https://github.com/oasis-tcs/odata-openapi/blob/master/tools/V2-to-V4-CSDL.xsl) | XSL definition file for changing old version to newest (by xslt package) |
| [Ratago](https://github.com/jbowtie/ratago) | Implementation of xsl processor in GoLang (if we would like write service to processor old version in service of Asset Store) |
| [AsyncApi React](https://github.com/asyncapi/asyncapi-react) | Someone, who will write component for Reference visualisation, can follow by this library 😄  |
| [React Voyager](https://github.com/APIs-guru/graphql-voyager) | React component for graphQL schema visualisation. It can be used with modification for OData schema visualisation |

Estimation:
- Reference visualisation: 1-2 week (depending on the complexity of the graphics and the problems encountered).
- Schema visualisation: 3-4 week (depending on the difficulty of rewriting [React Voyager](https://github.com/APIs-guru/graphql-voyager) to use OData Schema).

**Comment by derberg** [comment]
Great investigation. So looks like we can make decision that:
- we need to create new react odata components
- support v4 only
- v2 and v3 will be transformed realtime into v4 on a client side. This is an approach that will give the component higher adoption rate in community, while it is not very expensive browser operation

First we will focus on reference docs implementation. Design will be similar to https://pragmatiqa.com/xodata/ (API Details tab, Normal View mode) but of course using our components.
Second, in next releases we will work on the data model visualization.
