### ISSUE TITLE
Provide Lambda UI resiliency  to available backend functionality

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#479]
**Description**

According to my knowledge  Lambda UI depends on 3 different domains (please verify)
- servicecatalogaddons -> without it, binding of lambda do service binding is not possible and in my opinion if UI knows that this domain is not available, the UI should not show the Binding component that you can see now in the attachment
- content and application -> without it, lambda UI will not get a list of events available to set as a Event Trigger 

**Reasons**

Console backend (graphql layer) is now modular, which means you can disable/enable a given domain. This means that in future Kyma user can install Kyma for example without Service Catalog, and the backend and UI will still properly work as ServiceCatalog domain functionality will be disabled.

Above requires proper handling of information delivered by the backend response, to not fail the UI but dynamically adjust it.

**Attachments**

![screen shot 2019-01-11 at 15 00 09](https://user-images.githubusercontent.com/6995927/51037912-eeb8e480-15b1-11e9-9062-dbab1d9a8d00.png)

AC:
- Only enable Lambda UI if all Modules are installed

**Comment by joek** [comment]
We have to wait for #578 .

**Comment by joek** [comment]
Moved out of 0.8 scope as we will implement "real" responsiveness as part of the knative story.

**Comment by kwiatekus** [comment]
We are in process of rewriting lambda UI as we want to support new function controller. Resilience to available backend modules will be assured.
