### ISSUE TITLE
Apply fiori ngx generic-list to all namespace related list views 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#486]
Use the new generic list and see if it works. 

 - [x] APIs
 - [ ]  Permissions
 - [x]  Resources
 - [x]  Config maps
 - [x]  Lambdas
 - [x]  Deployments
 - [x]  Replica Sets
 - [x]  Pods
 - [x]  Services
  - [x] Secrets

**Comment by dariadomagala** [comment]
I'm working currently on the cluster related list views. The 'permissions' component is shared between cluster and namespace views, so please contact me before staring to work on it to avoid conflicts and duplicated work.

**Comment by parostatkiem** [comment]
PR: https://github.com/jesusreal/console/pull/54
