### ISSUE TITLE
Apply Fiori ngx components for details views

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#488]

**Comment by kwiatekus** [comment]
Namespace Overview
Org details view (settings)

**Comment by parostatkiem** [comment]
The PR that constantly disconnects: https://github.com/kyma-project/console/pull/498

**Comment by parostatkiem** [comment]
#### Part 2
replace all "things" with `sf-*` classes with Fundamental-NGX or normal Fundamental-UI.
