### ISSUE TITLE
Extract all modular microfrontends from static console configuration into clustermicrofrontends CRs

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#495]
As a first step these CRs can be part of console chart.

AC:
* after deleting all clustermicrofrontends in a running kyma cluster, console must have the following navigation nodes:
![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/10ffcef1-2438-4b5c-ac5c-1da1b990a1a4)

![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/f5200bb2-ba83-4613-94f8-8ba72d1dd02b)

**Comment by kwiatekus** [comment]
Adapt cross links to reflect the mf- or cmf- prefixx in the p[ath segments

**Comment by pekura** [comment]
Preliminary CMF CRDs for console modules:  
[cmfs.zip](https://github.com/kyma-project/console/files/2773704/cmfs.zip).
