### ISSUE TITLE
Apply Fiori ngx components in list entry detail views

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#505]
**Description**

Apply fiori ngx library on the following views:
- secret detail view - http://console-dev.kyma.local:4200/home/namespaces/production/secrets/details/istio.default
- service detail - http://console-dev.kyma.local:4200/home/namespaces/production/services/details/hb-redis-micro-05033b9c-1e49-11e9-b059-0242ac110013-redis
- service expose api - http://console-dev.kyma.local:4200/home/namespaces/production/services/details/hb-redis-micro-05033b9c-1e49-11e9-b059-0242ac110013-redis/apis/create
- application detail - http://console-dev.kyma.local:4200/home/cmf-apps/details/testenvironment
- permission details - http://console-dev.kyma.local:4200/home/global-permissions/roles/admin

**Comment by marynaKhromova** [comment]
PR can be found here: https://github.com/jesusreal/console/pull/51/files
