### ISSUE TITLE
UI tests does not cleanup namespace

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/console#516]
**Description**

After the test  I see `catalogtestenvironment` namespace.

**Expected result**

All created resources must be deleted

**Actual result**

`catalogtestenvironment` with 2 redis deployments still exists:

![catalogtestenvironment](https://user-images.githubusercontent.com/15731038/51676307-836e0a00-1fd6-11e9-9bdd-0514b214a8af.png)

**Steps to reproduce**

Install Kyma and run tests.

**Comment by derberg** [comment]
will be fixed with https://github.com/kyma-project/console/issues/472
