### ISSUE TITLE
Cleanup after fiori fundamentals migration finished

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/console#522]
**Tasks**
- Remove as many imports and custom styles as possible from css entryfile `core/src/styles.scss` 
- Remove techne and bootstrap 4 dependencies, imported in `core/src/consoleapp.html` from `core/src/assets/vendor/` folder
- remove `--min` classes for columns and replace it with `--col-1` (it's the same)
-  ~~Fix environment details view. See comment https://github.com/jesusreal/console/pull/64#discussion_r262147142~~
![panels .png](https://images.zenhubusercontent.com/5c3de4fc1c15204eff7a904f/5b1a985c-87f3-4696-803c-c6f8e63eb4ca)
(done in another task)

@marynaKhromova 
- Fix confirmation modals in lambdas 
![lambdas.png](https://images.zenhubusercontent.com/5c3de4fc1c15204eff7a904f/2bc619a0-54b9-4172-aa6a-6f3babfbbbfc)

**Comment by marynaKhromova** [comment]
Here is the PR for updated confirmation modal in lambdas https://github.com/jesusreal/console/pull/72

**Comment by parostatkiem** [comment]
### PR: https://github.com/jesusreal/console/pull/73
