### ISSUE TITLE
Enable role binding and cluster role binding for users

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/console#536]
**Description**
Now you can create role bindings and cluster role bindings only for groups. It should be possible to create bindings also to users.

**Reasons**
Kyma administrator should be able to grant particular user some role in the UI. It is possible using `kubectl` providing subject kind `User`.

Note: please ensure that it is possible to create RoleBinding to the ClusterRole (works only in the namespace).

**Comment by ly1ila** [comment]
Hi @pbochynski here is the UI proposal for this usage: 
[kyma_role-binding-user_UI.zip](https://github.com/kyma-project/console/files/2894412/kyma_role-binding-user_UI.zip) also to find in Zeplin: zpl://project?seid=5c6ed952a74b4b408586042e&pid=5ab0db46508f1e7a678a01c1
