### ISSUE TITLE
Prow should also build on generic-list changes for console + lambda

### ISSUE THREAD

**Issue by maxmarkus** [kyma-project/console#553]
Currently only changes in console/core and console/lambda trigger their respective prow job. 
Update the prow job so that it also listens to updates happening in the folder `console/components/angular/generic-list/src/app/modules/`.

According to Michal Hudy:
If both sources are in one repository then it is possible by defining `run_if_changed`, something like here: https://github.com/kyma-project/test-infra/blob/master/prow/jobs/test-infra/validation.yaml#L34

In general `run_if_changed` is a regex pattern that matches paths of edited files.

**Comment by kwiatekus** [comment]
Generic list is deprecated
