### ISSUE TITLE
Prepare GenericList for 'fd-table'

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#554]
Together we decided to use `fd-table`  for our tables in GenericList. Some changes need to be done in _plain-table_ and _plain-list_ (wrappers) to let *renderers* use this feature. 
### This task will visually break most of the list views
Each renderer needs to be adjusted to changes (use Fundamental's `fd-table` content)

**Comment by jesusreal** [comment]
I understood it differently:
- For 'plain-table' we have to use fundamental class 'fd-table'
- For 'plain-list' we have to use fundamental class ['fd-panel-grid'](https://sap.github.io/fundamental/layouts/panel.html#default-panel-grid-3-columns)

Let´s have this clarified before we start working on this ticket ;)

**Comment by parostatkiem** [comment]
PR:
https://github.com/jesusreal/console/pull/52
