### ISSUE TITLE
Fiori fundamental in modals

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#556]
Apply fiori fundamental in all modals in console core.

- [x] ~Information~
- [x] ~Confirmation~
- [x] ~Edit~
- [x] ~Create env~
- [x] Create IDP Preset
- [x] Create application
- [x] ~Edit application~
- [x] ~Create namespace binding~
- [x] ~Token / Connect application URL~
- [x] Create role binding
- [ ] Deploy new resource 

Check if there are any other modals.
~strikethrough~ means that is has been changed in other task.

**Comment by kwiatekus** [comment]
There is a separate task for modals in lambda-ui, so please dont include them in the scope of this one

**Comment by dariadomagala** [comment]
First PR (without deploy new resource modal): https://github.com/jesusreal/console/pull/56

**Comment by parostatkiem** [comment]
Deploy new resource modal PR: https://github.com/jesusreal/console/pull/59
