### ISSUE TITLE
Content UI manifest always pulled from master and updated only on image rebuild

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/console#558]
**Description**

1. Manifest for content UI is always pulled from `master` branch. What if we would like to release minor/patch releases?
1. Manifest is updated during Content UI build. It should be fetched from Minio or passed in config map

```
"prepare": "curl --insecure -o ./src/commons/manifest.yaml https://raw.githubusercontent.com/kyma-project/kyma/master/docs/manifest.yaml",
```

**Comment by derberg** [comment]
no manifest anymore, now it is replaces with headless CMS and UI reads CRs to build navigation
