### ISSUE TITLE
Create component for rendering OData spec - styling and integration

### ISSUE THREAD

**Issue by mjasinski5** [kyma-project/console#561]
**Description**

* integrated with console UI and make sure you test all works basing on real specs from SAP that is on ef the main OData users so a perfect testing model
* design will be similar to https://pragmatiqa.com/xodata/ (API Details tab, Normal View mode) basing on Fiori Fundamentals. You can imagine it is same as https://www.asyncapi.com/asyncapi-react/ but with different data ;)
* address issue of odata spec being saved in minio as `apiSpec.json`. Fixed in graphql needed

Stretch:
  * have expand/collapse functionality on all types like you have in swagger console https://editor.swagger.io/. But have it by type, and also globally as expand/collapse all
  * fetch EDMX file functionality as part of component (so it doesn't have to be fetched by user separately and passed as string)

**Reasons**

Reasoning and full investigation described here https://github.com/kyma-project/console/issues/477

**Comment by aerfio** [comment]
Remember to take care of #590

**Comment by aerfio** [comment]
Whoever takes this task - use this branch: https://github.com/aerfio/console/tree/odata

There are some things that had to be changed in comparison to what is on master (hooks declared in other place etc), so even if you change whatever styling structure there is - please use my branch, or "@" me :d

**Comment by aerfio** [comment]
Reminder:  take care of service worker in `index.tsx`
