### ISSUE TITLE
Styling issue in "create binding" modal

### ISSUE THREAD

**Issue by JohannesDoberer** [kyma-project/console#562]
In "Global Permissions"->"Cluster Role Bindings"->"+Create Binding".
Click in the first input field and try to write something you will see that the highlighting on this field is broken.
Also error message will not be cleared after closing and opening the modal again.

![Bildschirmfoto 2019-02-11 um 15.44.47.png](https://images.zenhubusercontent.com/5c346c4d86008d0a2e182a83/2b4dfad5-2898-43d2-affe-0a19a386a8ef)
![Bildschirmfoto 2019-02-11 um 15.45.02.png](https://images.zenhubusercontent.com/5c346c4d86008d0a2e182a83/9248bc6f-d595-4fa9-8f7e-c55bcd53ddcd)

**Comment by hardl** [comment]
Check if still valid

**Comment by dariadomagala** [comment]
Styling issue is fixed after fiorification, but error is still visible after reopening the modal.
