### ISSUE TITLE
UI has broken elememts

### ISSUE THREAD

**Issue by sayanh** [kyma-project/console#572]
**Description**
Double ticks in the api view.
<img width="1414" alt="screen shot 2019-02-13 at 14 08 23" src="https://user-images.githubusercontent.com/5954057/52714577-7f605700-2f9a-11e9-94bc-31b97d1f8936.png">

Border missing from drop down menu while creating API
<img width="779" alt="screen shot 2019-02-13 at 14 07 24" src="https://user-images.githubusercontent.com/5954057/52714658-bf273e80-2f9a-11e9-9d66-7e2cb5b75c40.png">

**Comment by kwiatekus** [comment]
Broken dropdown spotted also in:
 - namespace-to-application binding modal
![screen shot 2019-02-13 at 16 45 48](https://user-images.githubusercontent.com/6783567/52724335-6d3ce380-2faf-11e9-8ebb-d07b939ed444.png)

**Comment by hardl** [comment]
also lambda ui
![image](https://user-images.githubusercontent.com/7690363/52726669-e8a09400-2fb3-11e9-8da9-bc69b7270295.png)

**Comment by jesusreal** [comment]
Another modal in namespaces views:

![screen shot 2019-02-13 at 17 42 34](https://user-images.githubusercontent.com/8238188/52728027-cf4d1700-2fb6-11e9-93b6-1e1bdc45efcb.png)
