### ISSUE TITLE
Disable autocomplete for fiori popover inputs (eg namespace binding)

### ISSUE THREAD

**Issue by maxmarkus** [kyma-project/console#576]
There are some fields that are dropdown combined with custom input. In this case, the browser's autocomplete is triggered and adding an overlay above the fiori dropdown overlay.

Check after fiorification if this is still valid.

<img width="843" alt="dropdown-with-input" src="https://user-images.githubusercontent.com/1720843/52728882-5d75cd00-2fb8-11e9-9fd2-5ab734243627.png">

**Comment by dariadomagala** [comment]
It's not valid after fiorification. Although autocomplete option is not consistent for non-dropdown inputs. Some of those inputs have it enabled, some disabled and it would be good to use only one approach.
