### ISSUE TITLE
Fix top navigation nodes duplication for smaller screens

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#580]
**Description**

Fix top navigation nodes duplication for smaller screens.

**Expected result**

On smaller screens, nodes from the top navigation should be visible only in the dropdown, not also as a regular node.

**Actual result**

Docs node is visible twice on smaller screens. 
![Screen Shot 2019-02-15 at 12.35.12.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/6d18cca8-a395-43d9-a203-d4cabca72e8f)

**Steps to reproduce**

**Troubleshooting**

**Comment by JohannesDoberer** [comment]
https://github.com/kyma-project/luigi/pull/416

**Comment by marynaKhromova** [comment]
The issue was fixed within this task https://github.com/kyma-project/console/issues/580
