### ISSUE TITLE
Improve empty list placeholder in GenericList

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#581]
Currently we define a separate template for empty-list-placeholder in every place where `<y-plain-table>` is used, which means **many** places.
All of them are nearly the same. The only real difference is the presence of `+ Add new {something}` button. 

`<y-plain-table>`  should be able to take below **optional** parameters and use them to render (or not) the placeholder in case the list is empty:
- title: string
- subtitle: _string_
- button_text: _string_
- button_callback: _function_

The placeholder would be some kind of modular - e.g. you can only have a button without title, or opposite.
In case none of them is provided, the list should not render anything if empty.

Furthermore there should be still possible to provide a full template of the placeholder (like it is done now) instead of `<y-plain-table>` props, in case somebody wants to have a fully custom placeholder.

#### Please contact Franz about the design of the placeholder before starting this task

**Comment by kwiatekus** [comment]
Please consider this design when implementing:
https://luigifiddle-a748bf19e.dispatcher.hana.ondemand.com/#/home/empty

**Comment by jesusreal** [comment]
Proposed design by @ly1ila
![Screen Shot 2019-02-27 at 15.51.08.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/60f06fd8-6d90-48cc-8ea2-68ad194473ad)

Implemented design:
![Screen Shot 2019-02-27 at 15.51.35.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/0f6530ff-ee4b-4d30-9e42-c803eaf50dc4)


Git diff for reviewer to test changes: 
[https://app.zenhub.com/files/139590577/e1cdc538-bebc-423c-bfcf-655e88c4c0d9/download](https://app.zenhub.com/files/139590577/e1cdc538-bebc-423c-bfcf-655e88c4c0d9/download):

**Comment by jesusreal** [comment]
PR created: https://github.com/jesusreal/console/pull/63
