### ISSUE TITLE
Ci setup for OData React component

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/console#590]
**Description**
After merged #588 PR:
- create Prow Job for OData React component with `presubmit` and `postsubmit` stage in `test-infra` repository.
- create Makefile with pipeline for pr and master like in other package in `console` repo.

Stretch:
- create bash script for automatically pushing new version of component to npm, try to find a solution for pushing patch, minor and major version, eg with appropriate tag in title of PR.

**Reasons**
Better development of OData React component.

**Comment by aerfio** [comment]
[x] - also make `pre-master-kyma-components-asset-upload-service` required
