### ISSUE TITLE
Use Tabs component from React Fundamental in Instances

### ISSUE THREAD

**Issue by aerfio** [kyma-project/console#596]
**Description**
React Fundamental [tabs component](https://sap.github.io/fundamental-react/tabs) is fixed ([link](https://github.com/SAP/fundamental-react/issues/315)). We can use it in place of our component. 

**Reasons**

We want to be consistent with rest of codebase and style by using Fiori Fundamentals.

**Comment by aerfio** [comment]
Is it still valid?

**Comment by kwiatekus** [comment]
We try to avoid such items in backlog. This doesn't bring value to the end-user.
We will introduce fundamental-react tabs during continuous refactoring of the code.
