### ISSUE TITLE
Error on testing bundle installation should fail whole test instantly

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/console#603]
**Description**

When the catalog-UI test failed the testing bundle installation, then the test doesn't stop. In this situation, the output can be misleading!

**Expected result**

Test fails bundle installation -> whole test fails instantly and the output is clear.

**Actual result**

Test fails bundle installation -> test doesn't stop and the output can be misleading.

**Comment by kwiatekus** [comment]
Already done.
testing bundle is installed before test execution and fails the whole `testing.sh` execution in case of error
