### ISSUE TITLE
Wrap asyncapi docgen in react component 

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#61]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- use https://github.com/asyncapi/docgen that is reused in http://editor.asyncapi.org/ | https://github.com/asyncapi/editor
- have a working example to show it works
- have clear answer to question:
  - how much time it will take to have it here, working for us, with custom css over the default ones https://github.com/kyma-project/console/tree/master/components
  - how much time it will take to have it here https://github.com/asyncapi as our contribution to open source, with our offer to maintain it with org owner

**Reasons**

Current display of asyncapi is very minimalistic and requires a lot of improvements. Before we decide to write something on our own, we should check if we can actually reuse the official component used for that.

**Comment by michal-hudy** [comment]
https://github.com/asyncapi/docgen is a server side module and it cannot be used in frontend. I have contacted them and they are interested in contribution from our side. Currently, they form a team with codeowners and maintainers - we are invited to join.

I think implementation of a new React component that will fully support AsyncAPI may took 4-5 days.
