### ISSUE TITLE
Split luigi-config.js and write unit tests

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/console#610]
Now that we have transpilation in place for our luigi configuration in console, it is time to take advantage of it.

_luigi-config.js_ is way too long currently and it would be good to have unit tests for (at least) some of the business logic contained in this file.

[x] Split luigi config file in several files
[x] Write unit test for important business logic

Please work on a timebox and focus in writing the most relevant tests, not everything needs to be tested.

**Comment by kwiatekus** [comment]
We try to avoid such items in backlog. This doesn't bring value to the end-user.
We will do it as part of continuous refactoring of the code.
