### ISSUE TITLE
Action buttons should be part of the table they belong to

### ISSUE THREAD

**Issue by maxmarkus** [kyma-project/console#639]
Headlines that belong to a table should be part of the panel consisting the panel 
Eg similar to Namespace Details > Connected Applications

![image 4](https://user-images.githubusercontent.com/1720843/53869580-ce793500-3ff8-11e9-8c6a-7fc4948d4d16.png)

**Comment by kwiatekus** [comment]
In case there is only one list on the view, the create button will be placed in the page header. In other cases, the action buttons related to the list are already part of the list container
