### ISSUE TITLE
Unable to view lambda when created via kubectl apply <lambda.yaml>

### ISSUE THREAD

**Issue by joek** [kyma-project/console#66]
Confirm these statements before you submit the issue:

- [X] I have searched open and closed issues for duplicates.
- [X] I have read the contributing guidelines.
---

**Description**

When a lambda is created using yaml the UI is not able to parse it. The reason being empty container filed in deployment spec.

To reproduce the issue

Try creating lambda using following [yaml](https://raw.githubusercontent.com/kyma-project/examples/master/service-binding/lambda/deployment/lambda-function.yaml).
Try to view it on lambda UI page in console
Output of `lambda.spec.deployment.spec.template` is attached.

**Comment by lszymik** [comment]
Please take a look into it.

**Comment by joek** [comment]
The example is already adjusted. Will close the issue as with knative we will follow another aproach.
