### ISSUE TITLE
Refactor Catalog and Content views to read from DocsTopic CR

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#666]
**Description**

- Catalog and Instance views to read content from Headless CMS
- Content UI to read from Headless CMS
- ui-api-layer to have Headless CMS related queries (query and subscription) 
- make sure we render only docsTopics that have a proper label

**Reasons**

To start using Headless CMS

**Comment by pkosiec** [comment]
Okay, along with @michal-hudy  and @akucharska we set a basic contract. This is updated GraphQL schema for UI API Layer:

```graphql
type File {
	url: String!
	metadata: JSON!
}

type Asset {
	name: String!
	namespace: String!
	type: String! ("asyncapi", "markdown", "openapi", itd. - dowolne)
	files: [Files!]! 
}

type ClusterAsset {
	name: String!
	type: String! ("asyncapi", "markdown", "openapi", itd. - dowolne)
	files: [Files!]! 
}

type DocsTopic {
	name: String!
	namespace: String!
	groupName: String!
	assets(type: String): [Asset!]!
	displayName: String!
	description: String!
}

type ClusterDocsTopic {
	name: String!
	groupName: String!
	assets(type: String): [ClusterAsset!]!
	displayName: String!
	description: String!
}

clusterDocsTopics(viewContext: String, groupName: String): [ClusterDocsTopic!]!


type ServiceClass {
	...
	docsTopics: [DocTopic!]!
}

type ClusterServiceClass {
	...
	clusterDocsTopics: [ClusterDocTopic!]!
}
```

We will use the following labels in DocsTopic CR:
`cms.kyma-project.io/type`, `cms.kyma-project.io/groupName`, `cms.kyma-project.io/docsTopic` and `cms.kyma-project.io/order`.
The label `cms.kyma-project.io/order` value will order ClusterDocsTopics for `clusterDocsTopics` query. We will return ordered array based on the label value.
