### ISSUE TITLE
Proper usage of anchor tags in console UI

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/console#678]
We are using anchor tags without `href` attribute through the whole codebase and global css styling setting `cursor: pointer` for all links. This has some side effects, as:
- Text selection happens on double click (example: tabs, expand/collapse)
- Global style would also be applied to a disabled link.
Therefore the right approach is to let the browser apply default link behaviour by using `href` attribute, which will also free us from potential bugs and inconsistency issues. 

Recommended setup for links where no redirection takes place through href attribute is `href="javascript:void(null)"`

**Comment by marynaKhromova** [comment]
The pagination is not possible to change now, because of the wrong implementation of Pagination Fundamental NGX component. Already created the task about it https://github.com/SAP/fundamental-ngx/issues/611
