### ISSUE TITLE
Exposing API should not be available in system namespaces

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#679]
**Description**

Expose API should net be available for system namespaces

**Expected result**

'Expose API' is gone from the popover

**Actual result**

**Steps to reproduce**

Open a system namespace, i.e istio-system. Open Services and click action menu on one of the services

<img width="1918" alt="Screen Shot 2019-03-12 at 10 05 25" src="https://user-images.githubusercontent.com/6783567/54187774-92d5e380-44ae-11e9-812e-cd33744896c4.png">

**Comment by dariadomagala** [comment]
Should we also hide 'APIs' navigation node for those namespaces?
