### ISSUE TITLE
Update vulnerable dependencies and security scans

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#68]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

* WhiteSource and Checkmarx enabled for Instances, Catalog, Content and Website
* They should be triggered only on master
* Fix known vulnerabilities in our dependencies by updating them or changing dependency
  * catalog/package-lock.json -> unshiftio / url-parse - Known security problem with version 1.4.1
  * react/package-lock.json -> same as above
  * content/package-lock.json -> same as above
  * instances/package-lock.json -> same as above

**Expected result**

CI passes with all scans and GitHub no longer pings for vulnerable dependencies

**Actual result**

CI scans commented out

**Comment by akucharska** [comment]
https://github.com/kyma-project/console/pull/64
https://github.com/kyma-project/website/pull/28
