### ISSUE TITLE
react-odata NPM package has no license

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/console#688]
**Description**

The NPM package for the react-odata component is available under https://www.npmjs.com/package/@kyma-project/odata-react

This has no license declaration, what causes an issue in FOSSA license scan.

**Expected result**

All components have valid non-restrictive licenses. Kyma is licensed under Apache-2.0, and this should also be the license declared on the NPM packages issued by Kyma.

**Actual result**

No license available.

**Comment by pkosiec** [comment]
Fortunately, we've added LICENSE file in the package, which means this is false alarm. However, we will include license in package.json anyway.
