### ISSUE TITLE
Form from react-schema-form doesnt render properly with additionalProperties

### ISSUE THREAD

**Issue by mjasinski5** [kyma-project/console#69]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
All details are located here: https://github.com/mozilla-services/react-jsonschema-form/issues/963

AC:
- [x] Update react-schema-form on Catalog UI
- [x] Update react-schema-form on Instances UI
- [x] Test with Azure broker if it works

**Expected result**
Form renders with tags

**Actual result**
Form outputs an error

**Comment by mjasinski5** [comment]
waiting for https://github.com/mozilla-services/react-jsonschema-form/pull/1021 to be merged :) It has been reviewed already so its gonna be done soon ;)

**Comment by derberg** [comment]
1.6 released 
* https://www.npmjs.com/package/react-jsonschema-form
* https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v1.0.6

**Comment by pkosiec** [comment]
- [ ] Update react-schema-form version
- [ ] Check on Azure broker service plans whether the additionalProperties are visible

**Comment by pkosiec** [comment]
@aerfio Please create issue on `react-jsonschema-form` repository.  Maybe we will be able to do bug fixing there, but firstly we need to sync with the author of the PR that introduced `additionalProperties` support.

**Comment by aerfio** [comment]
https://github.com/mozilla-services/react-jsonschema-form/pull/1101
Solves 2 issues out of 3 of [this issue](https://github.com/mozilla-services/react-jsonschema-form/issues/1099)

Last one, adding "X" button to remove partiular pair will hopefully be taken care of here: https://github.com/mozilla-services/react-jsonschema-form/pull/1085
