### ISSUE TITLE
Alert window is misplaced  if other modal window is open

### ISSUE THREAD

**Issue by lilitgh** [kyma-project/console#690]
<img width="1410" alt="Screenshot 2019-03-14 at 09 54 27" src="https://user-images.githubusercontent.com/29227648/54343885-0bb87500-4640-11e9-89ec-0263669a41b5.png">

**Steps to reproduce**

On any list view when alert is appearing (for example lambdas with resource quota alert) open a modal window

**Comment by y-kkamil** [comment]
https://github.com/kyma-project/luigi/pull/435
