### ISSUE TITLE
Add content to an empty README.md for react-odata

### ISSUE THREAD

**Issue by kazydek** [kyma-project/console#698]
**Description**

Add content to an empty `README.md` for react-odata: https://github.com/kyma-project/console/blob/master/components/react-odata/README.md. Follow [this](https://github.com/kyma-project/community/blob/master/guidelines/internal-guidelines/repository-template/template/README.md) template.

Additionally:

- Add `”license": "Apache-2.0",` to package.json before publishing it. It will resolve [this](https://github.com/kyma-project/console/issues/688) issue.
- Publish the package on `npm` .
- Use the latest version of the package in the Catalog and Instances UIs.

**Related issues**
See also #688

**Comment by derberg** [comment]
readme already provided in https://github.com/kyma-incubator/documentation-component
