### ISSUE TITLE
Modify service catalog UI navigation

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#70]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- Remove left navigation
- Modify core to not collapse environment left nav for Catalog View
- Change position of search component and preserve functionality of real time results refresh
- Search supports search over all available card data
- Add filter that is a replacement for current left navigation
  - filter by category rename to filter by tag
  - limit list of elements in filter to 5 + the `see more` link to expand full list
  - search by tag part support search for all filters, so should be moved above as a first element in the filter
  - filter by remote environment out of scope for now
  - `All` concept supported for every filter
  - When you implement Tag filter, work on mock data with more than 30 tags to see how the UI will handle `see more` as this is a real use case of ours. Scroll bar must be visible to the users.
  - our of scope: indicator of amount of records of a given element (no values in brackets for now)
- update acceptance tests

**Reasons**

Adjust UI basing on feedback and current lack of scalability of the navigation

**Attachments**

![kyma_catalog-overview_1](https://user-images.githubusercontent.com/6995927/44780155-91cc0d00-ab81-11e8-9664-fcbb3b12a278.png)
![kyma_catalog-overview_2](https://user-images.githubusercontent.com/6995927/44780156-91cc0d00-ab81-11e8-8d72-63aa82ec55ee.png)
![kyma_catalog-overview_2-scrolling](https://user-images.githubusercontent.com/6995927/44780157-91cc0d00-ab81-11e8-921c-81f608fe0f0e.png)

**Comment by derberg** [comment]
Docs are part of DoD but anyway please remember to update https://github.com/kyma-project/console/blob/master/catalog/OSBAContract.md too

**Comment by michal-hudy** [comment]
Review: @magicmatatjahu, @michal-hudy

**Comment by derberg** [comment]
@akucharska @kazydek 
hmmm, please look into this document https://github.com/kyma-project/console/blob/master/catalog/OSBAContract.md, first screen shot and spot what is not updated at all ;)
