### ISSUE TITLE
Expose API "dex" predefined configuration does not work on minikube and xip.io

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/console#706]
**Description**

When you expose an API with security enabled, console provided pre-defined configuration for dex which is not needed and is wrong. On a minikube envoy cannot resolve dex.kyma.local cause it does not have access to host network and on a xip.io cluster which has self signed cert it cannot validate request over https  to ingress gateway.

JWKS uri should be set to dex FQDN, not dex.$DOMAIN because it fails on a minikube, on xip.io cluster and it creates additional load on istio ingress gateway, which is not needed.

Instead console should either change the JWKS uri to be dex FQDN(modify dex preset) **or** (suggested) just set authenticationEnabled to true in the API CR. API controller in such case add dex configuration with FQDN automatically.

**Expected result**

JWKS uri is set to dex FQDN.

**Actual result**

JWKS uri is set with dex.$DOMAIN

**Steps to reproduce**

On a minikube or on a a cluster with xip expose securely any API, it won't authenticate the token.

**Troubleshooting**

![Screenshot 2019-03-22 at 10 33 49](https://user-images.githubusercontent.com/17701416/54814186-806a5f80-4c8f-11e9-8a48-50654ea6ea11.png)

**Comment by hardl** [comment]
dex FQDN: http://dex-service.kyma-system.svc.cluster.local:5556/
