### ISSUE TITLE
Logging UI - Time interval is not properly set

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/console#722]
Definition of time interval (minutes, hours, days) is not properly set. Please check relevant code in _search-form.component.ts_ which applies logic on value set in the UI.

This screenshot shows evidence of the issue. Time should be set to 10:51:12 but it is set to 09:55:12. For hours and days the time is also not properly set. *A draft for unit test for this part are already in place, they need to be activated and checked once the bug is fixed*.

![Screenshot 2019-03-27 at 10.56.31.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/ee35a6b0-46de-4c5c-9d9d-4f1dcb0a8b17)
![Screenshot 2019-03-27 at 10.56.23.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/5b38ce66-efdc-4369-b274-c9deac9fdf9e)

**Comment by kwiatekus** [comment]
The log ui will be refactored completely
