### ISSUE TITLE
Improve secrets view to have it decoded in the UI

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#727]
**Description**

AC:
When I click on "Show details" I'd like to see a button next to encoded value that decodes it for me.

To consider:
Have copy button to copy the value to the clipboard.

**Reasons**

Would be awesome to have support for automated decoding like it is already possible in the Catalog views in the secrets preview components. Otherwise UI is not fully helping the user.

Now when you click on "Show details" you still see encoded value

**Attachments**

![Screen Shot 2019-03-28 at 13 32 20](https://user-images.githubusercontent.com/6995927/55157966-10138080-515e-11e9-8fdb-09ac05b7af69.png)

**Comment by akucharska** [comment]
Decoding have been added in issue [738](https://github.com/kyma-project/console/issues/738)
