### ISSUE TITLE
Load Test Lambda Implementation

### ISSUE THREAD

**Issue by joek** [kyma-project/console#729]
**Description**

As a DevOps I need to know the performance limits of my lambda function. To prove the service quality of the lambda functionality frequently running load tests should be integrated into the prow pipeline.

AC:
- Determine the max number of requests for each Function size with three different performing functions.
- Have a report including graphs to show the performance over time (including the HPA)
- (Think about and maybe implement) Develop a metrics to test if the performance has changed between two runs.

**Reasons**

Serving requests is the key feature of a lambda functions. We need to ensure to know the limits and find performance problems upfront.

**Comment by a-thaler** [comment]
This topic is covered by https://github.com/kyma-project/kyma/issues/3523, will close it
