### ISSUE TITLE
kyma-project/odata-react NPM package has no license reported

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/console#731]
**Description**

The NPM package https://www.npmjs.com/package/@kyma-project/odata-react is reported to have no license, causing a finding in FOSSA:

https://app.fossa.com/projects/git%2Bgithub.com%2Fkyma-project%2Fconsole/refs/branch/master/97fae53a2166547203dfad9dedc0c14915f6b90e/issues/licensing?filter=unlicensed_dependency&revisionScanId=523086

**Expected result**

The package is published with a license reported in the NPM listing.

**Actual result**

The package is published without a license reported in the NPM listing.

**Comment by derberg** [comment]
already reported, it is our component anyway and should be marked manually as resolved in Fossa, and later of course we will add license https://github.com/kyma-project/console/issues/688
