### ISSUE TITLE
Consider adding version information to console

### ISSUE THREAD

**Issue by arifC** [kyma-project/console#734]
**Description**
I would find it helpful if there's an easy non-terminal way to find the installed Kyma version. An appropriate place could be the /docs page.

**Reasons**
The version information is generally useful for reporting issues or looking up documentations. But it also plays a major role in upgrading Kyma. Before an upgrade, I always check my version first. There is no documented way of finding the Kyma version, so everyone needs to find their own way (see https://github.com/kyma-project/kyma/issues/3338).

**Attachments**
Alternative request: https://github.com/kyma-project/kyma/issues/3338

**Comment by kwiatekus** [comment]
Duplicate of  https://github.com/kyma-project/console/issues/754
