### ISSUE TITLE
Display Kyma version in the Console UI

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/console#754]
**Description**
Display version of Kyma in the UI.

**Reasons**
It should be easy to user to identify Kyma version. Now you can do that only by inspecting kyma-installer deployment in namespace kyma-installer:
```
kubectl -n kyma-installer get deployment kyma-installer -o jsonpath="{.spec.template.spec.containers[0].image}
```
Distinguish kyma instances deployed from released versions which have pattern:
```
eu.gcr.io/kyma-project/kyma-installer:VERSION
```
from those deployed from sources.

Fetch the `kyma-installer` deployment via gql (new query needed for fetching single deployment by name and namespace) and parse the image version string:
If image source is `eu.gcr.io` and the version is a semVer (incl. RCs), display it, i.e `1.0.0`
If image source is `eu.gcr.io` but the version is a commit hash, display it like that `master ({commit hash})` 
If thesource is not `eu.gcr.io`, show the full image path as a version in the ui

Designs can be found here:
https://app.zeplin.io/project/5ab0db46508f1e7a678a01c1/screen/5cd42cf183b4fc5dee341e8a

**Comment by ly1ila** [comment]
Hi pbochynski, 

In consultation with the SAP Product Design Team, we recommend that you place the version number in the footer (actually under the fields on the right). @kwiatekus will determine which information should be placed there (for example, copyright notices).

![kyma_version_footer](https://user-images.githubusercontent.com/25120433/56645157-6b616180-667d-11e9-9dc4-c1909c68db9f.png)

**Comment by kwiatekus** [comment]
@ly1ila we dont have copyright yet. So we shouldnt shjow the copyright character

**Comment by ly1ila** [comment]
Update: 
<img width="1441" alt="kyma_version_footer_w_copyright" src="https://user-images.githubusercontent.com/25120433/56646179-5c7bae80-667f-11e9-87b3-9c6bd81fc22d.png">

Zeplin: https://zpl.io/Vx06N7m

**Comment by ly1ila** [comment]
We decided to put it in the navigation bar to keep it visible regardless of the content length.

![image](https://user-images.githubusercontent.com/25120433/56652089-c64d8580-668a-11e9-8901-da4955a8aa29.png)

(Zeplin is updated)

**Comment by kwiatekus** [comment]
After consultation with @hardl we found yet another place to display version number.
According to Fiori3 guides, we could add an "About" menu item to the user profile dropdown in the shell bar. After clicking it, the user would see kyma version in a modal.
What do you think @ly1ila

**Comment by kwiatekus** [comment]
Kyma version should be displayed in a dedicated modal window, which opens after user clicks `About` menu item

![image (1)](https://user-images.githubusercontent.com/6783567/57456818-97c8d080-726e-11e9-9e37-41aa1c3dd628.png)

![image (2)](https://user-images.githubusercontent.com/6783567/57457756-66510480-7270-11e9-9771-4eb73724ada5.png)

**Comment by kwiatekus** [comment]
Displaying `Kyma Version` in help dropdown would require a feature on luigi side.
Please use `User Profile` (fully configurable) dropdown for until the it is possible to configure it as  part of help menu.

**Comment by kwiatekus** [comment]
There are 2 options:
 - It can be done using LuigiClient's 
`uxManager().showConfirmationModal()` (but without the kyma logo)
Currently, the dismiss button is always there (could be labeled with empty string not to have it visible), but Luigi team is working on a fix to make 
 - It can be done as modal microfrontend with small size
https://github.com/SAP/luigi/blob/master/docs/luigi-client-api.md#openasmodal

**Comment by pbochynski** [comment]
Please display also Kubernetes version.

**Comment by kwiatekus** [comment]
Proposed solution requires checking if current token allows to view deployments in namespace kyma-installer
https://kubernetes.io/docs/reference/access-authn-authz/authorization/#checking-api-access

The `About Kyma` menu item should be shown conditionally.

**Comment by y-kkamil** [comment]
blocked by: https://github.com/SAP/luigi/issues/603

**Comment by kwiatekus** [comment]
Postponing as we have a dependency to Luigi framework

**Comment by abbi-gaurav** [comment]
@kwiatekus, additionally we should enable the customers to add some metadata that can help easily manage the cluster. It could be simple key-value pairs but might be good that customers can provide it.

**Comment by tricky42** [comment]
This issue is now more than 8 month old, can you provide a concrete plan how and when this will be tackled?
