### ISSUE TITLE
Incorrect appearance of docs and tabs in catalog-ui and instances-ui

### ISSUE THREAD

**Issue by aerfio** [kyma-project/console#759]
**Description**

Library we are using to render markdown (react-markdown) is displaying content differently than it is on github (See GCP Broker): 
![image](https://user-images.githubusercontent.com/17271979/55733135-9614ae80-5a1d-11e9-9435-9ee91e81e88e.png)
There should be no `` ``` `` included in code section

Moreover, **NOTE** should be bolded

![image](https://user-images.githubusercontent.com/17271979/55733423-1affc800-5a1e-11e9-8a8e-6998ee5cc898.png)

and docs are exceeding its parent container on smaller screens 
![image](https://user-images.githubusercontent.com/17271979/55733541-497da300-5a1e-11e9-9168-62bfa3fe9ac9.png)

**Reasons**

Those issues should be fixed to create consistent professional UI experience

**Comment by aerfio** [comment]
Duplicate of https://github.com/kyma-project/kyma/issues/3907, which was already taken care of.

**Comment by magicmatatjahu** [comment]
Fixed by https://github.com/kyma-project/console/commit/d7df4678abb899b237445df930854063a66b0ba6
