### ISSUE TITLE
Add integration tests for components/react

### ISSUE THREAD

**Issue by aerfio** [kyma-project/console#766]
**Description**

Right now we have no validation of any change in components/react, as integration tests do not get triggered, we do not have to make separate PR in kyma repo. You could easily make changes in components/react that would make UI and UI integration tests fail, but this behaviour is not tested, you do not have to bump image when you update comp/react.

**Reasons**

 We should trigger integration tests on any change in comp/react 

**Attachments**

**Comment by kwiatekus** [comment]
Changing react/components would start pipelines for all applications that use them (service-catalog-ui, add-ons, content).
The usage of a new image version for any of those in kyma charts  would trigger integration tests
