### ISSUE TITLE
Restructure left navigation 

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#78]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- contribute to core to get result as in attached screen shot
- Service Catalog view becomes `Catalog` and a normal view without collapsible left nav
- Service Instances become `Instances` 
- (out of scope for now) New `Brokers` shows up but comment it out for now. You can already assume and provide a host for the view that we will create in the future
- All those 3 views are grouped under the `Service Catalog` header
- Dont remove anything what is not visible in the design

**Reasons**

- group all view from one domain under one header for better clarity
- resolve confusion about Service Instances that are confused with k8s Services

**Attachments**

![screen shot 2018-09-04 at 08 18 39](https://user-images.githubusercontent.com/6995927/45013597-f53fba00-b01b-11e8-8d10-6d0c43ef6c49.png)

**Comment by mjasinski5** [comment]
@magicmatatjahu
