### ISSUE TITLE
Test view for lambdas

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/console#780]
**Description**
Test lambda view should contain:
- choice how to invoke lambda (http request / event)
- event selector - you  can pick what event you want to test
- the input data editor with templates updated when you switch the trigger (request/event/event type)
- log live preview
- test button (invoke lambda with input data)

Test view should check if lambda is exposed (mandatory). Test button should call lambda through API gateway (exposed), pass the input data and display response.

**Reasons**
Developers want to test their lambdas easily.

**Attachments**
You can simulate event triggers sending event content as http request body. This is the way how event trigger works:
- event payload is received pushed to kubeless as a request body: https://github.com/kyma-project/kyma/blob/22675d2a177e945e23ae384f6017e3096edbdb74/components/event-bus/internal/push/handlers/message_handler.go#L53
- kubeless extracts body and sends it to lambda function as event.data:
https://github.com/kubeless/runtimes/blob/bdee7792a6d265a719a75e886071cbc4fb5f7295/stable/nodejs/kubeless.js#L66

To test it please you can create a lambda with 2 triggers (http and event) with following code:
```
module.exports = { main: function (event, context) {
    console.log(JSON.stringify(event.data));
} }
```
You can invoke lambda with the event (use application mock) or call it with http request:
```
curl https://your-lambda-url -d '{"prop":"value"}'
```
Both triggers will set event.data object.

**Comment by brendandobbs** [comment]
@pbochynski , are you suggesting that any event can be tested not just the ones configured in the event triggers? If we do it that way we would need to bypass the event bus and send the event directly to the lambda endpoint. I can see pros and cons of both approaches. Sending through the event bus has the advantage that we're testing the event subscription is also working.

**Comment by pbochynski** [comment]
> @pbochynski , are you suggesting that any event can be tested not just the ones configured in the event triggers? If we do it that way we would need to bypass the event bus and send the event directly to the lambda endpoint. I can see pros and cons of both approaches. Sending through the event bus has the advantage that we're testing the event subscription is also working.

My idea is to call lambda through http and bypass eventing. It is useful for testing code before you enable event trigger. UI should suggest payload for already configured event trigger and allow to pick any other event from the catalog.
