### ISSUE TITLE
<Filter/> components in instances and catalog have wrong styling

### ISSUE THREAD

**Issue by aerfio** [kyma-project/console#785]
**Description**

![image](https://user-images.githubusercontent.com/17271979/56576826-bc178280-65c9-11e9-9dde-713a01ddc01f.png)
![image](https://user-images.githubusercontent.com/17271979/56576842-c5a0ea80-65c9-11e9-9d5f-fec7d3070234.png)
After update to fundamental-react@0.5 <Dropdown/> component has transparent background and is right positioned, and in instances it's just on the wrong side

**Expected result**

It looks nice, as it should

**Actual result**

See screens above

**Troubleshooting**

I've tried to fix it it on my [branch](https://github.com/aerfio/console/tree/fix-catalog-instances) and it works in most of the cases

I've fixed how it looks in instances 
![image](https://user-images.githubusercontent.com/17271979/56577151-8fb03600-65ca-11e9-946b-001698f82dc6.png)

In most cases it looks right: 
![image](https://user-images.githubusercontent.com/17271979/56577238-c6864c00-65ca-11e9-8dff-6065cfe7a5bd.png)

But unfortunately sometimes it look like this in catalog
![image](https://user-images.githubusercontent.com/17271979/56577195-abb3d780-65ca-11e9-976b-c53544aaaf63.png)

to reproduce:
```bash
cd components/application-broker/contrib/examples/
kubectl create -f application.yaml
```
and then bind this app to some namespace, it should be bugged like this in catalog

**Comment by aerfio** [comment]
Further investigation: 
![image](https://user-images.githubusercontent.com/17271979/56580859-f2f29600-65d3-11e9-916c-2fa199c977e4.png)
I've placed appropriate console.logs in node_modules to see where does this prop change, and it seems it is never correctly passed to its child components - first 4 lines are from my component (Dropdown.js in components/react) and rest is from `fundemantal-react`


[this line](https://github.com/SAP/fundamental-react/blob/28ad8010382c0a27e9ae091919d12e6c9332d499/src/Popover/Popover.js#L65) works

[this](https://github.com/SAP/fundamental-react/blob/28ad8010382c0a27e9ae091919d12e6c9332d499/src/utils/_Popper.js#L93) doesnt

**Comment by aerfio** [comment]
compare line number to be sure, it's here 
![image](https://user-images.githubusercontent.com/17271979/56581967-71e8ce00-65d6-11e9-85da-2cdc10281b05.png)

**Comment by akucharska** [comment]
https://github.com/SAP/fundamental-react/issues/540

**Comment by akucharska** [comment]
![Screenshot 2019-05-13 at 08.51.53.png](https://images.zenhubusercontent.com/5b8683811dd32d2cc77238b0/bdc777e3-866e-4ce5-b5cf-580656032f72)
