### ISSUE TITLE
GET request with a large body (DoS risk)

### ISSUE THREAD

**Issue by pekura** [kyma-project/console#787]
**Description**

Console UI is served by nginx. It is configured to accept GET requests only, which is good.

**Risk** 

Bombarding the server with GET requests with a large body can lead to a denial of service situation.

**Suggested Mitigation**

Make sure to configure the nginx to limit the client GET request size.

**Comment by sergio-oss** [comment]
@kwiatekus  still applicable ?

**Comment by kwiatekus** [comment]
According to the documentation, nginx has a default value of :
`client_max_body_size :  1m`

This sounds reasonable to me
