### ISSUE TITLE
Console should only allow https microfrontend views

### ISSUE THREAD

**Issue by pekura** [kyma-project/console#788]
**Description**

Console UI supports 3rd party view plugins defined as (Cluster)Microfrontend k8s custom resources. The views defined there are rendered within the Console UI.

**Risk** 

The Microfrontend view URL can be specified as non-secure (http) compromising security of the Console UI. 

**Suggested Mitigation**

Browser might block it or show a warning but we should prevent rendering of such views in the first place.

**Comment by kwiatekus** [comment]
When trying to load microfrontend hosted via http, console blocks it already as mixed content is not allowed:
```
Mixed Content: The page at 'https://console.pijany.hasselhoff.ga/home/namespaces/default/mf-whatever' was loaded over HTTPS, but requested an insecure frame 'http://www.columbia.edu/~fdc/sample.html/'. This request has been blocked; the content must be served over HTTPS.
```
