### ISSUE TITLE
Simplify access to exposed APIs

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/console#790]
**Description**

Provide a button to copy API's URL to the clipboard and add the link to open the URL in the new tab/window. 
 - APIs list
- Exposed APIs list on service details

Do not list the service port behind the URL as people will think that this is the exposed port.

Additionally, separate the Service Port from the URL so it doesn't suggest that they belong together. 
Add a tooltip explaining what service Post is and how it should be used

**Reasons**
It should take about 1 second to navigate to exposed API.
In the list view, you have to select and copy hostname manually. In the API details page, the URL is split into 2 parts (host and domain), so you need to copy both and concatenate them.

**Comment by kwiatekus** [comment]
Put the service port to the next line and add a tooltip.
Remove the read-only name input from the `General Information` section
