### ISSUE TITLE
Provide documentation about metadata in markdowns

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/console#794]
**Description**

The Service Classes documentation is displayed in the console under the tabs which are defined by the metadata at the beginning of these markdowns.

We are missing the documentation about:
- how to define markdowns
- which types we support
- what is the order of displaying the docs in console
- what will happen if we don't define the markdown

**Reasons**

I need to mention about necessary metadata in the helm-broker documentation and I don't want to describe everything about it there. It would be better to have separate doc explaining this to which I could link in mine document.

**Comment by mmitoraj** [comment]
Create complete documentation about providing content in Kyma Console:
- what is markdown
- metadata and how to use it
- content and how to write it

**Comment by derberg** [comment]
We should not focus on metadata only as user first need to understand what markdown is at the end
I personally like https://devportal.yaas.io/tools/documentationsdk/index.html#ExaminetheDocumentStructure a lot

**Comment by derberg** [comment]
I feel this section https://kyma-project.io/docs/master/components/helm-broker#details-service-classes-documentation-provided-by-bundles-documentation-structure is not needed or we at least need a link to https://kyma-project.io/docs/master/components/headless-cms/#details-markdown-documents.

Also broken link here https://github.com/kyma-project/kyma/pull/3804/files#diff-6ba5a1727b8f946251d2d9175a34c14aR115, shouldn't it link here https://kyma-project.io/docs/master/components/helm-broker#details-service-classes-documentation-provided-by-bundles-documentation-structure

**Comment by mmitoraj** [comment]
@derber,
- re: the first comment - the section is removed and the link added in the [pull request](https://github.com/kyma-project/kyma/pull/4216)
- re: the second comment - link fixed
