### ISSUE TITLE
One step provisioning flow

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#80]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- remove the `circle` wizard steps indicators
- all shows up as step one
- `Name` stays. Improve validation:
  - When you load a provision form to the user and we already know that for example `redis-instance` name already exists, then we should generate `redis-instance-2` name and increment in case more instances are coming. 
  - disallow name with spaces or special characters
- `Plan` and `Labels` stays as it is for now. Only look if it is possible to place name, plan and labels next to each other in one row, if it will look better.
- Then below above fields have a clear separation ruler and input parameters below, the one coming from plan schema
- modal form scale from maximum from top to bottom of the screen. In case not all fits the screen show scroll bar to the user to indicate scrolling is needed
- update tests if needed
- update OSBA contract docs

**Reasons**

- simplify provisioning
- avoid making magic solutions in 2 step wizard to change it into one step wizard in case custom plan schema is provided or not

**Comment by mjasinski5** [comment]
Review: @akucharska @mjasinski5
