### ISSUE TITLE
Make core navigation items configurable

### ISSUE THREAD

**Issue by hardl** [kyma-project/console#801]
There might be usecases where a customer wants to completely disable some core nodes (non-microfrontend-cr) in the navigation, regardless of permissions.

AC:
* Configuration option in console configmap to disable core nodes, either single nodes or whole categories (e.g. '/operations/*' ?)
* Add information do console docs about this feature

**Comment by kwiatekus** [comment]
Proposed solution:
Enable user to configure `disabledNavigationNodes` via console's config map.
For example:
```
disabledNavigationNodes: [
"operations.pods",
"operations" // <-- whole category is gone
]
```
