### ISSUE TITLE
Integrate Knative Function Controller as Optional Module

### ISSUE THREAD

**Issue by joek** [kyma-project/console#804]
**Description**

Integrate Knative Function Controller as a Optional Module:

AC:
- Install Controller when enabled
- E2E Test for controller
- Documentation as part of Kyma Docs with Experimental flag (check with Barbara how to do it)

**Reasons**

All new Features have to run in context of kyma. As a developer I like to right away integrate them and give a preview for customers who like to enable the feature.

**Tasks**
- Migrate controller from incubator into components repo
- Create an Installer Module for Function Controller
- Implement Prow Job to create Controller Image
- Implement Tests (Backup, Upgrade, "Test" maybe called component test)
- implement integration webhook tests
- Implement E2E test (copy kubeless e2e test as far as it is working)

**Comment by Abd4llA** [comment]
Function controller is now optional module. Closing.
