### ISSUE TITLE
Back arrow does not work properly in Service Catalog view

### ISSUE THREAD

**Issue by mszostok** [kyma-project/console#805]
**Description**

In console, we have the Service Catalog View, with two tabs: **Add-ons and Service**. Using the *back* arrow in a given **Service** Details view 
<img width="1337" alt="Screen Shot 2019-05-06 at 12 29 30" src="https://user-images.githubusercontent.com/17568639/57220446-a5c2eb00-6ffb-11e9-80e6-d062dbd0b0f0.png">

results always in getting back to the **Add-ons** view instead of going to **Service** window.

**Comment by kwiatekus** [comment]
Invalid
