### ISSUE TITLE
Improve displaying of the bind credentials

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/console#806]
**Description**

Bind credentials modal which contains envs with a long name is displayed badly.

**Expected result**

Bind credentials modal handles long names.

**Actual result**

<img width="682" alt="Screenshot 2019-05-06 at 12 37 47" src="https://user-images.githubusercontent.com/21159554/57220607-41ecf200-6ffc-11e9-9d69-f2ddf909cf7b.png">

![image](https://user-images.githubusercontent.com/21159554/57220640-6b0d8280-6ffc-11e9-904b-2b62b1dddd1a.png)

**Comment by kwiatekus** [comment]
Problem also happens when displaying secrets
![image (11)](https://user-images.githubusercontent.com/6783567/77059055-9e6bbc80-69d6-11ea-8b56-af8704f26129.png)

**Comment by kwiatekus** [comment]
@Wawrzyn321 please make sure image with bugfix is bumped in kyma

**Comment by kwiatekus** [comment]
Fixed
