### ISSUE TITLE
Improve create namespace modal 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#818]
As a user I want to create namespace.

AC:

- User can define name & labels
- User can define resource quotas and limit ranges (optional)
- User input for memory settings is validated (validation for memory units according to k8s regexp : showing red error masg (see design) or green tick )

https://app.zeplin.io/project/5ab0db46508f1e7a678a01c1/dashboard?seid=5cd555a683b4fc5dee460a0b

**Comment by kwiatekus** [comment]
By default :
 - sidecar injection is enabled
 - limits per namespace and pod are disabled

**Comment by pbochynski** [comment]
Can I request additional improvements? 
1. The focus should be in the namespace name input box - I want to start typing immediately.
2. Enter key should work as submit button.
