### ISSUE TITLE
Create new component for rendering OData EDM in Data Model visualization 

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#821]
**Description**

- Create a new component that can be used anywhere
- Check if the best location is some official OData organization on GitHub, or better keep it in Console
- Have good communication about the new component, examples and a blog
- Follow https://github.com/SAP/fundamental

**Reasons**

Because of the nature of OData, users prefer to not just see raw reference documentation but also a visual representation of the data model described by the EDMX files that describe OData

**Attachments**

![Kyma_Catalog_API-Specs_Header_General-Infos- Data Modul](https://user-images.githubusercontent.com/6995927/57978747-31cd0d80-7a13-11e9-815d-2ad3b146c992.png)

**Comment by kwiatekus** [comment]
This issue didnt get required attention for so long.
Closing for now, as it was not a priority for so long
