### ISSUE TITLE
Content-ui acceptance tests fails randomly

### ISSUE THREAD

**Issue by akucharska** [kyma-project/console#822]
**Description**

Testing of content-ui randomly fail

See logs:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1125757043936858116 
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1126064822316699648
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1126527751927369728

**Expected result**

Test test-core-core-ui-acceptance doesn't fail without the reason.

**Actual result**

Random fails of docs-ui-test

**Steps to reproduce**

Random fails on standard kyma installation

**Troubleshooting**

**Comment by a-thaler** [comment]
please verify if valid
