### ISSUE TITLE
Implement websockets for catalog view

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/console#825]
**Description**

Implement WebsSockets support for updating any 'live' data (for example, instance statuses) on catalog view, as it is currently absent there. We can base our work on the implementation in instances view.

**AC**
The following items should be automatically updated  via web sockets
- service classes list (incl. counter of instances on service class tile component)
- the service instances list (+ statuses) on service class details view 

Service catalog UI requires major refactoring

**Comment by kwiatekus** [comment]
Will be done (apollo autopolling) within https://app.zenhub.com/workspace/o/kyma-project/console/issues/1340
