### ISSUE TITLE
Add a tooltip text for the environment name

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#83]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

The tooltip should appear on hover (over the environment name) containing the name of environment

- on the overview page
- on the environment selector

**Reasons**
 
The environment name can be long and the ending could get cut off in case it doesnt fit in the view port.

**Comment by hardl** [comment]
will be fixed by https://github.com/kyma-project/luigi/issues/193
