### ISSUE TITLE
Application list is not updated after binding the application to the namespace

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#839]
**Description**

Application list is not updated after editing one of the applications in a separate tab.

**Expected result**

Applications list should update if any application has been changed. 

**Actual result**

Application list is not updated after binding (or unbinding) the application to the namespace.

**Steps to reproduce**

* Open applications in two separate tabs
* In tab number 1 go to the application details
* Bind (or unbind) it to any namespace 
* In tab number 2 the 'Connected namespaces' column is not updated

**Troubleshooting**

It looks like the 'update' event is not received by the console at all, so it's probably a bug on the backend side.

**Comment by sjanota** [comment]
Same with status change

**Comment by kwiatekus** [comment]
Application view will be replaced by compass MF.

**Comment by kwiatekus** [comment]
Soon this view will be deprecated
