### ISSUE TITLE
UI for binding application service classes selectively

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#847]
**Description**

Allow selective binding of application's service classes to the namespace
Backend will be provided within https://github.com/kyma-project/kyma/issues/3843

**UI/UX views**

<img width="1084" alt="Screen Shot 2019-05-10 at 10 53 33" src="https://user-images.githubusercontent.com/9609118/57515035-04e17200-7312-11e9-8fa7-6fed5f1ee742.png">
<img width="1081" alt="Screen Shot 2019-05-10 at 10 55 26" src="https://user-images.githubusercontent.com/9609118/57515098-25a9c780-7312-11e9-96a2-1f41063e479d.png">
<img width="1079" alt="Screen Shot 2019-05-10 at 10 56 06" src="https://user-images.githubusercontent.com/9609118/57515189-52f67580-7312-11e9-89c9-2f8d82c65974.png">
<img width="1076" alt="Screen Shot 2019-05-10 at 10 57 37" src="https://user-images.githubusercontent.com/9609118/57515268-7e796000-7312-11e9-95a0-1926d61f40d8.png">
<img width="1079" alt="Screen Shot 2019-05-10 at 10 58 34" src="https://user-images.githubusercontent.com/9609118/57515322-a10b7900-7312-11e9-9155-15f515a4dc3d.png">

**Comment by kwiatekus** [comment]
edit (pencil) and remove (bin) binding icons will be handled globally in all console as a separate task

**Comment by kwiatekus** [comment]
See the API changes :
https://github.com/kyma-project/kyma/issues/3843#issuecomment-496135934

**Comment by akucharska** [comment]
![Screenshot 2019-06-17 at 13 31 12](https://user-images.githubusercontent.com/20790348/59601800-65c84b00-9105-11e9-8530-bd5b6b767074.png)
![Screenshot 2019-06-17 at 13 31 29](https://user-images.githubusercontent.com/20790348/59601801-65c84b00-9105-11e9-9590-496ef545131b.png)
