### ISSUE TITLE
Show notification in console if resource quota has been exceeded

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#85]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

We need a mechanism in console that:

- does the graphql call
- checks the result, if limit exceeded or not
- if exceeded, shows a "global" alert notification (see https://sap.github.io/fundamental/demo-pages/alert-overlay-demo-page.html)

This mechanism should be triggered after:
- switching the environment
- ~uploading a resource~ (not possible when limit exceeded)
- creating a lambda, i.e. we need to add such a "checkLimitRequest to our postmessage protocol (later it will be handled by custom events in Luigi)
- open environment details

**Reasons**

We want to inform the user if the resource quota for his environments is exceeded.

**Comment by kwiatekus** [comment]
API to show ResourceQuota was exceeded is already merged to Kyma master.

Example query to ask for status in a given namespace:
```
query{
  resourceQuotaStatus(environment:"kyma-system"){exceeded, message}
}
```

If the ResourceQuota is not exceeded, the endpoint returns:

```
"resourceQuotaStatus": {
      "exceeded": false,
      "message": ""
    }
```

If the ResourceQuota is exceeded it returns:

```
"resourceQuotaStatus": {
      "exceeded": true,
      "message": "ReplicaSet: redis-client-6467cb78f5, has 4/7 replicas running. It cannot reach the desired number of Replicas because you have exceeded the ResourceQuota limit."
    }
```

Message is optional.

For more information, check the proposal: [https://github.com/kyma-project/kyma/blob/master/components/ui-api-layer/docs/proposals/exceed-resource-quota.md]

**Comment by polskikiel** [comment]
The ResourceQuotaStatus query looks as follows:

```graphql
query{
  resourceQuotasStatus(environment:"production"){
    exceeded
    exceededQuotas{
      quotaName
      resourceName
      affectedResources
    }
  } 
}
```
This query returns two types of response: exceeded and not exceeded.
Not exceeded response looks as follows:
```graphql endpoint doc
  "data": {
    "resourceQuotasStatus": {
      "exceeded": false,
      "exceededQuotas": []
    }
  }
```
Exceeded response can look like this:
```graphql endpoint doc
{
  "data": {
    "resourceQuotasStatus": {
      "exceeded": true,
      "exceededQuotas": [
        {
          "quotaName": "kyma-default",
          "resourceName": "limits.memory",
          "affectedResources": [
            "ReplicaSet/redis-clientxd-5df45c4998",
            "ReplicaSet/redis-clientxd-5df9544d7f"
          ]
        },
        {
          "quotaName": "custom-quota",
           "resourceName": "requests.memory",
           "affectedResources": [
             "StatefulSet/example",
             "ReplicaSet/redis-clientxd-5df9544d7f"
           ]
         },
      ]
    }
  }
}
```
- **exceeded** equals `true` if any ResourceQuota is exceeded.
- **exceededQuotas** contains the list of exceeded ResourceQuotas limits and set of resources which exceed the limits.
- **quotaName** represents the name of the ResourceQuota with exceeded limit.
- **resourceName** represents the name of the resource which exceeded the ResourceQuota limit.
- **affectedResources** contains the list of resources which exceed the defined **resourceName** limit from the **quotaName** ResourceQuota.

Values from **affectedResources** are strings combined from [resourceKind/resourceName].
