### ISSUE TITLE
API Expose ui tests improvements (k8s-api-util more generic, remove waitfor)

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/console#859]
**Description**

1. Currently, ui tests for API Expose functionality use util classes from `k8s-api` folder (they are used to create/remove different kind of k8s resources), that are very similar to each other. Make them more generic to avoid code duplication.

2. The same test creates namespace/deployment/service, and then waits 15 seconds for these resources to become active (around line 135, `console-basic.test.js`). It not a deterministic time, implement some kind of status check for these resources.

**Comment by kwiatekus** [comment]
Done with https://app.zenhub.com/workspace/o/kyma-project/console/issues/1221
