### ISSUE TITLE
Improve listing of service instances

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#86]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- [x] rename column `Bindings` to ` Bound Applications` 
- [x] status on hover should show a system tooltip with `status.message`. White text on black background
- [x] clicking plan name should display details in a modal (as shown in attachment), details are part of the ServiceInstance object, spec.parameters
- [x] cleanup redis bundle from helm broker to not contain redisPassword field but have it autogenerated as this is better and more secure approach as proper security standards for complexity of the password can be applied without user interaction (@polskikiel)

**Reasons**

- improve usability
- make it possible to check basic info without checking details of the instance

**Attachments**

![screen shot 2018-09-04 at 14 38 47](https://user-images.githubusercontent.com/6995927/45031824-48cbfb00-b050-11e8-8ebc-f443a3dfb124.png)>

**Comment by PK85** [comment]
Check if we need to update ui-test regarding listening instances.

**Comment by aszecowka** [comment]
Depends on PR #526

**Comment by aszecowka** [comment]
Real-time update of a service instances list, was moved to the task console#156
