### ISSUE TITLE
Improvements for API UI

### ISSUE THREAD

**Issue by tricky42** [kyma-project/console#860]
* Provide a button to copy the URL of the exposed API into clipboard
* (Optional) Provide in addition a link to open another tap/window with the URL of the API
* The current UI is a bit confusing, as from the layout it looks like the Service Port is the port under which the API is exposed. I think it would be better if
**  we seperate the Service Port from the URL so it doesnt suggest that they belong together
** we add some explanation what the Service Port is and how it should be used...

**Comment by kwiatekus** [comment]
Duplicates https://github.com/kyma-project/console/issues/790
