### ISSUE TITLE
UI does not update lambda authentication status

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/console#866]
**Description**

When going through the Gateway example@[Manual Exposure Using Kubectl](https://github.com/kyma-project/examples/tree/master/gateway#manual-exposure-using-kubectl) I saw that the UI does not update the authentication status.

**Expected result**

The authentication status of the lambda function is correctly shown in the UI.

**Actual result**

See the screenshot. UI thinks there is no authentication on the lambda function.

**Steps to reproduce**

Follow the documentation at [Manual Exposure Using Kubectl](https://github.com/kyma-project/examples/tree/master/gateway#manual-exposure-using-kubectl):

```bash
$ export KYMA_EXAMPLE_NS=automatix-example-gateway
$ kubectl create ns $KYMA_EXAMPLE_NS
$ kubectl label ns $KYMA_EXAMPLE_NS env=true
$ kubectl apply -f ./lambda/deployment.yaml -n $KYMA_EXAMPLE_NS
$ kubectl apply -f ./lambda/api-without-auth.yaml -n $KYMA_EXAMPLE_NS
```

Now the UI looks as follows: 
![image](https://user-images.githubusercontent.com/8013145/57867531-9b75cd80-7801-11e9-904e-7860e28e9c5e.png)

The api object says that there is no authentication enabled, which is correct. Also correct in the UI.

```
$ kubectl get api -n $KYMA_EXAMPLE_NS hello -oyaml
  authentication: []
  authenticationStatus:
```

However, when enabling authentication the UI still does not show authentication enabled :
```
$ kubectl apply -f ./lambda/api-with-default-auth.yaml -n $KYMA_EXAMPLE_NS
```

Now the api says that `authentication is enabled`:

```$ kubectl get api -n $KYMA_EXAMPLE_NS hello -oyaml|grep authentication
spec:
  authentication: []
  authenticationEnabled: true
status:
  authenticationStatus:
    code: 2
    resource:
      name: hello
      ...
  validationStatus: 2
  virtualServiceStatus:
    code: 2
    resource:
      name: hello
      ...
```

Then go to `https://{cluster}/home/namespaces/{namespace}/cmf-lambdas/details/hello` and click on `http`.

UI still says that no authentication is enabled:
![image](https://user-images.githubusercontent.com/8013145/57870059-a41cd280-7806-11e9-94bf-2d0e26bed2f9.png)

Same for API:
![image](https://user-images.githubusercontent.com/8013145/57870108-b5fe7580-7806-11e9-9b92-79cad4ccd23c.png)

**Troubleshooting**

**Comment by kwiatekus** [comment]
We will rework the whole lambda ui.
