### ISSUE TITLE
Resource Quota Popup not shown on Lambda View

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/console#870]
**Description**

Resource quota popup not shown immediately after creating a lambda when resource quota is hit.

**Expected result**
The resource quota dialog get's shown immediately after the function is saved.

**Actual result**
Resource quota dialog is only shown then going to a different view such as `Overview`. Dialog is only shown for `Lambdas` view then editing the function and saving it.

![image](https://user-images.githubusercontent.com/8013145/58086665-5b2a9c80-7bbf-11e9-90a3-fdb0460a1919.png)
![image](https://user-images.githubusercontent.com/8013145/58086681-6382d780-7bbf-11e9-8f8c-1d19166bbaf9.png)

**Steps to reproduce**

When creating a new lambda via the UI while having not enough resources left (simulate by lowering the memory in Resources->Resource Quotas->kyma-default), there is no dialog complaining about hitting the quota limit (see screenshot 1).
However, if you go to `Overview` afterwards, the popup appears.
If you dismiss the popup and go again to `Lambdas` view the popup does not appear. However, then editing the function and saving it, the popup finally appears (screenshot 2)

**Troubleshooting**

**Comment by kwiatekus** [comment]
UI fro serverless functions will be reworked completely
