### ISSUE TITLE
Lambdas Testable from Console UI - usability improvements ( part 1 )

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#882]
**Description**

Implement low hanging usability improvement that would encourage developers to use log UI when developing and testing a lambda.

The main objectives here would be :
 - opening logs in a way that developers can watch them as they go on with development
 - simple auto-refresh of the log streams
 - filtering out log data which pollutes the streams
 - enabling new function "size" - limited to one replica - giving the developer only one log stream source 
 - Hiding (by default) log streams from old versions of the lambda

**Comment by damien-murphy** [comment]
It would be great if the user could click logs on a lambda or service and see logs that the infrastructure generates separated from the logs that console.log generates.
