### ISSUE TITLE
Lambda details 'jwt' error (unauthorised HTTPS endpoint only)

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#887]
**Description**
A weird error appears in browser console when I enter Lambda details page and lambda has an **unauthorised** HTTPS endpoint. The error is gone when I make my HTTPS endpoint authorized or remove it completely.
![image](https://user-images.githubusercontent.com/22825433/58481792-65b7d980-815d-11e9-8f04-b830883298ad.png)

**Expected result**
The error does not appear

**Actual result**
The error does appear

**Steps to reproduce**
(look at the description)

**Troubleshooting**

**Comment by kwiatekus** [comment]
UI for serverless functions will be reworked soon
