### ISSUE TITLE
Enrich details view of the instance

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#89]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- make plan name clickable and on click show modal and in it spec.parameters of the instance (like in main instance list as described here https://github.com/kyma-project/console/issues/86)
- display new fields, `Labels` with instance labels  (if not provided, do not display that field) and `Documentation` with link to metadata.documentationUrl (link opens in new tab. If not provided, do not display that field)
- update OSBA contract docs

**Reasons**

- have more details of the instance available for the user

**Attachments**

<img width="1106" alt="screen shot 2018-09-04 at 19 02 12" src="https://user-images.githubusercontent.com/6995927/45046112-77100180-b075-11e8-9fa3-3ba1fc52af7e.png">

![screen shot 2018-09-04 at 14 38 47](https://user-images.githubusercontent.com/6995927/45046096-68c1e580-b075-11e8-9621-1b2595844645.png)

**Comment by mjasinski5** [comment]
Review: @pkosiec @akucharska
