### ISSUE TITLE
Documentation should be hidden if 'cms' module is disabled

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#893]
**Description**

Documentation node in the top navigation should be hidden if 'cms' module is disabled.

**Expected result**

If documentation module is disabled, the documentation shouldn't be visible. Also, all links (navigation nodes) to the documentation should be hidden.

**Actual result**

The top nav node for documentation is always visible, even if documentation module is disabled. User can go to the documentation view, but this view crashes.

![Screen Shot 2019-05-30 at 11.44.58.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/67286616-c720-4b49-ad3f-7169a801e40f)
(development mode)

**Steps to reproduce**

- Run Kyma with cms module disabled
- Click on documentation node (question mark) in the top navigation
- Documentation is not accessible, the view is not rendered  

**Troubleshooting**

**Comment by kwiatekus** [comment]
was never bothering any customer or internal team. Was discover by manual removal of cms module. It was renamed to rafter.
It is really stale now
