### ISSUE TITLE
Add Event trigger modal has its model inconsistent with the lambda details page

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/console#913]
**Description**

The modal in which you can add/remove event triggers for lambda functions seems to be broken. If you add an event trigger, and then delete it (without saving) the modal will behave in a weird manner:

1. Create a lambda function, save it.
2. Click on 'Select Function Trigger' -> 'Event Trigger'
3. Choose one of the events and 'Add' it
4. Remove it from the lambda editor
5. Once again, open the  'Select Function Trigger' -> 'Event Trigger' modal

You will see that the previously added event is still marked there as 'checked' and you cannot select/deselect it, since the 'Add' button is inactive then.

**Comment by dariadomagala** [comment]
Major refactor planned for lambda-ui
