### ISSUE TITLE
Cannot change lambda size if created with 'minimal' yaml

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/console#914]
**Description**

If you create a lambda using provided definition file (either via kubectl or 'deploy new resource..' button from the UI) you will not be able to edit its size afterwards, even though the lambda is fully functional.

**Expected result**

After lambda creation it is possible to change its size.

**Actual result**

User can choose function size from the dropdown, but after save and refresh, the value is ignored.

**Steps to reproduce**

1. Apply provided lambda definition.
2. Go to the lambda details
3. Change lambda size to 'M'
4. Save lambda --> It's back to 'S'

```---
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: hello3
spec:
  function: |-
    module.exports = {
        main: function (event, context) {
            return 'hello world';
        }
    }
  runtime: nodejs8
  handler: handler.main

**Comment by kwiatekus** [comment]
It is rather an edge case.
In the outlook of planned changes (migrating to knative) we will not fix it for kubeless based lambdas
