### ISSUE TITLE
Extended Header for Service Details View

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#929]
Implement page header for service details view:

- move all read only data to the header
- include delete button (use existing gql delete mutation)
- fetch data using existing gql query
![kyma_services_detail_header](https://user-images.githubusercontent.com/6783567/59043146-0142fb80-887c-11e9-81c3-45a248a69e0d.png)

**Comment by kwiatekus** [comment]
already done

**Comment by dariadomagala** [comment]
it's not done :)
