### ISSUE TITLE
Define event subscription for service

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#956]
**Description**

As a micro-service developer I would like to subscribe  my service to events available in my namespace (from console UI).

The user should be able to:
1. select a service
2. choose event from available events
3. define rest endpoint on the service side that will consume the events (manually in the first version)

AC:
- user can define new (multiple) event subscriptions on service details view
- user can see existing event subscriptions for a given service (for full consistency, lambda event subscriptions must be reflected)

**Note**

Subscribing events to lambdas doesn't differ much on technical level - it also comes down to defining a subscription object binding the lambda's service instance with the event. This fact should be taken into account and we should aim for a  consistent UX around subscribing events both to services (directly) and lambdas.

**Attachments**

Example illustrating the use case : https://github.com/kyma-incubator/examples/tree/master/microservice-event-trigger#create-the-kyma-subscription

**Comment by derberg** [comment]
keep in mind that in case of service and also lambda it should be possible in UI to provide a name of  an even and other data also manually if such service doesn't exist on the list. It is a use case for applications that send events but did not provide event asyncapi schema.

**Comment by michal-hudy** [comment]
https://github.com/kyma-project/kyma/issues/7216

**Comment by kwiatekus** [comment]
Done in 1.14
