### ISSUE TITLE
Add API specifications to an Application in Console UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#961]
**Description**

As a Console User I want to add an API spec to an Application using file(s) on my disc.

AC:
 - User should be able to browse / drag&drop multiple files that will specify the APIs spec for the new service class
- the type of the API (AsyncAPI/OpenAPI/OData) should be auto detected based on the uploaded file

**Reasons**

Quick and Simple way to addAPI spec and use it inside Kyma.

**Draft UI**
https://app.zeplin.io/project/5ab0db46508f1e7a678a01c1?seid=5d10d57eac061f70b5e37a70

**Comment by kwiatekus** [comment]
**Things to consider**:
 - should the option to add service class be available for all apps?
        - self-managed apps? (those which auto-register their APIs? )
        - already paired apps?
- raise user awareness about potential breaking the contract
- Unify terminology : Specifications / Apis / Services&Events
- Its still unclear if and how we should allow defining Event Specs for unpaired apps

**Comment by akucharska** [comment]
This will be a feature of compass
