### ISSUE TITLE
Response (Unauthorized : 401)  doesn't redirects to the login page

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#97]
**Description**

401 error should cause that the user is redirected back to the login page. 

**Expected result**

Console should intercept any 401 error and redirect the user back to the login page

**Actual result**

Now it works properly only on the main view, but when you open any other route, there is just an error message, but no redirection.

**Comment by kwiatekus** [comment]
Lets validate if its still the case

**Comment by dariadomagala** [comment]
Could not recreate.
