### ISSUE TITLE
Documentation without front matter metadata is rendered incorrectly

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/console#975]
**Description**

It is a common case when documentation doesn't contain front matter metadata. In such case, not everything is well rendered. For example, tables don't work.

**Expected result**

![image](https://user-images.githubusercontent.com/26445970/60085184-228b5f00-9739-11e9-8d03-a4afbb3c9e91.png)

**Actual result**

![image](https://user-images.githubusercontent.com/26445970/60085205-28814000-9739-11e9-8ced-3ed85f17bb54.png)

**Steps to reproduce**

Use the following markdown:

```markdown
Doesn't work :(

| Test | Table |
| ---- | ----- |
| Test | Value |

## Other

Some additional text
```

**Comment by magicmatatjahu** [comment]
Fixed in https://github.com/kyma-incubator/documentation-component/pull/5
