### ISSUE TITLE
First header in documentation is ignored

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/console#976]
**Description**

When the header is in the first line of a document then it is ignored. It can be a common case when some external documentation is used.

**Expected result**

![image](https://user-images.githubusercontent.com/26445970/60085680-0a680f80-973a-11e9-8c5b-1530c07b316a.png)

**Actual result**

![image](https://user-images.githubusercontent.com/26445970/60085658-01773e00-973a-11e9-87a3-cb3251e69208.png)

**Steps to reproduce**

Use the following markdown:

```markdown
## First Header

Some text

### Next Header

Some additional text
```

**Troubleshooting**

**Comment by magicmatatjahu** [comment]
Fixed in https://github.com/kyma-incubator/documentation-component/pull/5
