### ISSUE TITLE
HTML is not well rendered in documentation component

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/console#977]
**Description**

When you look at this [document](https://github.com/awslabs/aws-servicebroker/blob/master/templates/athena/README.md) on GitHub it looks OK. In our documentation component, it is not well rendered.

**Expected result**

![image](https://user-images.githubusercontent.com/26445970/60086801-0f2dc300-973c-11e9-89bb-0ef04c66b26f.png)

**Actual result**

![image](https://user-images.githubusercontent.com/26445970/60086838-1f45a280-973c-11e9-842e-1b41a8cef9bf.png)

**Steps to reproduce**

Use provided documentation

**Comment by magicmatatjahu** [comment]
Fixed in https://github.com/kyma-incubator/documentation-component/pull/5
